### ISSUE TITLE
[Feature Request] Provide ability to add withXXX methods for mutable objects

### ISSUE THREAD

**Issue by KangoV** [rzwitserloot/lombok#1003]
We have got into the habit of adding with methods to out mutable dto objects that return the containing type as a return value. This really makes code easier to use. When using @Builder i see that the builder methods return the Builder, so this is just an extension to the main class.

For example:

```java
Game myGame = new MyGame()
    .withName("name")
    .withAge(18)
    .withDescription();
```

**Comment by rspilker** [comment]
We already support two featers that cover this:
- [`@Wither`](https://projectlombok.org/features/experimental/Wither.html)
- [`@Accessoers(chain=true)`](https://projectlombok.org/features/experimental/Accessors.html)

Using 'withXxxx' is typically used in immutable datastructures. I suggest you use the chaining feature to return the enclosing type from setters instead of `void`.

**Comment by KangoV** [comment]
Yeah, sorry for the spam, been away. Just used that and it works well. Thanks for closing.
