### ISSUE TITLE
@NonNull should not throw a NullPointerException

### ISSUE THREAD

**Issue by Nehon** [rzwitserloot/lombok#1013]
I know it's maybe nitpicking... But the NonNull annotation should throw an IllegalArgumentException instead of NullPointerException.

The reason is that a NullPointerException means that you are trying to dereference something that is null. That's not what is happening here, you're feeding a method with a null parameter that shouldn't be null.

Giving a null argument to a method that requires a non null argument is a typical use case for the IllegalArgumentException. The exception name itself makes a lot more sense to me. Maybe just make the message "argumentName shouldn't be null".

my 2 cents.

**Comment by rspilker** [comment]
First of all, you can configure lombok to throw an IllegalArgumentException using `lombok.config`. See also the documentation on the [`@NonNull`](https://projectlombok.org/features/NonNull.html) page and the [configuration system](https://projectlombok.org/features/configuration.html).

Secondly, we follow the guidelines from Effective Java. 

Thirdly, without an explicit check, an NullPointerException would probably implicitly be thrown by actually dereferencing the parameter. 

Even if you would be right, we wouldn't change the default behavior since that would break backwards compatibility.

The message we generate for parameter `x` is "x is null".

**Comment by Nehon** [comment]
The config file is enough for me.
Thanks
