### ISSUE TITLE
Add possibility to annotate annotations

### ISSUE THREAD

**Issue by AugierLe42e** [rzwitserloot/lombok#1136]
Currently, `@Value`, `@AllArgsConstructor`, etc. cannot be applied to annotations. A cool feature would be to add this possibility to let user compose his own set of annotations. For instance, let the user do the following:

```
@Value
@Builder(builderClassName = "Builder")
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PRIVATE, force = true)
public @interface CustomBean {
}
```

so that the following:

```
@CustomBean
public class Bean{
}
```

is equivalent to:

```
@Value
@Builder(builderClassName = "Builder")
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PRIVATE, force = true)
public class Bean{
}
```

**Comment by thisisthekap** [comment]
+1 for Meta Annotations.

On 23 Jun 2016, at 09:23, Augier <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently, @Value, @AllArgsConstructor, etc. cannot be applied to annotations. A cool feature would be to add this possibility to let user compose his own set of annotations. For instance, let the user do the following:

@Value
@Builder(builderClassName = "Builder")
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PRIVATE, force = true)
public @interface CustomBean {
}


so that the following:

@CustomBean
public class Bean{
}


is equivalent to:

@Value
@Builder(builderClassName = "Builder")
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@NoArgsConstructor(access = AccessLevel.PRIVATE, force = true)
public class Bean{
}


-

**Comment by Maaartinus** [comment]
Duplicate of [issue 557](https://github.com/rzwitserloot/lombok/issues/557) and many others. Please do a quick search before opening an issue. Please use the smiley in the top right corner for voting instead of +1.

**Comment by AugierLe42e** [comment]
> Duplicate of issue 557 and many others. Please do a quick search before opening an issue.

Guys, you have 15 pages of issues. A quick search gives me at leat 6 or 7 pages of issues. I *did* a quick search. But I have other things to do when I'm at work than going through pages of results ;)

**Comment by xak2000** [comment]
But now, when you are know that this is duplicate, why not close this issue?
To ensure that subsequent searches did not return so many pages.

**Comment by AugierLe42e** [comment]
> But now, when you are know that this is duplicate, why not close this issue?

I thought there was a good reason you kept it open ;)

**Comment by xak2000** [comment]
Sorry, I'm not related to this project anyhow, so I can't close issues of other people. :)
I just was looking for the same functionality (meta-annotation) and found these 5 open issues.
