### ISSUE TITLE
How to setup Lombok project on Android JACK compiler?

### ISSUE THREAD

**Issue by NeoLSN** [rzwitserloot/lombok#1150]
http://tools.android.com/tech-docs/jackandjill

I tried to add `provided 'org.projectlombok:lombok:1.12.6' annotationProcessor 'org.projectlombok:lombok:1.16.8'` in build.gradle, but it is not work.
Does anyone know how to setup?

**Comment by nksaroj** [comment]
I am getting the following error 
java.io.IOException: com.android.jack.api.v01.CompilationException: Failed to compile 

http://stackoverflow.com/questions/38345665/java-io-ioexception-com-android-jack-api-v01-compilationexception-failed-to-co

**Comment by ChristopheMaldivi** [comment]
Hi,

If you look at jack doc (https://developer.android.com/preview/j8-jack.html), it indicates:
>Because Jack does not generate intermediate class files when compiling an app, tools that depend on these files do not currently work with Jack. Some examples of these tools are:
> -Lint detectors that operate on class files
> -Tools and libraries that require the app’s class files (such as instrumentation tests with JaCoCo)

Sounds not good to me...

**Comment by shibenli** [comment]
it may mean we can't use lombok util it has do with '.jack'

**Comment by georgeworkhard** [comment]
is there any tool to generate java code based on the tags ? getter and setter can be generated conveniently, how abt builder?

**Comment by jaredsburrows** [comment]
You can use Retrolambda's for now: https://github.com/jaredsburrows/android-gif-example/blob/master/build.gradle#L96.

**Comment by shibenli** [comment]
I don't know whether #1166 by @jBouyoud will help for this issue @rzwitserloot

**Comment by rspilker** [comment]
Did you test with lombok 1.16.10? It contains cec8705c3b9fa6488d53bec5bb4eab27a6decf85 that might take care of it.

**Comment by shibenli** [comment]
@rspilker I have replaced
```
    provided 'org.projectlombok:lombok:1.16.10'
    apt 'org.projectlombok:lombok:1.16.10'
```
with
```
    provided 'org.projectlombok:lombok:1.16.10'
    annotationProcessor 'org.projectlombok:lombok:1.16.10'
```
But Jack also give me  the error(Error:Execution failed for task ':app:transformJackWithJackForDebug'.
> java.lang.AssertionError: java.lang.IllegalArgumentException). I want to know wheather lombok or jack cause this failed.

**Comment by FWest98** [comment]
I've taken a quick look into the causes of the problems with Jack and they don't seem too easy to solve.
First of all, the first error is caused by this line here: https://github.com/rzwitserloot/lombok/blob/aa2f4424a78b962edf0b7e0ef551a82c5822619a/src/core/lombok/core/AnnotationProcessor.java#L149
This is due to none of the ProcessorDescriptors returning true. I've tried removing the typecheck here (https://github.com/rzwitserloot/lombok/blob/aa2f4424a78b962edf0b7e0ef551a82c5822619a/src/core/lombok/core/AnnotationProcessor.java#L74) since the package is just renamed at that part, but then further down the line there are CastExceptions here (https://github.com/rzwitserloot/lombok/blob/aa2f4424a78b962edf0b7e0ef551a82c5822619a/src/core/lombok/javac/apt/LombokProcessor.java#L84). It seems that Jack has quite a different structure than Javac so I think quite some work has to be done in order to make Lombok compatible with Jack. I don't have the knowledge (nor time) to do this unfortunately...

**Comment by rspilker** [comment]
Jack is end-of-life: https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html
