### ISSUE TITLE
@EqualsAndHashCode annotation - problem with coverage

### ISSUE THREAD

**Issue by marcinpin** [rzwitserloot/lombok#1199]
I am using sonar to analyze and measure source code quality. I have problem with coverage methods hashCode and equals when I use @EqualsAndHashCode annotation.

I cannot cover this part of code and sonar reports an issue:
1 - if (!(o instanceof EqualsAndHashCodeExample)) return false;
2 - EqualsAndHashCodeExample other = (EqualsAndHashCodeExample) o;
3 - if (!other.canEqual((Object)this)) return false;

When I put another class if I expected then first line is covered.
When I put correct class if I expected then second line is covered.
When I covered before lines then I cannot cover third line.

What do you think about this? Thanks for reply.

**Comment by KangoV** [comment]
Try using [EqualsVerifier](http://jqno.nl/equalsverifier/). I've got 100% (not with a builder though).

**Comment by rzwitserloot** [comment]
The solution is to not let your code coverage tools check lombok code. Assume lombok code is bug free. In order to produce bug free code speedily, we generate 'safeties' that might very well be impossible to make happen.

lombok generates various `@Generated` annotations that you can use to make your code verifier skip these. You can add more via lombok.config (run `java -jar lombok.jar config` for more info; the key you probably want is `lombok.addLombokGeneratedAnnotation`).
