### ISSUE TITLE
[sugestion] add the ability to define "with" in the method of @Builder

### ISSUE THREAD

**Issue by sbuisson** [rzwitserloot/lombok#1209]
for a lot of people, the methode of a builder start with "with". Can you add a way to define it when we use the annotation Builder ?

Sample:

```
@Builder(prefixMethod="with")
 class ProductIndex{
 private String objectID;
}
```

```

 class ProductIndex{
        private String objectID;
...
    public static class ProductIndexBuilder {
        private String objectID;

        ProductIndexBuilder() {
        }

        public ProductIndex.ProductIndexBuilder withObjectID(String objectID) {
            this.objectID = objectID;
            return this;
        }
```

**Comment by ChrisBrenton** [comment]
I do not like this idea.

I do not believe it adds anything to the generated program, but it does add to the complexity of Lombok. I also see this as a feature that would go largely unused. Ultimately, as long as you have intelligently named fields, it is immediately intuitive, with generated javadoc, what the method does.

**Comment by redijedi** [comment]
Some companies, 3 I've coded for so far, have required the "with" prefix in their coding conventions. This basically prohibits lombok use. It seems like using a prefix is fairly common.

**Comment by rzwitserloot** [comment]
Lombok is opinionated, at times.

It is of the opinion that 'with' is for immutables; it implies that it returns a new instance, and that the thing you called it on is immutable or close to it.

builders are the opposite of that. They are mutable by definition.

It doesn't really matter how many companies have added it to their coding conventions. It's a stupid coding convention we shall not support.

**Comment by redijedi** [comment]
That's subjective. If lombok has decided that in light of @Wither, a "with" prefix would be confusing, then that's understandable. Hand waving and simply calling something that is actually fairly common and mostly benign "stupid" is rude, but I've come to expect that from Belgians.

**Comment by Maaartinus** [comment]
@redijedi I call it "stupid", too, but maybe you can explain, how such a funny convention might arise? There's a standard prefix "set", which is used by JDK and vast majority of libraries. Some prefer fluent setters using no prefix at all, and this is understandable as it makes code shorter and arguably more readable. I could imagine someone using sole "s" a prefix, but *what may be the reason for using a longer non-standard prefix?*

**Comment by rspilker** [comment]
See also https://immutables.github.io/immutable.html#copy-methods

**Comment by redijedi** [comment]
It's tough to speculate as I haven't been there for the inception of these standards. I can imagine that the standard comes from a simple way of speaking "build foo with this and with that." There are at least a few notable instances of prefixes in use. 

- Quartz uses it in its builders: http://www.quartz-scheduler.org/api/2.2.1/index.html
- Lombok-PG found prefixing common enough to add to their extension (https://github.com/peichhorn/lombok-pg/wiki/@Builder-@Builder.Extension). The builder from before the Lombok core team thought builder would be a good idea.

Builders in Java probably are still not a massively prevalent feature. So I think it's premature to say what an idiomatic use would be.

As far as readability, I can make the case that for english speakers using "with" is more readable. "I want to build X with Y and Z" is common speech.

FWIW, I personally don't care. I like lombok a lot and want to use it at every company I work for. However, in almost every circumstance, I've been met with resistance. Usually the fight is about how "magical" lombok is, or FUD re the uncertainty of what it produces. I can handle those debates. Standards nonconformance, however, is a simple way to prevent me from getting lombok into my organizations. I, and I'm sure others, would benefit from some flexibility in order to make lombok usage low friction. That is as much a political exercise as it is a technical one.

**Comment by pedro-borges** [comment]
Was there ever any development on this issue?
