### ISSUE TITLE
@Value toString pattern

### ISSUE THREAD

**Issue by mbjelac** [rzwitserloot/lombok#1211]
It would really really really be awesome if:

```
@Value(toString="fib({})={})")
class FibonacciExample {
    int input;
    int result;
}
```

generated a `toString` method returning the specified pattern, replacing `{}` placeholders with field references in declaration order:

```
public String toString() {
    return "fib(" + input + ")=" + result;
}
```

Optionally, this can be done as a shortcut to the hypothetical feature in `@ToString`:

```
@ToString(pattern="fib({})={})")
class FibonacciExample {
    int input;
    int reasult;
}
```

**Comment by ChrisBrenton** [comment]
This doesn't really feel like a necessary feature. You want a specific way implementation of toString for your class, which isn't really boilerplate.

**Comment by ChrisBrenton** [comment]
I feel that I probably misinterpreted the usefulness of this, however, I think some modification to the suggested implementation is required. For example, one might wish to print out one field more than once so, in this case, {input} to print out the value of input

Credit to rzwitserloot for this suggestion.

**Comment by rzwitserloot** [comment]
I really like this idea. It'd have to go on `@ToString` and not `@Value`, the rule would be that `{fieldName}` is a field access, in case of multiple consecutive `{` or `}`, only the innermost count (so, `{{name}}={age}` would end up printing `{Joe}=10`. We need a way to do lists. How about:

`names={names:[A, B]|(empty)}`

which means: Print 'names' here, but treat it as iterable, using 'comma+space' as a separator, [ as prefix and ] as postfix (A and B have special meaning, and are always required) and in case of 0 elements, printing the string `"(empty)"` instead.

The obvious downside is that this turns into its own little language which is normally not a great plan, but, regex is also its own little language and it does allow you to be incredibly expressive. For example, we could add a symbol for using a custom method to render a given string.

That's getting ahead of ourselves; the first version of this would simply allow {} for field names, and will automatically enumerate iterables with the pattern: `[A, B]|[]`.

**Comment by mbjelac** [comment]
Field name access as proposed seems a bit verbose to me. If you don't accept my proposal of Logback-style `{}` references by declaration order, is it possible to have index references? `{0}` references first field, `{1}` second and so on? Is that even possible as Java reflection `Class#getFields` doesn't guarantee the ordering?

**Comment by rzwitserloot** [comment]
Veto on anything where you don't have to name the fields explicitly.

The downsides:

1. You can't double-visit a field (print it twice). It's probably not needed, but a minor niggle.
2. Lombok uses a way to get at the fields which preserves order, however, the VAST majority of the time where java field order would come up, it's because Class.get(Declared)Fields() is used, and those methods, as @mbjelac mentioned, do NOT preserve order. That means, in the java community, most people consider fields to be freely re-orderable, and that this won't change anything significant. Whilst lombok uses field order here and there (the arguments of lombok-generated constructors are ordered in the same order as the fields show up, and we calculate hashCode and equals in that order too), any change in order is self-documenting (in the case of the constructors) or shouldn't matter (equals/hashCode; only performance is potentially affected assuming non-broken equals/hashCode impls of members). This would simply silently change behaviour. That's not acceptable. A simple example of where the community tends to assume field order is not important to backwards compatibility: A LOT of code auto-formatters will freely re-order fields to be in static-> non-static order, and within a category, alphabetized.

**Comment by mbjelac** [comment]
I understand. Explicit names then. Any field name errors will show up at compile so that's good (better than at runtime, anyway).

**Comment by askoning** [comment]
Caught in umbrella #1297.
