### ISSUE TITLE
AllArgsConstructor does not utilize superclass fields

### ISSUE THREAD

**Issue by mpouttuclarke** [rzwitserloot/lombok#1229]
If I have a class with AllArgsConstructor and a superclass with AllArgsConstructor.  The generated code only populates the current class fields and does not call super class AllArgsConstructor

**Comment by beamofsoul** [comment]
+1

**Comment by alan-givati** [comment]
Definitely a problem in the current form - if I have inheritance all the super-class fields are effectively hidden.

**Comment by freemanke** [comment]
so the builder of child class also have no fields of super class, i think it should be an issue.

**Comment by artgo** [comment]
+1

**Comment by agirardeaudale** [comment]
+1

**Comment by Josef-Reichardt** [comment]
+1

**Comment by fgcui1204** [comment]
+1

**Comment by rspilker** [comment]
I know that this is very nice to have, however, since getting to the parent class required resolution, it is simply not possible.

**Comment by RuiFernandesCb** [comment]
@rspilker Has this issue had any development since 2017?

**Comment by Maaartinus** [comment]
@RuiFernandesCb AFAIK no and AFAIK nothing has changed as when Lombok runs, it can't get enough information about the superclass. What could be done is something like letting the user provide a
```
@SuperClassStub class Whatever {
    int x;
    int y;
    String name;
}
```
or (maybe better)
```
@SuperClassStub abstract void whatever(int x, int y, String name);
```
which would make Lombok remove the stub, prefix `int x, int y, String name, ` to argument lists of all constructors it generates and generate a `super(x, y, name)` call therein. This is not very satisfactory because of the field duplication (which has to be kept in sync), but it's not too bad as any mismatch would lead to a compile-time error.

Given the number of upvotes here, it could be better than nothing, WDYT?

**Comment by camilajenny** [comment]
it's said it's impossible due to way the java compilation stages https://stackoverflow.com/a/29771875/7769052 stack up
