### ISSUE TITLE
Incorrect @Synchronized("readLock") working

### ISSUE THREAD

**Issue by bsokolovu** [rzwitserloot/lombok#1241]
Hi!
Please take a look at attached source. 
Explicit blocking (with synchronized blockes) works fine, but synchronized annotation breakes all rules.
[BlockingTest.java.txt](https://github.com/rzwitserloot/lombok/files/601590/BlockingTest.java.txt)
jdk version is 1.8.0.112 and Lombok version is 1.16.10

p.s. also if you'll replace static logger with Slf4j annotation my Intellij Idea 15.0.3 will see it as a valid code but will give compilation error.

**Comment by Maaartinus** [comment]
I removed logging I didn't like, changed the delays to 1 second and tried it out in *Eclipse*. The outcome is always something like
```
20:27:20.523 [Thread-0] INFO  c.o.handlers.search.BlockingTest - task1 locked
20:27:21.527 [Thread-0] INFO  c.o.handlers.search.BlockingTest - task1 unlocked
20:27:21.527 [Thread-1] INFO  c.o.handlers.search.BlockingTest - task2 locked
20:27:22.527 [Thread-1] INFO  c.o.handlers.search.BlockingTest - task2 unlocked
20:27:22.528 [main] INFO  c.o.handlers.search.BlockingTest - main locked
20:27:23.528 [main] INFO  c.o.handlers.search.BlockingTest - main unlocked
```
The two tasks behave the same, the locking works, what would you expect? Does it behave differently in Intellij?

I also tried `@Slf4j` and lowercased the logger name and it worked fine. In case the problem is Intellij specific, you should probably [file an issue here](https://github.com/mplushnikov/lombok-intellij-plugin/issues).

**Comment by bsokolovu** [comment]
You're right, it looks like a problem of plugin for Intellij Idea.
