### ISSUE TITLE
Android Studio v2.2+ update

### ISSUE THREAD

**Issue by slightfoot** [rzwitserloot/lombok#1242]
Hi,
Just to let you know `android-apt` is built into the Android Gradle Plugin from v2.2+ and your documentation is out of date. See https://bitbucket.org/hvisser/android-apt/wiki/Migration for reference material.

The end of this doc should be updated: https://projectlombok.org/setup/android.html
with:
```
provided "org.projectlombok:lombok:1.16.10"
annotationProcessor "org.projectlombok:lombok:1.16.10"
```

**Comment by gradha** [comment]
I would like to add a suggestion on the Android instructions: replace the specific version numbers. Instead of 1.12.6 put X.YY.Z with a note below to check https://bintray.com/bintray/jcenter/org.projectlombok:lombok and use the latest version. As stupid as it sounds I had a project with this line verbatim, a version 2 years old.

**Comment by phiresky** [comment]
For android studio 3.0 it should be

```
    compileOnly 'org.projectlombok:lombok:1.16.18'
    annotationProcessor 'org.projectlombok:lombok:1.16.18'
```

**Comment by rspilker** [comment]
Nowadays, we automatically put the latest version in the online documentation whenever we release a new version.

We'll update the documentation.

**Comment by rspilker** [comment]
Will be part of the next release.
