### ISSUE TITLE
Lombok + eclipse + null-analysis: full compile OK, incremental incorrect

### ISSUE THREAD

**Issue by sylvainlaurent** [rzwitserloot/lombok#1248]
I'm using lombok 1.16.10 with eclipse 4.6.1 Null reference analysis.
Consider the following class:
```
import static org.eclipse.jdt.annotation.DefaultLocation.*;
import org.eclipse.jdt.annotation.NonNullByDefault;
import org.eclipse.jdt.annotation.Nullable;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@NonNullByDefault({ PARAMETER, RETURN_TYPE, TYPE_BOUND, TYPE_ARGUMENT })
public class MyPojo {

	private @Nullable String nullableValue;
	private String nonNullableValue;

}
```

And this use of it:
```
	public static void main(String[] args) {
		MyPojo myPojo = new MyPojo();

		// eclipse should not complain
		myPojo.setNullableValue(null);
	}
```

If I clean the project, eclipse performs a full compilation and everything is OK.
If I touch the main method, eclipse performs an incremental compilation and incorrectly reports this error in the call myPojo.setNullableValue(null):
```
Null type mismatch: required '@NonNull String' but the provided value is null
```

FYI, if I hover the mouse on the call to setNullableValue(), the tooltip shows the signature as 
```
void test.MyPojo.setNullableValue(@Nullable String nullableValue)
```
which is correct. There's definitely something weird with the incremental compilation...

I attach an example project to reproduce : [lombok-eclipse-null-analysis.zip](https://github.com/rzwitserloot/lombok/files/617437/lombok-eclipse-null-analysis.zip)

**Comment by krkhnh** [comment]
I have a similar issue. But I'm not sure if the issue is from Eclipse or Lombok.

**Comment by krkhnh** [comment]
Here is an example. Please note the red underline is not `Error` but `Warning`. That is due to my custom IDE setting.
![code](https://user-images.githubusercontent.com/5172480/31430508-feee993a-aeab-11e7-9b2b-d5fd2fa485eb.jpg)

And here is my setting from Eclipse.
![settings](https://user-images.githubusercontent.com/5172480/31430527-152c951c-aeac-11e7-9556-26f70fe6b94b.jpg)

This setting actually warns me when I put `null` value for a `@Nonnull` parameter. But all those false alarms like above make things hard to debug.

**Comment by rzwitserloot** [comment]
Lombok will now copy the annotation along; if it doesn't, you can configure it to do so in lombok.config (but this nullable annotation is in the recognized built in list that lombok 'knows about' so that should not be necessary); this feature has been out for a while.
