### ISSUE TITLE
Implicit @RequiredArgsConstructor on @Data will be removed when using @NoArgsConstructor

### ISSUE THREAD

**Issue by blackanthrax** [rzwitserloot/lombok#1269]
```java
@Data
@NoArgsConstructor
public class Sample {
  
  @NonNull
   private String string;
```
Does not create a RequiredArgsConstructor, unless you add the annotation `@RequiredArgsConstructor`.

**Comment by askoning** [comment]
This is by design: any explicit constructor - which includes constructors from other Lombok annotations - will cause `@Data` to not generate others.

**Comment by grimly** [comment]
The bug wouldn't it be that it creates a default constructor with your non null string attribute ?
What default value your attribute would have ?

**Comment by askoning** [comment]
You'd have to set it before it's useful, but that holds for all fields. Note that `@NonNull` only prevents you from _setting_ a null value, its initial value doesn't matter.

`@Data` and `@NoArgsConstructor`  in combination with a `final` field will cause a compilation error as Java itself will not allow this field to remain non-initialised.

**Comment by Doogiemuc** [comment]
May I please reopen this issue. Please let me explain why:

In a standard hibernate java application every managed entity needs a NoArgsConstructor, so that the container can create entity classes. So the example given at the top is quite common. For another reference that states the same problem, see for example this stack overflow question: https://stackoverflow.com/questions/37671467/lombok-requiredargsconstructor-not-working

The most common case actually _IS_ that one needs automatically generated getters, setters, a NoArgsConstructor **and** a RequiredArgsConstructor.

**So I'd like to suggest that this should be the default behaviour of the @Data annotation, becasue it is the most common scenario.**   

Why and where would any additional constructors ever hurt?  Lombok should create them. This is the behaviour that IMHO most users would expect.

**Comment by grimly** [comment]
If NoArgConstructor works, then RequiredArgsConstructor does nothing more.
If there is a change to be made maybe remove the first because the second does the same job on the same class.

> Why and where would any additional constructors ever hurt?

When your object grow and get new attributes, all the calls to the full constructor must be reworked again.

**Comment by ViniGodoy** [comment]
I have to upvote what  @Doogiemuc said. This is a fairly common scenario. Off course, you can solve all by having just the NoArgsConstructor and calling all setters, but this is error prone and its fairly common to have both constructors. 

The natural usage should be use @Data and include even more constructors with the constructor calls (No/All args). So, please consider reopening this issue, or at least, insert a parameter in @Data to insert both constructors.
