### ISSUE TITLE
Intellij, Jackson oddities with variables starting with 'x'

### ISSUE THREAD

**Issue by parry84** [rzwitserloot/lombok#1278]
I'm using Lombok 1.16.12 and IntelliJ Lombok plugin 0.14.16

Suppose I have a variable starting with 'x' as follow:

```
@Getter
@Setter
class MyModel {
    @JsonIgnore
    private String xMyField;
}
```

Suppose I have method using the generated getter as follow:
```
void myMethod(MyModel model) {
    println(model.getXMyField());
}
```

The code compiles and executes as expected but I face the following issues:
- With IntelliJ 2017.3, if I select 'xMyField' and click 'Find Usages' the IDE reports no usages, which is incorrect
- When serializing the model with Jackson, the 'xMyField' is included in the output despite the @JsonIgnore annotation.

If I remove the 'x' prefix (the variable is renamed 'myField') all the issues above disappears.

Regards,
Emanuele

**Comment by m-manu** [comment]
@parry84 
> With IntelliJ 2017.3, if I select 'xMyField' and click 'Find Usages' the IDE reports no usages, which is incorrect

I think you meant 2016.3

**Comment by parry84** [comment]
Yes it's 2016.3, thanks

**Comment by rzwitserloot** [comment]
Perhaps this issue is better posted here: https://github.com/mplushnikov/lombok-intellij-plugin/issues

**Comment by amseager** [comment]
This problem occurs not only with 'x' in front of fields and there is nothing wrong with lombok intellij plugin.

Every field starting with one lowercase letter causes jackson serializing problems. F.e. fields 'aTest', 'bTest', 'cTest' etc. will all cause this bug. 

It happens because for that type of fields Lombok is generating getters & setters with wrong names.
model.getXMyField() - should be model.getxMyField(). Same with setter.
Looks weird, but Jackson can only understand that type of names while converting json into object and vise versa.
If you try to generate G&S in IDEA and Eclipse the result will be correct (in this case, model.getxMyField()).

**Comment by rzwitserloot** [comment]
Duplicate of #2693
