### ISSUE TITLE
@EqualsAndHashCode doesn't generate '@Override' annotation

### ISSUE THREAD

**Issue by KroArtem** [rzwitserloot/lombok#1314]
Consider the following code:

```java
public class ComplexCall implements Serializable {
    some stuff here;
```
This stuff is mostly Hibernate mapping code. Consider there is no `equals()` and `hashcode()` methods. If I launch this project warnings from Hibernate are generated:
`WARN  [main][hibernate.mapping.RootClass] - HHH000038: Composite-id class does not override equals(): package.name.classname`

If I add `@EqualsAndHashCode` nothing changes as (delombok proves it) there is no `@Override` annotation.

If I add `equals()` and `hashCode()` generated by IDEA, there are no warnings.
 
I see there were some other tickets somehow related to this one: [this one](https://github.com/rzwitserloot/lombok/issues/1245)

Somewhere else I saw your reasons that you don't know anything about interface and cannot deduct about it. Has anything changed during this time? (I saw the first tickets dated from 2015 but cannot find them now).

**Comment by Maaartinus** [comment]
I don't think the other issue is related as it uses an interface with one mutable and one immutable representation and wants them to have a compatible equals.

I also don't think that the `@Override` annotation should be missing, see e.g., [this test](https://github.com/rzwitserloot/lombok/blob/aa2f4424a78b962edf0b7e0ef551a82c5822619a/test/transform/resource/after-delombok/EqualsAndHashCode.java#L7). Isn't a different class the culprit rather than the one you put `@EqualsAndHashCode` on?

The message doesn't speak about missing `@Override` annotation on an overriding method; it complains about a missing method. This all should work (I'm using Lombok with Hibernate, too; they both do some magic, but their magic paths don't conflict as Lombok is long done when Hibernate starts).

**Comment by KroArtem** [comment]
Hello, sorry for such a long answer. It was probably something with IDEA as currently everything is ok.

Closing this ticket as irrelevant.
