### ISSUE TITLE
@EqualsAndHashCode always using object.equals?

### ISSUE THREAD

**Issue by SamDeBlock** [rzwitserloot/lombok#1321]
Lets assume following classes:
```java
@EqualsAndHashCode
public class Foo {
    private int fooProperty;
    private Bar bar;
}
```

```java
@EqualsAndHashCode
public class Bar {
    private int barProperty;
    private int barProperty2;
}
```

Then the generated equals method on Foo contains the following snippet:
```java
Object this$bar = this.bar;
Object other$bar = other.bar;
    if(this$bar == null) {
        if(other$bar != null) {
             return false;
         }
    } else if(!this$bar.equals(other$bar)) {
        return false;
    }
return true;
```
By assigning this.bar and other.bar to variables of type Object. The equals method on Bar is never called.
In some cases this breaks equality where foo1.getBar().equals(foo2.getBar()) returns true, but foo1.equals(foo2) returns false.

**Comment by Maaartinus** [comment]
I may be wrong, but *"By assigning this.bar and other.bar to variables of type Object."* sounds like you're misunderstanding how overridden method calls work. Any method call on an object (i.e., non-static) performs dynamic dispatch, i.e., it looks the method up in the actual (rather than declared) class of the receiving object (as if every method was declared `virtual` in C++). So calling `x.m()` and `((Object) x).m()` are exactly equivalent.

In case I'm misunderstanding you, a concrete example of the error would surely help.

**Comment by SamDeBlock** [comment]
Never mind, completely overlooked something. We are temporarily stuck using an old version of JTS, which defines a 
```java
public boolean equals(Geometry g) 
```
method instead of equals(Object o), which was the actual cause of our issue.
