### ISSUE TITLE
@NonNull creates dead code in Eclipse

### ISSUE THREAD

**Issue by filibe** [rzwitserloot/lombok#1368]
Hello,
I have the following problem in Eclipse. When I unable the "Null analysis" using lombok annotations I get a warning about dead code when I use @NonNull to a method parameter.

The following code will have a warning where I use the @NonNull in the constructor:
```Java
import lombok.Getter;
import lombok.NonNull;

public class LombokExample
{
  @NonNull
  @Getter
  private String nonNullAttribute;
  
  public LombokExample(@NonNull String nonNullAttribute)
  {
    this.nonNullAttribute = nonNullAttribute;
  }
}
```
I used delombok to see the generated code and it looks like this:
```Java
  public LombokExample(@NonNull String nonNullAttribute)
  {
    if (nonNullAttribute == null)
      throw new NullPointerException("nonNullAttribute");
    this.nonNullAttribute = nonNullAttribute;
  }
```
I believe the @NonNull annotation should be removed in the generated code in order to avoid the dead code warning in Eclipse.

**Comment by rspilker** [comment]
We leave the `@NonNull` on the parameter for documentation purposes. If you want to generate javadoc, you need that annotation there.

**Comment by filibe** [comment]
Hi Roel,
I do not understand your answer. If I set javadoc to the method, it will not remove the "dead code" warning.

**Comment by rspilker** [comment]
What I meant is that in order to generate javadoc, you typically run delombok and then run the javadoc compiler on the delomboked code.

But it is actually unrelated to your Eclipse problem. Because of the different way we process the eclipse files, we were unable to remove the annotations.

Sorry if that interferes with your plan to use the lombok annotations in the Eclipse the null analysis.

Actually, I thing the Eclipse null analysis is in a way broken, since it doesn't allow for actually enforcing the nullness.

My problem with it is that I both want to document that you shouldn't pass null values _and enforce that_.

This is especially useful for maintainers of libraries, where you cannot depend on the users of you library also configured their null analysis correctly.

My suggestion is that you file a bug report on Eclipse that they should allow for code to verify the nullness.
