### ISSUE TITLE
FingBugs reports Bad Practice Warning in @Wither

### ISSUE THREAD

**Issue by jacek99** [rzwitserloot/lombok#1415]
Comparison of String parameter using == or != in  ....domain.Simulation.withId(String)
	
   Bug type ES_COMPARING_PARAMETER_STRING_WITH_EQ (click for details)
   In method ....domain.Simulation.withId(String)
   Actual type String
   Value loaded from id
   Value loaded from ....domain.Simulation.id
   At Simulation.java:[line 52]

Java code:

   @Wither
    public class Simulation  {
        private String id;

**Comment by Maaartinus** [comment]
The behavior is intentional: A fast `==` test can save you needless copying. Using `equals` would do it more often, but it can be costly. It's an optimization decision assuming that the object and its copy are equivalent.

Just add `lombok.extern.findbugs.addSuppressFBWarnings=true` to your `lombok.config` to keep it shut.
