### ISSUE TITLE
Consider support kotlin

### ISSUE THREAD

**Issue by freezhan** [rzwitserloot/lombok#1416]

**Comment by javatlacati** [comment]
FYI Kotlin still has some Issues with annotation processing so it's too early for having some cool lombok features.

https://stackoverflow.com/questions/35517325/kotlin-doesnt-see-java-lombok-accessors

Moreover it will not work on the same module:

https://discuss.kotlinlang.org/t/kotlin-java-lombok-interop/1442

but the good news is that you can recue something with kapt see #1169

**Comment by fzyzcjy** [comment]
Hi is there any updates? thanks!

**Comment by rzwitserloot** [comment]
@fzyzcjy I don't even know what this issue is asking, so, I have no idea. But probably no updates now nor in the foreseeable future, whatever this is asking.

(It may be asking: I want to annotate things in my kotlin code and get lombok to generate kotlin code for me! - which is unlikely to ever happen. Or it is asking: When kotlinc is in mixed mode, compiling java files in addition to kotlin files in intermix mode, I want lombok to work on the java source files at least. Which it just will, out of the box, if kotlinc _does not_ break annotation processor invocations, but it does, or at least, it did, in 2017. Any updates? I dunno. You're on the bug list, file something over at kotlin's bug tracker I think).

Or it means something even more exotic. I'm pretty sure all roads lead to: No.

**Comment by fzyzcjy** [comment]
@rzwitserloot thanks for the reply!

> When kotlinc is in mixed mode, compiling java files in addition to kotlin files in intermix mode, I want lombok to work on the java source files at least. 

Personally I am asking this. Well ok... then may need to find some workarounds

**Comment by rzwitserloot** [comment]
@fzyzcjy Assuming kotlinc still doesn't fire annotation processors properly, possibly file a bug (it's on them to fix that, I can't make that happen for them short of forking `kotlinc`, which I also can't do, at least, I don't think it's open source either). I'm going by old info here, I don't use kotlin. If there _is_ something project lombok can do to make this work, Pull Requests are welcome. No current core maintainers have the requires experience and motivation to pick this up.

**Comment by fzyzcjy** [comment]
@rzwitserloot Thank you!
