### ISSUE TITLE
@RequiredArgsConstructor does not respect @NonNull fields in superclass

### ISSUE THREAD

**Issue by alvint** [rzwitserloot/lombok#1499]
version 1.16.16

```
@Getter
@Setter
public abstract class Parent {
  @NonNull
  protected Integer someProperty;
}

...

@Getter
@Setter
@RequiredArgsConstructor
public class Child extends Parent {
  @NonNull
  private String otherProperty;
}
```

The constructor generated is `Child(String)` instead of `Child(Integer, String)`.

Another problem is that fixing this may cause some existing code to no longer compile (bump version maybe?). Although you could (legitimately) argue that any existing code with this issue is actually a coding error so that code **should** break.

BTW, any javadocs on the fields don't get transferred over to the constructor (and it would be nice if the argument names matched instead of just using `arg0`, `arg1`, etc). I'm too lazy to file a bug for that though.

**Comment by wrprice** [comment]
`int` is a primitive and can never be null.

**Comment by Maaartinus** [comment]
@alvint Lombok in general can't work well with superclasses as it works in a compile stage when the information is not yet available.

It can't see the superclass field. Even it if could, there's no way of initializing it besides calling the super constructor (which you forgot to declare). So far it can't work, even if Lombok were perfect.

And now, another problems comes in: Lombok wouldn't see the super constructor either. This may get fixed one day... or not as it's a tough problem.

**Comment by alvint** [comment]
@wrprice Corrected. :)

**Comment by alvint** [comment]
@Maaartinus That's why I declared the superclass as abstract--the child class has to initialize the field instead of a constructor in the parent.

That's a good point about lombok working in the compile stage. I imagine there's a (super ugly) way to inspect the code to determine if it has a superclass, but it would probably be too hacky and  fragile to be worth it.

It's also quite ugly and redundant, but how about adding a `check` parameter to `@NonNull` something like `NonNull(check=Parent.class)`? Although I would admit that would be so embarrassingly ugly I wouldn't even document it.

**Comment by wrprice** [comment]
@alvint, my understanding is that `@NonNull` modifies the behavior of _other_ helpers in Lombok when they encounter a field or variable annotated as such.  The `@Setter` on the abstract class modifies its behavior to generate a method that throws NPE on receiving null input.  Since the setter is the only way for that field to be mutated from within its enclosing class, that's all Lombok needs to do.

@Maaartinus pointed out that `Parent` is declared without a constructor. That means, whether it happened to be `abstract` or not, it has an initial state where `someProperty == null`.  The `@NonNull` does not modify the default field initialization, nor would it enforce itself on a handwritten constructor.  If you have Lombok generate a constructor for you, using `@RequiredArgsConstructor`, then that helper will honor the annotation and force a null check.  (Aside: I thought to be "required" the fields would also need to be declared `final`?  I may be wrong on this part.) Also as a result, any subclass could no longer depend on a zero argument constructor and would be forced to call `super(Integer)`, and `Child` would fail to compile without it.

From the Child's perspective, which does use `@RequiredArgsConstructor`, at best it could look for _all_ of the parent constructors.  Is it possible to automatically limit to only a subset?  How?  There could be many; does it generate a suitable child constructor for _every_ constructor in Parent?

```
@Getter
@Setter
abstract class Parent2 {
    @NonNull private Integer value1;
    @NonNull private Integer value2;

    protected Parent(@NonNull String str) {
        value1 = str.length();
        value2 = 0;
    }
    protected Parent(Integer v1, Integer v2) {
        value1 = 0;
        value2 = (v1 == null ? 0 : v1) + (v2 == null ? 0 : v2);
    }
}

@RequiredArgsConstructor
class Child2 extends Parent {
    @NonNull private String str;
}
```

Does Child2 have one or two constructors?  If one, which?  If two, what if I knew I only wanted to expose one of them from the child?

```
@Generated
Child(String s1, String s2) {
    super(s1);
    str = nullCheck(s2);
}

@Generated
Child(Integer v1, Integer v2, String s1) {
    super(v1, v2);
    str = nullCheck(s1);
}
```

**Comment by alvint** [comment]
@Maaartinus exactly. See my other bug. :)

**Comment by alvint** [comment]
@wrprice as @Maaartinus pointed out, if Lombok could look for parent constructors, it could also (and should) look for the fields directly.

**Comment by alvint** [comment]
Maybe a slightly less horrible solution would be to add an `include` parameter to `@RequiredArgsConstructor`, like (citing the above example) `RequiredArgsConstructor(include="someProperty", includeType = Integer.class)`?

**Comment by alvint** [comment]
@wrprice yep, the child couldn't use a no-arg constructor (well, it _could_) because it needs to initialize `someProperty`. But that's beside the point of this issue, since we're trying to create one.

**Comment by Maaartinus** [comment]
> That's why I declared the superclass as abstract--the child class has to initialize the field instead of a constructor in the parent.

@alvint But that's impossible in Java. The field is private, game over.

Even if it wasn't, that's a very strange idea to let subclasses do the initialization.

> I imagine there's a (super ugly) way to inspect the code to determine if it has a superclass, but it would probably be too hacky and fragile to be worth it.

There indeed is such a thing, it's called resolution and and it's indeed too fragile.

> It's also quite ugly and redundant, but how about adding a check parameter to @NonNull

AFAICT no chance. Implementing new Lombok features is orders of magnitude more difficult than a similar thing in an annotation processor. The maintenance is even worse as Lombok can't use a proper stable API.

Therefore a feature doing something strange has no chance. A feature requiring resolution has no chance either. This one is both.

---

> Maybe a slightly less horrible solution would be to add an include parameter to @RequiredArgsConstructor, like (citing the above example) RequiredArgsConstructor(include="someProperty", includeType = Integer.class)?

This would work for a single field only.

There's a similar proposal for specifying the super-constructor to be called, but don't keep your fingers crossed. There are tons of feature requests and hardly any progress recently. The authors concentrate on stability and Java 9 compatibility.

**Comment by alvint** [comment]
@Maaartinus yep, i left out the multiple args stuff for simplicity of expressing the concept. I figured you'd automatically add it.

**Comment by alvint** [comment]
@Maaartinus crap, the field should not be private. Editing...

**Comment by rspilker** [comment]
For all generated constructors, we currently cannot use any information from the super type, since that would require resolution. This also goes for builders. Without manually adding that information to each subclass, I do not see this working anytime soon. And adding information about the parent class is also a horrible solution. So we're kinda stuck here. I'm closing this issue, not because I think it isn't important, but because I don't see how we can solve it. Sorry.

**Comment by alvint** [comment]
@rspilker Is it feasible that the new tech used in \@SuperBuider could also apply to this problem somehow?
