### ISSUE TITLE
can lombok support RowMapper of jdbcTemplate 

### ISSUE THREAD

**Issue by asmburning** [rzwitserloot/lombok#1575]
generate a RowMapper to support jdbcTemplate use @RowMapper or alike ,when i change my model property,i don't need to modify RowMapper

**Comment by andang76** [comment]
+1

**Comment by raharvi** [comment]
+1

**Comment by janrieke** [comment]
This feature request seems to be very Spring-specific. Can you point out where such a feature makes sense without using Spring? Could you provide a general example (including a proposed lombok annotation/syntax and the lombok-generated code)?

**Comment by andang76** [comment]
It could be more general if, instead of returning directly a Rowmapper instance, the method generated by lombok returns the object itself built from a ResultSet:

for example:

`
@ResultSetBuilder
public class Person { 
   private String name; 
   private String cell;
   ...
}

generates method:

public Person fromResultSet(ResultSet rs) {
    Person p = new Person();
    p.setName(rs.getString("name");
    p.setCell(rs.getString("cell");
    return p;
}

having this method, I could use it in a Rowmapper for Spring or another framework.

builder generation could be customized by some simple field annotations, like @Column(name="first_name"), and so on


`

**Comment by rspilker** [comment]
I suggest using a mapping framework for this. See also #2181
