### ISSUE TITLE
Add option to super-call in builder constructor

### ISSUE THREAD

**Issue by Thyaris** [rzwitserloot/lombok#1635]
Add a new attribute to `@Builder`, determining if there will be a super call in the builder constructor.

My use case:

* There is a class `Message`, containins an attribute `type`.
* There are sub-classes like `LoginMessage`, that have attributes like `username`.
* Both `Message` and `LoginMessage extends Message` are annotated with `@Getter`, `@Setter` and `@Builder`, thus `LoginMessage` provides `getType()`
* When built with `LoginMessageBuilder`, `getType` will always return null for a LoginMessage
* I am setting the type in the constructor of `Message`, but that constructor is not called upon `#build()`

**Comment by victorwss** [comment]
I think that you either misunderstood some thing or failed to explain it correctly.
The constructor of the superclass must be called by the constructor of the subclass, the builder can't do anything about that. Also, if `LoginMessage` provides `getType()`, why it is stored in `Message` instead of `LoginMessage`? What does the `getType()` of the `Message` actually means?

Can you provide a code of what you want to write as lombok-spiced code and what you expected to be the equivalente delomboked code?

**Comment by Thyaris** [comment]
As I wrote an example, I just recognized that the error came from something else. I got NullPointerExceptions due to bad architecture, fixed the architecture and got another NullPointer, but it wasn't from the `_type`.
It works, and it should have worked before, I think the error was somewhere else.
Thank you, you are a good rubber duck 😄 

> The constructor of the superclass must be called by the constructor of the subclass, the builder can't do anything about that.

It's called implicitly actually, and I should have known this from the beginning.
And yes (and no), the builder also generates a contructor in the target class which he calls.
