### ISSUE TITLE
Installer & Eclipse: "I can't find any IDE" when "eclipse.ini" has been renamed.

### ISSUE THREAD

**Issue by AndrewBourgeois** [rzwitserloot/lombok#1666]
The installer can't find the Eclipse IDE if the "eclipse.ini" file has been renamed.
Renaming the file back to "eclipse.ini" fixes the issue.

**Comment by Maaartinus** [comment]
@AndrewBourgeois Is this an issue? But there must be *something* the installer looks for. No matter what you choose, there are chances that somebody renames it. How would you solve this?

**Comment by AndrewBourgeois** [comment]
I wrote the ticket so that others can find it should they face the same issue.
I don't think that someone needs to spend time on a fix for this.

If someone really wants to improve the installer for this use case: I'd solve this by adding a combobox in the installer where you have to select your IDE before you open the file selection dialog so that you can force the user to select the INI file instead of a dialog (if Eclipse was selected earlier).

**Comment by rspilker** [comment]
Well, it's always an Eclipse-like installer, so actually any ini-file would do. That said, I think that this use case isn't worth the troubles now.

The installer needs two things right now:
- a place to put `lombok.jar`
- an ini file to modify

We now determine the one with the other.

It would make it possible to also use the lombok installer on other eclipsy products. Then again, you can also do it manually.

I'm closing this issue since it's served its purpose.

**Comment by avinashpratapsingh** [comment]
I saved as eclipse.ini to STS.ini and placed lombok.jar under -vmargs option and ran lombok.jar once again and this time it worked.
