### ISSUE TITLE
Why not use maven?

### ISSUE THREAD

**Issue by cholf** [rzwitserloot/lombok#1686]
a lot of persons use maven,hope to support maven,thanks.

**Comment by cholf** [comment]
Any way to change to maven pro?How do you release it to the maven repository？ Or  a zip link to download ? I try to change it to maven pro,but failure .Thanks.

**Comment by andrebrait** [comment]
Gradle would be a much better option, specially since it can do basically everything ant can, including renaming files and whatnot (you can even integrate ant right into Gradle).

**Comment by FilipMalczak** [comment]
I already had a look with the same idea, that it should be rewritable to gradle.

Not that easy, unfortunately. Ant file is really long and a lot of stuff that is going there is weird (understandable, since we're tweaking the compiler). I guess that unless you're part of core lombok team and know pretty well how the build works like, you won't be able to rewrite it.

**Comment by rspilker** [comment]
The build script is very complicated, since we need to compile stubs, stubs for stubs, some code needs to be compiles twice, once using -target 1.4 and once with a higher class file version, for backward compatibility. All thing that are not possible in maven, unless you also write maven plug-ins.
