### ISSUE TITLE
Installation for Eclipse in system directory

### ISSUE THREAD

**Issue by Smedzlatko** [rzwitserloot/lombok#1700]
Hi, I am quite struggling with installing `lombok` to my Eclipse running on Ubuntu 18. Even when running the installer as `root`, it still complains that it cannot write to `/snap/eclipse/12` directory, because of missing permissions. Could someone point me to the correct procedure of installation to a system directory?

**Comment by adrsant** [comment]
Hi, maybe you need to change the permissions of  directory (/ snap / eclipse), try running this command on the linux terminal :
sudo chmod 777 -R /snap/eclipse

**Comment by Maaartinus** [comment]
I don't think so. The root just doesn't care about the standard file modifiers, the access is always granted. There may be other kind of permissions missing or a different problem producing a wrong error message, I can't tell. Concerning writing to the directory, I'd try `echo > /snap/eclipse/12/foobarbaz` as root, maybe the reason becomes clear.

@Smedzlatko Maybe temporarily granting the whole subtree to yourself (`chown -R smedzlatko /snap/eclipse`), installing Lombok and then changing back might work.

**Comment by rspilker** [comment]
You can `install` lombok by hand, modifying `eclipse.ini`. To get the instructions, launch `lombok.jar` and click on the link "Show me what this installer will do to my IDE installation".

**Comment by JazminGonzalez-Rivero** [comment]
I am having this issue as well, is the only current option to install it by hand?

**Comment by fireboy1919** [comment]
Just to give a little more perspective, the way to get a nice, current version of eclipse on ubuntu is to install it with snap (https://snapcraft.io/).  
Snaps are self-contained and read-only squashfs volumes that ubuntu mounts (squashfs is always read-only, so you can't get around that with chmod) using the snap command.  Its especially appealing for eclipse because of how difficult java is to version, and that java versions don't line up with ubuntu releases.

So the problem isn't "we need to install it by hand."  It's that *we can't install it in a read-only partition*.

As I see it, I think we have four options, really:
1. We could use overlayfs to add a layer on top that is writeable in order to modify eclipse.ini.
2. Add an argument to eclipse startup so that it uses a different eclipse.ini.
3. Install eclipse manually (and then KEEP installing it manually every time we need an upgrade).
4. Figure out how to make lombok work the same way that all the rest of the eclipse plugins do - where it doesn't need to write to eclipse.ini to work.

I don't really like any of the options except the last one; they all seem like kludges.  Unfortunately, I don't know how to do the last one (or if it's possible).

**Comment by benda0ud** [comment]
Hi,
Try [this link](https://askubuntu.com/questions/1051926/how-to-make-eclipse-installed-via-snap-use-a-differerent-configuration-when-star/1051927#1051927). I used it to copy my eclipse.ini and add -javaagent:lombok.jar. It's working.

**Comment by anton-k11** [comment]
> Hi,
> Try [this link](https://askubuntu.com/questions/1051926/how-to-make-eclipse-installed-via-snap-use-a-differerent-configuration-when-star/1051927#1051927). I used it to copy my eclipse.ini and add -javaagent:lombok.jar. It's working.

Yep, That works. Thanks
