### ISSUE TITLE
Missing static import makes unrelated classes fail to compile

### ISSUE THREAD

**Issue by gabor-farkas** [rzwitserloot/lombok#1713]
I created the simplest reproduction I can:
https://github.com/gabor-farkas/lombok-bugreport

Basically, given a class A
```java
package a;

import lombok.Builder;

@Builder
public class A {
    private String a;
    public static void main(String [] args) {
        A.builder().a("a").build();
    }
}`
```
And a class B
```java
import static a.A.MISSING;

public class B {

}
```

The compilation of class A also fails:
```
[ERROR] [...]src/main/java/B.java:[1,1] cannot find symbol
  symbol:   static MISSING
  location: class
[ERROR] [...]src/main/java/a/A.java:[9,10] cannot find symbol
  symbol:   method builder()
  location: class a.A
```
In a bigger project, there are hundreds of errors, mostly for missing builders and onConstructor_, and that many errors hides the original root problem.

**Comment by rspilker** [comment]
Yes, this is a known bug, and not something we can fix.

The problem is that javac tries to resolve static imports during parsing, so before annotation processors get the chance to run. And if an error occurs during parsing the annotation processors are not run at all.

Please register a bug at Oracle/OpenJDK.

**Comment by rspilker** [comment]
This also means that we cannot give a better error message.
