### ISSUE TITLE
Using Entity.id only on equals() lead to unexpected behavior when id = null

### ISSUE THREAD

**Issue by soberich** [rzwitserloot/lombok#1753]
This is a clone of https://github.com/jhipster/generator-jhipster/issues/2543
with relevant adjustments in code listing.

### Scenario:
when you have 2 entities with a OneToMany relationship and want to use the parent list to maintain the relationship using CascadeType.ALL (or persist, or update)

### Create the Father of the relationship
  Create 2 new childs of the same type and add them to the parent list.
  using `CascadeType.PERSIST` on the relationship call `repository.save()`, where repository is Spting Data Jpa repository `JpaRepository<Entity, Long>`
```java
        @Transactional
	public <S extends T> S save(S entity) {
		if (entityInformation.isNew(entity)) {
			em.persist(entity);
			return entity;
		} else {
			return em.merge(entity);
		}
	}
```
### Expected result
2 childs added to the database

### Actual result:
only the second child is added, as equals using id returned true when both were null.

### Fix
```java
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Entity)) return false;
        final Entity other = (Entity) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null || other$id == null ) {
            return false;
        }
        return true;
    }
```
Note the               ` if (this$id == null || other$id == null ) return false;`
instead smth like  `if (this$id == null && other$id != null) return false` which is now produced

This a kind of makes hard to use Lombok with hibernate in some cases

Also same advised by Vlad
https://vladmihalcea.com/the-best-way-to-implement-equals-hashcode-and-tostring-with-jpa-and-hibernate/

**Comment by Maaartinus** [comment]
I'm afraid, your `equals` is completely broken as it compares two entities with different non-null `id`s as equal. In the following I'm assuming, you've mean `return this$id == other$id;` instead of `return true;`.

> Note the `if (this$id == null || other$id == null ) return false;`
instead smth like `if (this$id == null && other$id != null) return false` which is now produced

What currently gets produced is the equivalent of `Objects.equal(this$id, other$id)`, i.e., just null-safe equals. That's surely correct, albeit problematic with JPA. This line

> `if (this$id == null || other$id == null ) return false;`

solves the problem, but without also following what Vlad wrote about `hashCode`, it can lead to other problems, when the entity gets assigned an `id`. So the only good solution for JPA is your above `equals` and a constant `hashCode`... you're testing a single field... you need no Lombok for this, right?

What I mean:
- There's no perfect solution for JPA. (*)
- JPA changes the `id` and using a mutable field for EqHC is broken by design.
- Using business fields for EqHC is even more broken.
- **Your preferred solution needs no Lombok.**

FWIW, I'm using manually written EqHC which throws when called with `id` being `null`.
- This feels rather wrong, but it's fail-fast.
- Entities whose identity may change shouldn't be used as keys and this way I ensure it.
- It's quite possible that this may be problematic with bigger projects, for me it works well.

---

(*) Except maybe assigning a unique id already in the constructor.
