### ISSUE TITLE
Wrong Getters & Setters generated 

### ISSUE THREAD

**Issue by ihappyk** [rzwitserloot/lombok#1779]
i have a class with fields like below
`@Getter
@rzwitserloot 
class Sample{

private boolean isFormula;
private string formula;

}`

This is generating the below code for setters

public isFormula(boolean formula){
isFormula = formula;
}

**Comment by janrieke** [comment]
Your example code is wrong. I'm assume now that you have both `@Getter` and `@Setter` on the class. I just check that code with lombok 1.18.0 and it works as expected. So there is definitely no setter method like yours generated. The only "problem" is that because of the "is" in `isFormula`, the setters for both fields would have the same name and signature, and therefore lombok only generates the first one (for `isFormula`). This is not a bug. You have to change the names, or use `lombok.getter.noIsPrefix = true` (which also affects the generation of setters).
