### ISSUE TITLE
how to create static block by jctree?

### ISSUE THREAD

**Issue by scyiqie** [rzwitserloot/lombok#1784]
now i need to create static block ex:

public class Test {
    static {
        try {
            Class s = Class.forName("s");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
}

**Comment by janrieke** [comment]
Are you trying to extend lombok? Then this is not the best place to ask, because this is neither a bug in or a feature request for lombok. Please use [the lombok forum](https://groups.google.com/forum/#!forum/project-lombok) or [ask at stackoverflow](https://stackoverflow.com/help/how-to-ask) instead.

PS: You could simply create a test case with such a static block, set a breakpoint and inspect what javac made of it. Then you'll know what to generate.
