### ISSUE TITLE
Code coverage on @NonNull

### ISSUE THREAD

**Issue by iggymoran** [rzwitserloot/lombok#1786]
Using a config flag in order to maintain any sort of backward compatibility that might be required, is it possible to change the code that gets generated for the `@NonNull` annotation from:

```java
...
if (person == null) {
    throw new NullPointerException("person is marked @NonNull but is null");
}
...
```

to:

```java
$$$nonNull$$$(person, "person");
```

where `$$$nonNull$$$` is a static method that looks something in the order of:

```java
@lombok.Generated
private static void $$$nonNull$$$(Object object, String parameterName) {
    if (object == null) {
        throw new NullPointerException(parameterName + 
            " is marked as @NonNull but is null");
    }
}
```

This would:
- reduce the amount of generated code (even if it's generated, we can still apply the DRY principle!)
- not mark the null check lines as uncovered in coverage tools that respect the `@lombok.Generated` annotation

**Comment by rzwitserloot** [comment]
No; lombok is a compile-time only dependency, so there's no place we can stick this $$$nonNull$$$ method that's still in existence at runtime. We'd have to generate it.

Applying DRY to code generation is a silly argument. As with all programming maxims and rules of thumb, you can apply it badly. Try to think of what the maxim is actually trying to prevent and then use that insight. For example, DRY is primarily about saving yourself from having to fix the same bug, or apply the same change request, in multiple places (or worse, forgetting about a few places and creating an inconsistent experience, and/or bugs). None of this applies to code generation.

The coverage tools thing is quite a relevant remark but I don't have a real solution to it; we can generate a private method to do it in _each_ class that has `@NonNull` annotations in it, but those aren't entirely invisible (they show up in autocomplete dialogs and the like), and that makes the cure worse than the disease.

opinion/rant follows:

A code coverage tool which marks `if (x == null) throw new NullPointerException();` as a problem because the line isn't covered, is indicative of why code coverage is a silly thing to chase. Don't use code coverage tools in this way! It makes you _remove_ defensive code, and/or screw up your APIs to make it possible to create inconsistent state just so you can at least test that your code does something deterministic and testable when you create inconsistent situations. In other words, code coverage tools deployed in the mode you seem to be deploying it, makes your code worse: Your APIs become worse, and your code becomes more brittle. It's lose/lose.

Another issue is the value of coverage: Unless you get a straight up 100%, the percentage value is useless. Each line of code has a 'relevancy score', indicating how important that line of code is. Some lines score thousands of 'relevancy' points, whereas others score a straight up 0, whilst most score a 1. Thus, 95% code coverage measured where each non-blank, non-comment line counts as '1 relevancy point', says absolutely nothing of import whatsoever about the quality of your tests. If the lines with a few thousands 'relevancy points' are part of the 5% uncovered, your tests are apparently just testing the simple stuff and the boilerplate, and not the real meat and potatoes, and are thus a waste of everybody's time. But that 90% code coverage number is giving everyone a false sense of achievement.

Said even more simply: Dump your code coverage tools because they are bad, they make you write bad code, and they mislead you about the quality of your code.

There is one good reason to use a code coverage tool: "Line for line": Looking at some line of code, run a bunch of tests and/or a real run whilst you manually press some buttons, and then ask a code coverage tool which test or tests covered the exact line you're looking at. That's a fine tool and a nice aid for figuring out complicated issues. Note that lombok's nullcheck being impossible to trigger is no problem whatsoever when code coverage tools are deployed in this fashion.

But that's it; the moment anybody starts mentioning the word 'percent' or 'full code coverage', my disdain for said code shop grows.

end rant.

**Comment by randakar** [comment]
I like this rant a lot.

It's accurate. Percentage coverage is a piss poot metric. Unit tests that
only cover the happy path, ditto. You want to cover the corner cases and
those won't be covered if you only test the easy stuff.

I disagree that having full coverage is necessarily a bad sign though.
Given that you want some kind yard stick  for "good enough" that is not
entirely subjective, it may be better than nothing or some meaningless
percentage of partial coverage.

I don't think unit tests should ever be the whole story or some kind of
holy grail though. Higher level tests tend to be more reliable indicators
of "stuff being broken" than unit tests. Those still have coverage, of
course, but code that can not be reached from there probably should not be
covered..

Op wo 25 jul. 2018 23:50 schreef Reinier Zwitserloot <
notifications@github.com>:

**Comment by iggymoran** [comment]
> No; lombok is a compile-time only dependency, so there's no place we can stick this $$$nonNull$$$ method that's still in existence at runtime. We'd have to generate it.

Exactly my point. Generate it on every class that has an `@NonNull` annotation.

> None of this applies to code generation

I largely agree with this, however one place where this does help is in class file size, and therefore jar size. This is pretty minor though.

> but those aren't entirely invisible (they show up in autocomplete dialogs and the like)

Fair enough point. I hadn't considered that. Having said that, IDEs like IntelliJ (with the JetBrains `@NotNull` annotation) generate code that is very similar to the one I proposed when you build through the IDE (which is one thing I don't like about it, since you don't get the same build from your machine or from running gradle/maven on your CI box).

I imagine that the Lombok plugin would be able to take care of not showing the method (but I've never written an IDE plugin, so it might not be possible). Also, I think that this only applies to _this_ class, as the method should be private.

-----

As for your opinion/rant - I pretty much agree with everything! Code coverage is a rather meaningless number which can be easily manipulated. 

> Said even more simply: Dump your code coverage tools because they are bad, they make you write bad code, and they mislead you about the quality of your code.

This one, not so much: Running a code coverage tool, **and analysing its results** can lead you to find meaningful things that you're not testing (perhaps for a good reason, or perhaps by simple forgetfulness) such as branches or error conditions that might be part of the _meat and potatoes_, or at least the _gravy_ :wink:.

I think Lombok is a great tool, and I think if we can make it play nicer with some other concerns, that are important to _some_ people, it can become an ever better tool.

Thanks for taking the time to thoughtfully respond to this issue.
