### ISSUE TITLE
javac: An unknown compilation problem occurred when using transient field

### ISSUE THREAD

**Issue by robertotru** [rzwitserloot/lombok#1815]
Hello folks,

This issue is to report an investigation I've conducted on a private project. I'm experimenting with **Java 10** (issue tested with _JDK9 as well_) and **Lombok 1.18.2** using latest IntelliJ IDEA (version 2018.2).
I have a maven project with the _maven-compiler-plugin_ version 3.8.0. I made some changes into my project and tried to compile. Both IntelliJ and command line compilation issued by the `mvn clean install` command ended up with the following mysterious message:

```bash
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] An unknown compilation problem occurred
[INFO] 1 error

```

I spended some time trying to understand which was the root cause. At the end I discovered that was Lombok (not sure it is a bug or a bad use of the library).

I've added the following line in my project
```java
    @Getter(value = AccessLevel.PRIVATE, lazy = true)
    private final transient Graph graph = createGraph();
```
and it seems that `transient` caused the issue. 

The annoying part is that even running Maven with `-X` option provided any useful hint. I had to Delombok the project and compile again to understand that the problem was related to a change made with Lombok.

I hope it helps.

Best
Roberto.

**Comment by rzwitserloot** [comment]
Lombok generates an error, using the proper Messager interface from the annotation processor infrastructure, to report that lombok does not support 'lazy' on transient fields.

The bug lies with maven; they are swallowing these errors are saying they are 'unknown'. Please file a bug with maven.

Simple test case to reproduce so you can tell the maven crew:

Test.java:

    public class Test {
        @lombok.Getter(lazy = true)
        private final transient int x = 5;
    }

compile with java: `javac -cp lombok.jar Test.java` and you'll get the error: "error: 'lazy' requires the field to be private and final.".

**Comment by robertotru** [comment]
Ok. Then maybe the Intellij IDEA plugin doesn't report that info.
