### ISSUE TITLE
Suggestion: Type Inference.

### ISSUE THREAD

**Issue by m-kuklinski** [rzwitserloot/lombok#1840]
I have a suggestion for a feature. 

I was trying to implement something that would be simple using C++ templates, but is effectively impossible with generics, as generic wildcards cannot be used as full types.

I tried to get around this using the (deprecated) @Delegate, both in a method-local class and in an anonymous class, hoping that I could expand the interfaces of `T`  to the new class in order to support rudimentary metaprogramming and type inference. This did not work, as @Delegate cannot used in methods with arguments (presumably to prevent the user from passing Arg.class to the annotations type list).

If something like this could be supported, it would make Java far more powerful and easier to use, and would gain some of the compile-time dynamicism that C++ has had since CFront.

Effectively, I would like some way to expand a generic wildcard into a meaningful type.

**Comment by rzwitserloot** [comment]
I have no idea what this would precisely look like, but I sounds like something that just doesn't mesh with what generics are.

**Comment by ameisen** [comment]
Sorry for the late response (and at home, so using personal account).

@rzwitserloot 
It _doesn't_ mesh with what Java generics are, which is why I'm wondering if they could be implemented as a post-compilation AST step (similar to Lombok).

Scala has a somewhat better level of functionality with generics, not quite on par with C++ but closer. I suspect it isn't practical to implement in Java itself using annotations, just wasn't sure and wanted to strike up a discussion about it.

@victorwss - Sorry. It is difficult to make posts on my phone (as I was). I'd use `@lombok.experimental.Delegate`, but as it is deprecated and marked to be removed in the future, I am concerned that it will cause a maintenance issue - it will lock us into the last version of lombok that supports it.
