### ISSUE TITLE
Add onConstructor to @Value

### ISSUE THREAD

**Issue by leonard84** [rzwitserloot/lombok#1842]
`@Value` is missing `onConstructor` to decorate the generated constructor, e.g., with `@JsonCreator`.

**Comment by rspilker** [comment]
Neither does `@Data`. The `@XxxArgsConstructor` annotations do have this feature.

So you would need to use:
```java
@Value
@RequiredArgsConstructor(onConstructor_={@JsonCreator})
public class Foo {
}
```

Since the use of the `onConstructor` and friends parameters are useful, we keep them, but since they are error-prone to maintain, and we are not sure if we can make them work in future java versions, we don't want to add more places to support them.

We asked Oracle to add the possibility to refer to any annotation to the language, but so far, that has been denied.
