### ISSUE TITLE
Allow usage of @Builder.Default and @Singular at the same time

### ISSUE THREAD

**Issue by KangoV** [rzwitserloot/lombok#1865]
Basically, I'd like to do ...
```
@Builder.Default 
@Singular 
private Set<X> labels = new HashSet<>();
```
... which will create a `label(X x)` method in the builder, but NOT the `labels(Set<X> set)` method.

Is this possible?

**Comment by janrieke** [comment]
Could you explain what your use case is? Do you want to define which the type of collection implementation to be used? Or do you want to define the initial elements for the collection?

**Comment by fo0** [comment]
I just wanted to open the same issue. My problem is if I creating a class and using the builder, then sometimes I dont add something directly via the builder/singular and it crashes because the collection is null.

Class
```Java
@Data
public class MyClass {
@Singular 
private Set<String> labels = new HashSet<>();
}
```

Here is an example:
```
MyClass sample = MyClass.builder().build();

// doing some stuff with sample

sample.addLabs("abc"); // here it crashes because its not initialized
```

Maybe Im doing something wrong and there is a workaround to solve the problem? Please help me :-)
It could be nice if you can add something to @singular that it initializes the collection or not

```
@Singular(init="true")
```

**Comment by rzwitserloot** [comment]
lombok already inits your stuff. These 2 requests are unrelated; the first one wants the ability to disable the generation of the plural form method which makes absolutely no sense: the plural file is equivalent to repeatedly calling the single form; in particular, it does NOT just blindly do 'this.x = x' for the collection, it actually copies everything over. I see no use case for removing the plural form method and therefore that feature request is denied.

The second feature request wants to initialize the set. Lombok _already_ does that; the only way you end up with a null field is if you call your own constructor and skip the builder entirely. The solution is to not do that or initialize the list in your own constructor. Again, not something `@Singular(init="true")` should do (very misleading).

I think you both misunderstand how `@Singular` works. Run delombok on some code with it and see what lombok does, I think that should help clarify things.

**Comment by fo0** [comment]
you see no use case? I just show you one example.
If there is no problem with it, how would you recomment us to solve the problem with the example above?

**Comment by Maaartinus** [comment]
@fo0 Your example does not compile. It has at least two errors, why don't you just copy real code?

Moreover, lombok (at least in the most recent version) produces a warning explaining where you're wrong.

What you wrote about what happens isn't true either; I've just tried. It is initialized and throws an `UnsupportedOperationException` because you're trying to modify a unmodifiable collection.

The main purpose of builder is to create an immutable object, which is why the collection is unmodifiable. `@Builder` and `@Data` together don't make sense.

**Comment by fo0** [comment]
I fixed my sample. It wasn't created to compile correctly, it should just show one possible example which explains this use case. If you don't think that this makes sense, then I'm done here :-) and you can close this issue. But that's too bad because it's IMO a missing feature of @Singular which could catch some problems which  described in this issue by me and @KangoV

**Comment by Maaartinus** [comment]
@fo0 I can't close this issue, as I'm not a project team member. I'm just trying to help.

Now it's better, but
- it does NOT crash "because its not initialized"
- it does throw an `UnsupportedOperationException` because of immutability (an unmodifiable collection used)
- this immutability is intentional
- there's no solution for the problem *"I used a builder to get an immutable thing and want to mutate it"*

If you use `@Builder` for mutable things, you're probably doing it wrong. Just use `@Data` and add a method like `public void addLabel(String label) { labels.add(label); }` and you're done. Consider using `@Accessors(fluent=true, chain=true)` so that you can write stuff like `new MyClass().a("a").b("b")....z("z")`, i.e., use a builder-like syntax without any builder.

**Comment by fo0** [comment]
this doesn't match with my issue and my example but I think we are done. Maybe @KangoV and me are the only one who every used the generated `addX` methods after initialization, and maybe the author didn't created this for that use case, whatever.

**Comment by blaghed** [comment]
Just ran into this limitation as well, and the "mutable" argument made me facepalm a bit. All fields are already mutable by allowing Setters, so why draw the line at collections?
Having the behaviour as immutable by default is fine, but I completely agree that adding `@Builder.Default` should allow us to specify the collection type in order to allow mutability at our leisure, exactly as @fo0 describes.
