### ISSUE TITLE
Feature Request: param check!

### ISSUE THREAD

**Issue by liudaomanbu** [rzwitserloot/lombok#1924]
I think lombok need a param check hook.
For example

```
@Value(staticConstructor = "create")
@Builder(toBuilder = true)
public class Person {

  int age;
}
```

or

```
@Data(staticConstructor = "create")
@Builder(toBuilder = true)
public class Person {

  int age;
}
```

I want to check the age should >=0 and <=150 by annotation.

I think lombok need param checks,not only @NonNull.
Do you consider supporting JSR check annotations and add a param check hook to support custom check?
I think it's a good idea.

**Comment by rzwitserloot** [comment]
The problem with checks is that this turns annotations like `@Max(150)` into a very crappy programming language. We all know java. `if (age < 0 || age >= 150) throw new IllegalArgumentException("age should be between 0 and 150");` is java-ese for such a check, not `@Max(150) @Min(0)`.

Many validation frameworks exist, and in my opinion, they all suck. So that's double-bad: Multiple ways of doing validation existing is bad because that makes it hard for lombok to cater to all current usage, and them sucking is even worse; either we release yet another way of doing it, or we release something which we don't even like.

Let's go through the issues:

* Annotation-based validation is really restrictive, and 'I'm programming java but actually java code is scary to me!' syndrome. Not acceptable.

* We could allow you to write, say, `@Validator private static void validateAge(int age) throws IllegalArgumentException` and we can then analyse the method name, figure out it's the validator for the age field, generate errors if you fatfinger the name, and do a check on the type. Unfortunately, single-field validation is STILL restrictive. Imagine this is an account for amazon and there's a separate setting for whether or not you want to authorize your auto-payment for alcohol. This then leads to the need for a validation check: (!alcohol || age >= 18) is now another constraint. This cannot be done with validator-per-field style.

* We could allow you to write, say, `@Validator private void validate() throws IllegalArgumentException` and call that immediately after construction. But now you still do have an invalid User instance, even if it is unlikely to escape. This way sounds like the best way, in that it's flexible unlike the other options, but possibly the solution is instead to make it easy for you to write the constructor with lombok still filling in the boilerplate of the args-list and the this.x=x settings. But that's tricky and has its own problems. (it's a bit surprising to see in code `@ActuallyThisIsTheAllArgsConstructor public MyType(/* lombok injects all params here ! */) { if (age < 18 && alcohol) throw new IllegalArgumentException("Ixnay on the Alcoholsay, kiddo!"); /* lombok generates a bunch of this.x = x; here! */ }`
