### ISSUE TITLE
If property is Boolean with "is" prefix, getter and setter not match with IDEA auto generated

### ISSUE THREAD

**Issue by gcgc** [rzwitserloot/lombok#1940]
`private boolean isOk`
With this property,  Lombok and IDEA both generate getter with name `isOk` and setter with name `setOk` 

`private Boolean isOk`
With this property,  IDEA generate `getOk` and `setOk`,  while Lombok generate `getIsOk` and `setIsOk`

And I understand that it's not recommend using boolean property with "is" prefix. Just find this mismatch when testing.

**Comment by rspilker** [comment]
`Boolean` != `boolean`.

Lombok gives special treatment to `boolean`, following the beanspec.

In our experience, it is not okay to extend special treatment to `Boolean` variables as well.

We cannot introduce this now, it would break other people's code.

We will not introduce a configuration key because that is extra maintenance burden for us, for a scenario that shouldn't exist in the first place.
