### ISSUE TITLE
@MethodNameConstants

### ISSUE THREAD

**Issue by manuel-hegner** [rzwitserloot/lombok#1944]
It would be very useful to have a `@MethodNameConstants` annotation that works the same way as `@FieldNameConstants` but with the methods. It would be even more useful if there was also a version that generates [Field](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/reflect/Field.html) and [Method](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/reflect/Method.html) type constants instead of only the name.

An example where these constants are useful are Javax webservers where you often build URIs with the [UriBuilder](https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/UriBuilder.html).

**Comment by rzwitserloot** [comment]
Gracias for naming a useful use-case. nevertheless, the complication of parameter lists being a rather intrinsic part of the definition of a method in java-land makes this one a bit more hairy than we'd like, and making j.l.r.Method/Field values is also a rather complicated affair: Only for public members? If making them for private members, should we automatically call .setAccessible(true) on them for you? They aren't actually immutable; accessibility is a mutating value, so should they be method calls instead of fields? But it's expensive to do a reflection lookup and the accessibility nature of them is usually irrelevant so in practice...

you see where this is going: Documentation as long as my leg and once we release it, endless misunderstanding and change requests because everyone has slightly different needs.

So, j.l.r.F/M literals: Never gonna happen. `@MethodNameConstants`: I don't really see that either :(

**Comment by bertvanbrakel** [comment]
In answer to which methods?
1. Just do it for methods with no args.
2. all methods regardless of params (not lombok's problem to deal with params then)
3. make it configurable

approach 1: various flags directly on the annotation
 
@MethodNameConstants(getters=true, setters=true, allArgMethods=true)

approach 2: - provide a class with a static method which is called to determine if it's included (if possible in lombok)

@MethodNameConstants(strategy=MethodNameStrategies.ALL)

approach 3: - provide includers. If any match it's included

@MethodNameConstants(include={ MethodNameInclude.GETTER, MethodNameInclude.SETTER, MethodNameInclude.MULTI_PARAM}  )

the last approach allows changing/adding behaviour down the line without breaking older implementations


The code using this will need to handle the number of param args and conversion. Lombok just provides the removal of the magic strings

One of our current codebases uses a vendored product that references extension-points/hooks via method name strings. Be really nice if we could get a compiler error if they are out of whack. It also makes creating links between code easier (what does this magic string point to?) vs writing our own constants

**Comment by jackytank** [comment]
hi are there any update regarding potential @MethodNameConstants? Because I'm currently writing Unit Test for private method and indeed it would be helpful to have a @MethodNameConstants similar to @FieldNameConstants

```java
  @MethodSource("calculateR12DataProvider")
  void calculateR12Test(
      final PowertransformerTransformerendCalcEntity calc,
      final double sbase12,
      final double expected) {
    try {
      // Prepare
      final Method method = PsseTransformer2WindingProcessor.class.getDeclaredMethod("calculateR12",
          PowertransformerTransformerendCalcEntity.class,
          double.class);
      method.setAccessible(true);

      final double result = (double) method.invoke(super.psseTransformer2WindingProcessor, calc, sbase12);

      assertThat(result, is(expected));
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }
```

in this case __.getDeclaredMethod("calculateR12"__ is just a String so if I change method signature then I must consciously change in UT class too

**Comment by dejj** [comment]
My team uses `@FieldNameConstants` and fake `Void` fields as workaround. It lets us code-surf into reasonably-close distance to the method definition. We use a reflective unit test to ensure that field and method names match.

```java
@FieldNameConstants(innerTypeName = "Methods")
@Mapper( ... )
public abstract class MapstructMapper {

  @Mappings({
    @Mapping(target = Dto.Fields.title, source = ".", qualifiedByName = Methods.composeTitle),
  })
  public abstract Dto mapEntityToDto(Entity entity);

  Void composeTitle;
  @Named(Methods.composeTitle)
  static String composeTitle(Entity entity) { ... }
}
```

Previously we would define the method names as constants, which created the kind boilerplate Lombok seeks to do away with:

```java
@UtilityClass
public static class Methods {
  public static final String composeTitle = "composeTitle";
}
```
It's the best I can do, short of forking Lombok and implementing a baseline `@MethodNameConstants` sans overloads.
