### ISSUE TITLE
ant intellij fails with IllegalStateException

### ISSUE THREAD

**Issue by lestephane** [rzwitserloot/lombok#1956]
when doing:

```bash
$ git clone ...lombok.git && cd lombok
$ ant intellij
```
It fails with:

```text
BUILD FAILED
/home/lestephane/GitRepos/lombok/build.xml:386: java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.eclipse.platform#org.eclipse.core.filesystem;[1.3.0,2.0.0)
	at org.apache.ivy.core.resolve.IvyNode.getArtifacts(IvyNode.java:811)
	at com.zwitserloot.ivyplusplus.intellij.BuildIntellijProject.generateLibraryXml(Unknown Source)
	at com.zwitserloot.ivyplusplus.intellij.BuildIntellijProject.doExecute(Unknown Source)
	at org.apache.ivy.ant.IvyTask.execute(IvyTask.java:271)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
``` 

I have no clue what to do.

Full output of the command: [trace.txt](https://github.com/rzwitserloot/lombok/files/2610119/trace.txt)

**Comment by trks1970** [comment]
Same for me.

**Comment by mshassium** [comment]
same problem.
[logs.txt](https://github.com/rzwitserloot/lombok/files/2773161/logs.txt)

**Comment by sjacek** [comment]
same problem
[logs.txt](https://github.com/rzwitserloot/lombok/files/2825721/logs.txt)

**Comment by IgnatBeresnev** [comment]
Same here... I can only imagine how many people have been discouraged and didn't contribute just because they couldnt set up the environment properly...

**Comment by sjacek** [comment]
Yep... I wanted to contribute new annotation LiferayLog, but for now it's impossible for me... :-(

**Comment by cberes** [comment]
Seems to be a problem with a transitive dependency of org.eclipse.jdt.compiler.apt https://github.com/rzwitserloot/lombok/blob/master/buildScripts/ivy.xml#L48

I tried using the latest version of vanilla ivy, but I got the same error message.

Then I tried removing the dependency, and `ant intellij` succeeded. Not sure if you'll be able to build the project with Intellij, but it's a workaround to get started.

**Comment by YuShanMuGong** [comment]
> Seems to be a problem with a transitive dependency of org.eclipse.jdt.compiler.apt https://github.com/rzwitserloot/lombok/blob/master/buildScripts/ivy.xml#L48
> 
> I tried using the latest version of vanilla ivy, but I got the same error message.
> 
> Then I tried removing the dependency, and `ant intellij` succeeded. Not sure if you'll be able to build the project with Intellij, but it's a workaround to get started.

yes!! I remove this line ，then get success!

**Comment by pimotte** [comment]
I've done a little bit of research to try and find out the underlying issue here.
As mentioned, the IvyNode `org.eclipse.platform#org.eclipse.core.filesystem;[1.3.0,2.0.0)` causes the problem. 

Further up in the build log for me there is the following line:
```
[ivy:resolve] 	org.eclipse.platform#org.eclipse.core.filesystem;[1.3.0,2.0.0) by [org.eclipse.platform#org.eclipse.core.filesystem;1.7.500] in [ecj9, contrib]
```

The call in ivyplusplus that triggers the error is [this one](https://github.com/rzwitserloot/ivyplusplus/blob/master/src/com/zwitserloot/ivyplusplus/intellij/BuildIntellijProject.java#L143)

The error triggers because the `md` (ModuleDescriptor) variable is null. 

I've tried rebuilding ivyplusplus with ivy-2.5.0, but that did not resolve the issue.

**Comment by furstenheim** [comment]
Removing the last part and leaving:

`<dependency org="org.eclipse.jdt" name="org.eclipse.jdt.compiler.apt" rev="1.3.300" conf="ecj9->default;" />`

Also seems to work

**Comment by rzwitserloot** [comment]
I've fixed the issue in IvyPlusPlus and updated the lombok build script to require the updated version.

Before the various folks who are waiting for this go forth and make fun new features, **please contact us first** – we have to maintain your contribution, we are the guardians of the lombok learning curve, as well as the standards that it has in terms of quality of the feature as well as whether we 'like' what it inherently recommends about how you write java code. Failure to contact us might result in us being forced to deny your pull request and then we all feel bad.

Our build script used to just error out if you ran `ant intellij`, saying explicitly that we don't support this due to lack of resources on our side to maintain it. I'm a bit confounded; did everybody in this thread who found solutions just disable that without mentioning it?

At any rate, now that `ant intellij` does something (no idea if it does the right thing, as a non-intellij user it'd be a big task for me to attempt to figure out if it does the right thing in the first place!), I've removed the `<fail>`, but replaced it instead with a warning that you have to enter through first:

>  ** WARNING ** The core lombok contributors all use eclipse to develop lombok. We have some ability on letting you work on lombok via intellij, but whether the generated project can be used in a modern intellij is currently unknown. Please do continue, but be aware that trying to work on lombok from intellij may run into problems. If you want to adopt 'work on lombok via intellij' as a task, we're open to it!

We still need this, in other words!
