### ISSUE TITLE
Lombok put annotation on builder method parameter instead method itself

### ISSUE THREAD

**Issue by AngryGami** [rzwitserloot/lombok#1961]
Lombok version is 1.18.4

My Test.java file is this:
```
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;

@Builder
public class Test {
    @JsonProperty("kebab-case-prop")
    public final String kebabCaseProp;
}
```
lombok.config file is like this:
```
lombok.copyableAnnotations+=com.fasterxml.jackson.annotation.JsonProperty
```
I.e. I want @JsonProperty annotation copied to builder method so jackson can actually use builder properly.
When I do "delombok" like this: `java -jar lombok-1.18.4.jar delombok -p Test.java > d_Test.java`
resulting file contains following:
```
...
        public TestBuilder kebabCaseProp(@JsonProperty("kebab-case-prop") final String kebabCaseProp) {
            this.kebabCaseProp = kebabCaseProp;
            return this;
        }
...
```
Note that @JsonProperty is attached to parameter of the method, not to a method itself, which confuses jackson and it won't do proper deserialization. If I manually move annotation to method, everything works.

Is this some sort of a bug or this is intended behavior?

**Comment by Maaartinus** [comment]
> I'm not a lombok maintainer, but to me it seems that adding more config options will push the complexity of this feature too much towards incomprehensibility.

@janrieke I agree that it's (mostly) a Jackson issue, but otherwise disagree. Now, we have `copyableAnnotations`, which sounds good, but then the questions comes what it exactly means. Lombok's choice makes sense, but it's not obvious. And, as we can see, it's not always what's needed.

Copying annotations to the builder opens even more choices. While I can't imagine configuring all possible target places individually, I'm afraid that it's the best solution since otherwise, there'll be always someone missing an option. Let's hope, I'm wrong.

**Comment by janrieke** [comment]
That's why you have to explicitly switch on copying for your annotation, because lombok cannot know if the annotation is also for `ElementType.PARAMETER`. However, for annotations that are for `ElementType.FIELD`, it is more likely they are also for `ElementType.PARAMETER` than `ElementType.METHOD`.

But of course that's not safe, it's just more likely to be valid. If we want to be able to support all cases, lombok would need separate config options `annotationsCopyableToParameter` and `annotationsCopyableToMethod`. But that's what I meant with increased complexity.

**Comment by AngryGami** [comment]
Well, yes... covering all possibilities might be unfeasible. Reasonable defaults is also good, but I believe that for cases like this there must be some sort of escape hatch. Global configuration is way too general to handle this. Maybe additional annotation(s) that control where other annotations should be copied would be a better approach (at least more granular). 
My main issue with current behavior is that I have to repeat JsonProperty annotation at both field and builder method/field level which is boilerplate and error prone approach.

**Comment by AngryGami** [comment]
```
    @Target({ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER})
    @Retention(RetentionPolicy.RUNTIME)
    @Repeatable(CopyToBuilderAsRepeat.class)
    public @interface CopyToBuilderAs {
        Class<? extends Annotation> value();
        ElementType[] copyTo();
    }

    @Target({ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER})
    @Retention(RetentionPolicy.RUNTIME)
    public @interface CopyToBuilderAsRepeat {
        CopyToBuilderAs[] value();
    }

    @Builder
    public class Test {
        @CopyToBuilderAs(value = JsonProperty.class,copyTo = ElementType.METHOD)
        @JsonProperty("kebab-case-prop")
        public final String kebabCaseProp;
    }    
```

**Comment by Maaartinus** [comment]
@AngryGami 

> Global configuration is way too general to handle this.

Are you sure? My idea would be to allow to configure exactly where an annotation should go, but only globally. This makes it much more complicated than the current state ("copy to where it makes sense most of the time"), but still very simple when compared to your proposal.

It's also much less verbose, as you don't need to repeat the information for every field. Are there case when you want e.g., `@JsonProperty` to be handled differently than in your last example?

**Comment by AngryGami** [comment]
I don't have any usecases where JsonProperty should go not to a method but I assume someone might have. My proposal is not a replacement for global configuration, but merely a escape hatch for situations when someone want to override behavior that in all other cases is fine. Situation with NotNull annotation above is an example where you might want that. Verbosity could be mitigated by making @CopyToBuildAs annotation attachable at class level and therefore work for all fields in the class.
