### ISSUE TITLE
The annotation about log in fact is private, would you make it protected?

### ISSUE THREAD

**Issue by ryuhi** [rzwitserloot/lombok#1979]
So, I can use these annotations in the parent class, and the sub class could use this variable by typing no letters.

**Comment by rspilker** [comment]
I'm not sure I understand you correctly, but let me try to interpret you request.

The lombok log annotations generate a private static field named `log`.  Your request is to change that behavior to generate a protected static field `log` instead.

If that is the case, we're going to reject that feature request, because that's not a common enough scenario, and probably leads to bugs or misleading log entries.

If you meant something else, please leave a comment.
