### ISSUE TITLE
[BUG] Warning: java: @Builder.Default requires @Builder or @SuperBuilder on the class for it to mean anything.

### ISSUE THREAD

**Issue by suraj1291993** [rzwitserloot/lombok#2027]
**Describe the bug**
`@lombok.Builder.Default` not working properly during certain times.

**To Reproduce**
Use the following code snippet.
```
import lombok.*;
@Builder(toBuilder = true, builderClassName = "Builder")
public class TestPojo {
	@lombok.Builder.Default
	private long scanTime = System.currentTimeMillis();
	public static class Builder {
	}
}
```
During simple javac compilation, the following **warning** is thrown
![image](https://user-images.githubusercontent.com/6951284/51470763-d2c7f680-1d9a-11e9-9560-3bbcbb35e98c.png)

**Expected behavior**
The expected behavior is compilation of the code snippet without any warning

**Version info (please complete the following information):**
 - Lombok version - 1.18.4
 - Platform (javac) - javac 1.8.0_192 

**Additional context**
When I imported only the needed classes rather than simply using `lombok.*` there was successful compilation.
```
import lombok.Builder;
@Builder(toBuilder = true, builderClassName = "Builder")
public class TestPojo {
	@lombok.Builder.Default
	private long scanTime = System.currentTimeMillis();
	public static class Builder {
	}
}
```
I encountered the issue when compiling using intellij idea
Thanks

**Comment by rzwitserloot** [comment]
This isn't a lombok bug, or, if it is, we're not going to fix it because it is an extreme cornercase.

The only way this happens if:

[1] You've got a star import on lombok, and

[2] You override the generated builder name to be 'Builder' _AND_ you make that class by hand, which... coincidentally, is _exactly_ the name of lombok's annotation.

So, that `@Builder` annotation? Lombok thinks it is a reference to the inner class, therefore that annotation is clearly not a reference to `lombok.Builder`, therefore, there is no `@lombok.Builder`, therefore, warning.

We could dive into the precise java rules about what the `Builder` in your snippet is referring to (is it `lombok.Builder`, or is it `TestPojo.Builder`?), but let's not.

The fix is easy enough: Either don't pick precisely `Builder` as your builderclassname, or, don't star-import.
