### ISSUE TITLE
@Builder adds an all args constructor

### ISSUE THREAD

**Issue by cl0udninja** [rzwitserloot/lombok#2045]
Using a builder pattern in my opinion is a great way for not having a constructor with a lot of input parameters. It helps code readability big time. To my surprise when the `@Builder` annotation is added on a class a constructor with all the class members is created. Adding `@NoArgsConstructor` will break `@Builder`, too. 

Maybe something like this would be a better approach:

```java
@Builder
public class Foo {
  String a;
  String b;
}
```

would yield something like that:

```java
public class Foo {

  String a;
  String b;

  public static FooBuilder builder() {...}

  private Foo(FooBuilder fb) {
    this.a = fb.a;
    this.b = fb.b;
  }

  public class FooBuilder { 
  ...
  
  public Foo build() {
    return new Foo(this);
  }

}
```

**Comment by Maaartinus** [comment]
> To my surprise when the `@Builder` annotation is added on a class a constructor with all the class members is created.

That's how it works. It's actually a builder for the argument list of the `@AllArgsConstructor`. The ctor gets generated, but is AFAIK private (and you can change it by adding the annotation with an `access` argument).

There's also the `@SuperBuilder`, which IIRC works the way you described.

> Adding `@NoArgsConstructor` will break `@Builder`, too.

I guess so. The reason is that an explicit annotation wins over the implied `@AllArgsConstructor` (which you could add to fix it). But seriously, builder is primarily meant for immutable objects, so there's no reason for adding other ctors.

**Comment by cl0udninja** [comment]
Thank you! I'll give it a try!

**Comment by rzwitserloot** [comment]
Having the constructor go off of the builder is a weird loopy dependency concept (the main class depends on the builder, the builder depends on the main class.. ???), and makes creating an instance in any other fashion (such as automated tooling or deserialization frameworks like jackson) impossible.

The easiest answer to 'this unwieldy constructor is ugly to look at'? Well, as the doctor said when you say: "It hurts when I press here!" - stop looking at it!

It's private, and invisible (by default, at any rate).
