### ISSUE TITLE
[FEATURE] Add annotation @Dummy to generate dummy class

### ISSUE THREAD

**Issue by mayras** [rzwitserloot/lombok#2052]
It will be really useful to have dummy class generation, for example:

@Getter
public class Antenna {

     public static final Antenna DUMMY = new Antenna() <--- this instance is generated

     private Long getId();

}

Nice usage with Guava without long conditions to check null values:

MoreObjects.firstNonNull(antenna, DUMMY).getId()

**Comment by rzwitserloot** [comment]
The 'value' of this proposal is real (dummy classes are a thing), but low, because we're not saving a whole lot of boilerplate with this feature.

The problems are considerable:

1. Is there a no-args constructor? If not, should just fill in default values?

2. Is DUMMY the right name? Or EMPTY? Or SENTINEL? Or configurable?

3. What about generics?

4. Generally, if serialization is involved, the DUMMY should deserialize such that all DUMMYs are reference-equal to each other. Making this happen is non-trivial.

Doesn't make the cut I'm afraid. However, I also have some good news: Some sort of elvis/coalesce kinda thingie is a feature we're debating.
