### ISSUE TITLE
[FEATURE] More transparent jar naming when installing into IDE

### ISSUE THREAD

**Issue by Gaibhne** [rzwitserloot/lombok#2063]
**Describe the feature**
I would like to put forward the suggestion of naming the artifact `lombok-$version.jar` instead of simply `lombok.jar`. If there are reasons for distributing it with the opaque name as the download, then I would suggest to at least rename the file that is copied into the IDE directory. Every now and then, I wonder which Lombok version my IDE has installed, and looking at a file named simply `lombok.jar` is not helpful, and does not follow the typical artifact naming conventions.

My suggestion is thus to rename the artifact, at least the one in the IDE directory, to something like `lombok-1.8.16.jar` as part of the installation process. This will then allow me to see at a glance which library version my IDE is using, and in case of issues or debugging allow me to trivially change the versions by adjusting the `eclipse.ini` file or the IDEA equivalent.

**Describe the target audience**
Everyone who has multiple projects or workspaces working with multiple Lombok versions who wants to see at a glance which version their IDE is running.

**Comment by rspilker** [comment]
I understand your request, and do see the benefits.

Some things you can do already:

- I just want to point out that `java -jar lombok.jar --version` shows you the version number. And in a running eclipse you can see the version number in the Help - About Eclipse dialog.
- If you want to, after installing TOPdesk, you are free to rename the jar file and modify your `eclipse.ini` file. Or not use the installer, copy the jar to a directory of your choice and modify the ini file as approriate. 

The current setup replaces `lombok.jar` if it already exists. If we would use a jar file name based on the version, should we just remove all `lombok-xxx.jar` files? Or should we just leave them?

Since it is already possibly to do this manually, I'm closing the issue.
