### ISSUE TITLE
[BUG] Getter&Setter&Data bug

### ISSUE THREAD

**Issue by apjkern** [rzwitserloot/lombok#2072]
My English is very poor, try to describe the problem clearly.
If there is an attribute of the same name in the class, but the case is different, the generated class has a problem. The class is as follows:
<pre>
@Getter
@Setter
public class Notice{
    private String noticeTime;
    private String noticetime;
}
</pre>

case：
<pre>
Notice notice = new Notice();
notice.setNoticeTime("2019-03-03");
notice.setNoticetime("2019-03-03"); // IDEA has no error. but maven compile：No symbols found
</pre>
Notice class only:
getNoticeTime() & setNoticeTime()

No generate:
getNoticetime() & setNoticetime()

**Comment by NekoCaffeine** [comment]
Please use English, thx

**Comment by apjkern** [comment]
> Please use English, thx

ok

**Comment by Maaartinus** [comment]
Disclaimer: Not a Lombok team member answering.

> My English is very poor, try to describe the problem clearly.

You English is fine. Problem described very well.

> If there is an attribute of the same name in the class, but the case is different, the generated class has a problem.

This may be a problem of the [Lombok-Idea plugin](https://github.com/mplushnikov/lombok-intellij-plugin/issues) or of Lombok itself. It may be also by design as people are strange and strange people use strange rules and if Lombok sees *something what could be a getter*, it goes out of way. In this case, there's definitely a bug somewhere, as there's no manually written getter, so it's all Lombok's work.

*But I'd suggest you to avoid such names if possible. There may be other tools getting problem and the programmers will get problems, too. Such naming is just looking for troubles.*

**Comment by rzwitserloot** [comment]
This is intentional behaviour.

What can I say? Don't repeat the same name in your class file with different casing.

**Comment by apjkern** [comment]
> This is intentional behaviour.
> 
> What can I say? Don't repeat the same name in your class file with different casing.

I have already mentioned the problem. You will not accept it. For me, it doesn't matter. It is normal for a software to have problems. Accept everyone's opinions and let more people improve it to get better improvement. You Happy on the line
