### ISSUE TITLE
[FEATURE REQUEST] @ToString add optional attribute style

### ISSUE THREAD

**Issue by iMinusMinus** [rzwitserloot/lombok#2081]
```java
public @interface ToString {
    Style style() default Style.DEFAULT;

    public static enum Style {
        DEFAULT,SIMPLE,JSON;
    }
}
```

On one hand, we use json as data exchange format more and more.
On another hand, we implicit use toString in log, and we won't output data as json format use reflection. As reflection decrease application performance.

**Comment by janrieke** [comment]
Why should lombok perform a JSON serialization? JSON serialization is not trivial, and that's what mapper frameworks like Jackson are for. Those will do a much better job than what lombok could ever achieve.

**Comment by rspilker** [comment]
I agree with @janrieke.

Also, the `toString()` method is, as far as we are concerned, meant for debugging purposes, not for serialization. Otherwise it becomes part of your public API, and past experiences from existing Java standard libraries have shown that that is a bad idea.

Reflection, if done properly, hardly decreases application performance, that's mostly a myth from the past.

**Comment by deep011** [comment]
@rspilker 
Some times i realy want output some error log for some object with json style, because json style string can be formated more easyer.
