### ISSUE TITLE
Constants generated with @FieldNameConstants are in lower camel case

### ISSUE THREAD

**Issue by oleksandr-bilous** [rzwitserloot/lombok#2092]
**Short description**
`@FieldNameConstants` generates an inner type with string constants in a lower camel case.  Doesn't depend on `asEnum()` is true or false.

We understand that `@FieldNameConstants` is an experimental feature, but we are also widely using it within a lot of our projects. It is sad that in the last Lombok versions it was refactored in a way to use a lower camel case as an only possible solution to name the constants.

I have seen other issues that are connected with this one. (Or issues that are dedicated to the same question). And I understand why you want to keep the current solution as a default one. But it is definitely not clear why you are against to make an option to let developers choose the code style they want.

**Expected behavior**
A lot of developers are using following code styles as primary ones. And it's amiss, that new lombok updates break them.

According to [Google's java style guide](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names) :

> Constant names use CONSTANT_CASE: all uppercase letters, with each word separated from the next by a single underscore.

[Oracle's java language specification](https://docs.oracle.com/javase/specs/jls/se8/html/jls-6.html#jls-6.2) says:

>Constant names normally have no lowercase letters ...

May we expect that you will add an option to let us choose between naming styles? Maybe as an additional parameter in the annotation. It would be great to make developers choose the way they want to follow.

**Target audience**
Possibly every developer that has been using lombok's `@FieldNameConstants` feature alongside `uppercase constants` code style.

**Comment by rzwitserloot** [comment]
Isn't this kind of a ridiculous concern? Slavish adherence to a style guide seems like a bad idea to me.

However, if a significant chunk of lombok users share this to me ununderstandable concern, and it's easy for us to add, eh, well. We aim to please, I guess :)

working on it. It'll be a config key option only and not the default. Because if we make it the default, then someone is gonna name a variable, say, DVDPlayer and then complains that we turned that into constant D_V_D_Player.
