### ISSUE TITLE
[BUG] Wrong parameter names passed to another annotation processor

### ISSUE THREAD

**Issue by achaphiv** [rzwitserloot/lombok#2107]
**Describe the bug**

Related issue: https://github.com/micronaut-projects/micronaut-core/issues/1566

This class:

```java
@Introspected
@Value
public class Payload {
  private final String id;
}
```

leads to different parameter names:

```java
// id
Payload.class.getConstructors()[0].getParameters()[0].getName();

// arg0
BeanIntrospection.getIntrospection(Payload.class).getConstructorArguments()[0].getName();
```

The actual class has the correct name (`id`).

The `micronaut` team believes `lombok` is not properly passing parameter names to the other annotation processor.
Thus their generated class (`BeanIntrospection.getIntrospection(Payload.class)`) seems to see auto-generated names (`arg0`, `arg1`).

**To Reproduce**

1. `git clone https://github.com/achaphiv/micronaut-introspection-issue`
2. `./gradlew test -i` or `./mvnw test`

**Expected behavior**

`./gradlew test -i` or `./mvnw test` passes.

**Version info (please complete the following information):**
 - Lombok version: 1.18.6
 - Platform: javac 1.8.0_202 (mac) & javac 1.8.0_191 (linux)

Note that my test project *works* in `eclipse`.
It only fails via `javac` with either `maven` or `gradle`.

**Additional context**

https://github.com/achaphiv/micronaut-introspection-issue

**Comment by rspilker** [comment]
First of all, I'm trying to find out where the problem might be.

I created the following code:
```java
@lombok.Value
public class Payload {
	private final String id;
	
	public static void main(String... args) throws Exception {
		System.out.println(Payload.class.getDeclaredMethod("main", String[].class).getParameters()[0].getName());
		System.out.println(Payload.class.getConstructors()[0].getParameters()[0].getName());
	}
}
```

If I compile it using `javac -cp lombok.jar Payload.java` and run it, the output, as expected, is:
```
arg0
arg0
```

If I compile it using `javac -cp lombok.jar -parameters Payload.java` and run it, the output, as expected, is:
```
args
id
```

If I execute `javap -v Payload` on the latter, as expected I get:
```
...
  public Payload(java.lang.String);
    descriptor: (Ljava/lang/String;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: invokespecial #12                 // Method java/lang/Object."<init>":()V
         4: aload_0
         5: aload_1
         6: putfield      #13                 // Field id:Ljava/lang/String;
         9: return
      LineNumberTable:
        line 1: 0
    MethodParameters:
      Name                           Flags
      id                             final
...
```

So far, everything behaves as expected. Possibly the problem occurs when multiple annotation processors are active on the same code base in the same round.

We do have some code to collaborate with MapStruct, that might be reusable here, where collaborating annotation processors can pick up changes, possibly in a next round.

In general, developers at Oracle think that relying on the names of parameters is not necessarily a good idea, because it's not explicitly clear that renaming a parameter becomes a breaking change, since it is now part of your public API.

The suggestion is to annotate the parameters instead. Lombok will copy those parameters if you put them on a field, if you teach lombok that they're copyable annotation, by specifying that in `lombok.config`.

Since figuring out what's the problem here is a lot of time, and this is the first time we've encountered this problem, I'm closing this issue.

**Comment by rspilker** [comment]
https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.

**Comment by achaphiv** [comment]
> We do have some code to collaborate with MapStruct, that might be reusable here, where collaborating annotation processors can pick up changes, possibly in a next round.

Hmm, that makes sense.

> The suggestion is to annotate the parameters instead. Lombok will copy those parameters if you put them on a field, if you teach lombok that they're copyable annotation, by specifying that in lombok.config.

Yeah, I know. I didn't mention it because parameter annotations aren't seen in Micronaut's `BeanIntrospection` either. I figured it it was probably the same underlying issue as parameter names. 

I.E.

Adding `@Nullable`:

```java
@Introspected
@Value
public class Payload {
  @Nullable
  private final String id;
}
```

This passes:

```java
  @Test
  public void parameterAnnotationsViaReflection() {
    Parameter[] args = Payload.class.getConstructors()[0].getParameters();
    Assert.assertNotNull(args[0].getAnnotation(Nullable.class));
  }
```

This fails:

```java
  @Test
  public void parameterAnnotationsViaBeanIntrospection() {
    Argument<?>[] args = BeanIntrospection.getIntrospection(Payload.class)
      .getConstructorArguments();
    Assert.assertNotNull(args[0].getAnnotation(Nullable.class));
  }
```
