### ISSUE TITLE
[FEATURE] Add support for @Singular(init="false")

### ISSUE THREAD

**Issue by jearton** [rzwitserloot/lombok#2173]

**Comment by rzwitserloot** [comment]
We don't add features just because someone woke up one day and thought: Hey, why not. If we would, `@Data` would by now have about 89 different parameters and I think we can all agree that'd suck. So, no.

Next steps would be to elaborate on precisely what that would do and especially: Why anyone would want that.

If you mean: It should leave the collection on 'null', I'm shooting that down. That's silly code.
