### ISSUE TITLE
[BUG] UI cannot be resized - cant see options

### ISSUE THREAD

**Issue by magick93** [rzwitserloot/lombok#2175]
**Describe the bug**

I'm unable to see, and thus use, the options in the lombok installer.

**To Reproduce**
Download latest lombok.jar and attempt to run it using OpenJdk 11 and Ubuntu 19.04.

**Expected behavior**

Expect to be able to use, via seeing, the functionality of the UI

**Version info (please complete the following information):**
 - Lombok version - see screenshot below.
```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu219.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu219.04.1, mixed mode, sharing)
```

**Additional context**

![image](https://user-images.githubusercontent.com/2173213/61012319-20303280-a3d2-11e9-9669-4f5714432924.png)

**Comment by rzwitserloot** [comment]
This is a bug in JDK/linux and not something we are at this point willing to address. After pouring 5 hours into the absolute omnidisaster that is swing and HD screens, I already have too many grey hairs to spend another second on it.

Note that making the thing resizable does jack all to fix any of this in my experimentation.

I will accept PRs with the fix for this with a screencast proof that it works because I can't exactly go out and BUY a computer with the precise configuration such that this bug occurs.
