### ISSUE TITLE
[FEATURE] add spring properties files to configuration search 

### ISSUE THREAD

**Issue by sdwarwick** [rzwitserloot/lombok#2178]
global parameters for spring applications show up in files like "application.properties" and "application-local.properties"   it would be nice to have lombok support that as well, including the spring ability to publish what properties are available with a description.

**Comment by rzwitserloot** [comment]
I have absolutely no idea what any of this means. Please elaborate. Assume I have no idea what spring does (because I don't).

Do you perhaps mean that lombok should also read application.properties in addition to lombok.config? We're not going to do that, that sounds silly. Let's put lombok things in lombok config files and spring things in their config files and not mix and match like it's woodstock festival.

**Comment by rzwitserloot** [comment]
parked - close by 2019-07-25 if no feedback.

**Comment by janrieke** [comment]
I also interpret that in this way. However, this is impossible because `application.properties` only contains the runtime configuration, but Lombok is compile-time only.

**Comment by sdwarwick** [comment]
@janrieke @rzwitserloot you are correct, my bad.  I have been doing a lot of consolidation of other configurations that are currently integrated into spring,  but did not consider where Lombok stood in the compile-time  / run-time.   please drop request.

**Comment by rspilker** [comment]
Thanks for the feedback!
