### ISSUE TITLE
[FEATURE] mapping bean from and to a java Map

### ISSUE THREAD

**Issue by andang76** [rzwitserloot/lombok#2181]
I often convert simple beans to java HashMap and backwards. It's a tedious task.
I've built and used some reflection based tools, but a compile-time option like a Lombok feature could be the very best option IMHO (for performance issues, for example).

The very basic idea:
```java
@MapBuilder(class=java.util.HashMap)
public class Person {
   private String name;
   private String cell;
}
```
generate methods
```java
public Person fromMap(Map<String,Objet> map) {
   Person p = new Person();
   P.name = map.get("name"); 
   P.cell = map.get("cell"); 
  return p;
}

public Map toMap() {
   Map map = new HashMap<String,Object>();
   map.put("name",this.name);
   map.put("cell",this.cell);
  return map;
}
```
This is the very basic idea. It could have more features, like annotations for key customization, and so on.

**Comment by rspilker** [comment]
What do you plan to use the map for? Presumably for some sort of serialization.

Serialization and deserialization is a hot topic. There are already lots of projects that try to tackle this. Some use reflection (Jackson), some use code generation (MapStruct).

For simple objects, your example might work. But the moment you're allowing more complex objects, it get very complex very fast.

In Lombok, we don't have resolution, so we cannot inspect any other classes.

How can we handle the following example:

```java
class Person {
  private String name;
  private LocalDate born;
  private Address address;
  private List<Person> emergencyContacts;
}
```

1. In your example, fromMap should probably static.
2. Do we put the LocalDate in the map, or an ISO string?
3. Does Address have to have a fromMap/toMap as well? How would we distinguish between a LocalDate and Address if we don't have resolution?
4. What list implementation should we use?
5. Since the emengencyContacts are persons, how should we handle circular references?

All in all this is a very complicated subject, better left to specialized frameworks.

**Comment by andang76** [comment]
Ok, I understand, I didn't considered more complex cases. 
My use cases are 95% of simple beans,  just like the example I've submitted. 

I'm using Jackson for this, indeed. But alternatives like Lombok could be the best option, avoiding run-time reflection-based processing (potential performance issues) and having the feature trasparently, with virtually no effort needed for launching code generations. 
I've searched a little generation-based solutions but I haven't found any alternative. I'll evaluate Mapstruct, thanks.
