### ISSUE TITLE
[FEATURE] "it" syntactic sugar to stream.map(f)

### ISSUE THREAD

**Issue by pigsflew** [rzwitserloot/lombok#2182]
**Describe the feature**
Like `val` and `var`, `it` would allow you to not repeat yourself when using function references to an obvious source.

"Lomboked"
```java
val jsonBlobs = ImmutableList.of(new JsonObject())
  .stream().map(it::toJson).collect(collectors.toList());
```
Plain Java
```java
List<String> jsonBlobs = ImmutableList.of(new JsonObject())
  .stream().map(JsonObject::toJson).collect(collectors.toList());
```

**Describe the target audience**
people who use streams for object mapping a *lot* :)

**Additional context**
Nope.

**Comment by rspilker** [comment]
I understand the use case. 

To me using the word `it` sounds wrong. It refers to an object, not a class. possibly `they` would be a better fit.

Inferring the type at that location is going to be really complicated. We can make `var` and `val` work most of the time, because we ask the compiler to evaluate the initializing expression, and then calculate the type. Which is already pretty hard, and thee are some sharp corners there.

But what you're asking here is to understand the the type passed to the `of` method results in a list of that type, then the stream carries the same type and passes an object of that type to the map method.

We're rejecting this feature request.

**Comment by pigsflew** [comment]
Thanks for considering!
