### ISSUE TITLE
Support overriding `lombok.log.flagUsage` with a more specific `lombok.log.<whatever>.flagUsage`

### ISSUE THREAD

**Issue by barorion** [rzwitserloot/lombok#2187]
In my project I'm using a specific logging framework (Log4j2 in my case), and `@Log4j2` is very handy.

I want to block usages of the other logging related annotations (e.g. `@Log4j`) using Lombok's config mechanism. This can prevent cases where the wrong logging frameworks (that might also exist on the classpath due to transitive dependencies) is used due to a simple typo in the used log annotation.

Right now, my best bet is to have many entries like

```
lombok.log.log4j.flagUsage = error 
lombok.log.slf4j.flagUsage = error 
lombok.log.javaUtilLogging.flagUsage = error
... (same for all other log frameworks except log4j2) ...
```
And I'll have to remember to update this file every time Lombok great guys add support for a new logging framework.

A more friendly option (with less boilerplate config code :)) would be to support: 
```
lombok.log.flagUsage = error  # disallow all
clear lombok.log.log4j2       # allow (only) log4j2
```

I know an option to allow overriding a broader configuration options with more specific ones was discussed, e.g. in #1933. This is probably another usecase that can earn from such mechanism.

**Comment by rspilker** [comment]
I do understand the problem, and also that we might support more logging frameworks later.

But I think that precedence rules (general rules vs. specific rules) in combination with scoping rules (directory structure) are hard to understand and maintain, both for the Lombok developers and the users.

Since we only occasionally add logging frameworks, and we always publish those in the change log, and the chances that you also have those dependencies on the classpath, and the developer uses them without noticing, and the reviewer also misses it, are low, we're not going to add this.
