### ISSUE TITLE
[FEATURE] Using decimal instead of BigDecimal?

### ISSUE THREAD

**Issue by bojanv55** [rzwitserloot/lombok#2192]
Currently when we want to do money-related calculations we have to use BigDecimal - which is tedious.

Not sure if lombok can support this at all, but...

Is it possible to have instead of this

```
BigDecimal x = new BigDecimal(1);
BigDecimal y = new BigDecimal(2);
BigDecimal sumAndDiv = x.add(y).divide(y);
```

to have much simpler version:

```
decimal x = 1;
decimal y= 1;
decimal sumAndDiv = (x+y)/y;
```

**Comment by Maaartinus** [comment]
This is unfortunately [a pretty complicated and basically denied feature](https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-Operator-overloading).

Using `decimal` instead of `BigDecimal` doesn't sound right as in the end, there's no new type, so it's just a lie. It could be used as a marker for Lombok to recognize it has to do something, but see the last paragraph of the wiki.
