### ISSUE TITLE
[FEATURE] Built-in builder

### ISSUE THREAD

**Issue by amarkevich** [rzwitserloot/lombok#2199]
using new annotation like @WithBuilder generate code like 
```
public class AttributeType {
    private String name;
    // generated
    public AttributeType withName(String name) {
        setName(name);
        return this;
    }
```
Usage:
`new AttributeType().withName("name")`

Its more clear comparing to existing @Builder (avoid builder()/build() calls):
AttributeType.builder().name("name").build();

**Comment by janrieke** [comment]
I think your use case is covered by `@Acessors(fluent=true,chain=true)`. Furthermore, there is `toBuilder` and `@Wither`. I don't see a need for more.

**Comment by amarkevich** [comment]
Thanks @janrieke 
@Wither is exactly what I'm looking for. `@Accessors` is not compatible with existing `@Getter`/`@Setter`

**Comment by amarkevich** [comment]
Unfortunately `@Wither` require `@AllArgsConstructor`; initial request about simple `this withX` implementation

**Comment by Maaartinus** [comment]
@amarkevich 

> Its more clear comparing to existing @builder (avoid builder()/build() calls):

No. Actually, you first post shows a code using `setName(name)` which you compare with `AttributeType.builder().name("name").build()`. But the former modifies an existing object while the latter creates a new one.

> Unfortunately `@Wither` require `@AllArgsConstructor`

Sure, otherwise it couldn't create a new object.

---

You should really make clear whether you want a new object or not.

If all you want is using the "with" prefix for setters, I'm afraid, this won't ever get implemented as the "with" prefix is taken by the `@Wither`.
