### ISSUE TITLE
[FEATURE] Add an option to @ToString to distinguish Strings containing "null" from the null value

### ISSUE THREAD

**Issue by michaelamaura** [rzwitserloot/lombok#2247]
# Description of the issue

As lombok is just using the #toString implementation of an object's fields, this can lead to ambiguities when using String fields:

Provided we have a simple class:

```
  @Data
  class SimpleClass {
    private final String field;
  }
```

Thus `new SimpleClass(null).toString()` and `new SimpleClass("null").toString()` will yield `"SimpleClass(stringField=null)"`.

This is inconvenient, since we cannot determine whether the field is `null` or whether it is the `String` `"null"`. Additionally also empty strings will become more readable.

# Possible solution

When the field would be quoted we would have `stringField=null` and `stringField="null"` respectively. Of course quoting must only apply when the field is actually a `String` instance thus exluding the `null` value.

This is also in line with most code generators. For example IntelliJ IDEA would generate a `#toString()` method like the following (using single quotes):

```
    @Override
    public String toString() {
      return "SimpleClass{" +
          "field='" + field + '\'' +
          '}';
    }
```

Note that, however, this implementation is doing it wrong since it will also quote the `null` value thus making the quoting useless.

To support this an attribute like `boolean quoteStringValues() default false` could be added to the `@ToString` annotation:

```
  @Data
  @ToString(quoteStringValues=true)
  class SimpleClass {
    private final String field;
  }
```

# Alternative solutions

Alternatively we could have a `@ToString.Quoted` annotation that could be placed directly on the field like:

```
  @Data
  class SimpleClass {
    @ToString.Quoted
    private final String field;
  }
```

Additionally a configuration key like `lombok.toString.quoteStringValues` with values `true` or `false` might be neat to configure this on a wider scope.

# Implementation details

It could be argued whether to use single or double quotes for this. This is simply a matter of taste and will not affect the usefulness of the feature.

Note, however that it should not be an issue if the string itself contains quotes, since this would not introduce any ambiguities (using single quotes for easier readability of the code):

* `new SimpleClass("'").toString()` would yield `"SimpleClass(stringField=''')"`
* `new SimpleClass("''").toString()` would yield `"SimpleClass(stringField='''')"`

These are not "easy and nice to read", but definitely unambiguous, since it is clear that the first and last quote are part of the quoting. So I would argue that just "putting quotes around" is enough and we should not escape quote characters in-between.

# Target audience

Any developer having to deal with the occasional `null` value of fields in their data and value objects.

**Comment by michaelamaura** [comment]
Just updated `quoteStringFields` to  `quoteStringValues` to emphasize that not the type of the field, but the type of the value will trigger the quoting (so `null` will not be quoted because it is not a `String`).

**Comment by ptlanu22** [comment]
Can someone confirm if this needs to be picked up and implemented.

**Comment by rspilker** [comment]
Initially I liked the idea. And then Reinier and I started looking into this more closely.

We have some concerns regarding the feasibility, and currently don't think it is a good idea.

The first question is: should it be based on declared types, like we currently handle Arrays, or on values. Declared types would make it easier to generate the code, the latter would involve a runtime instanceof check. Or even a combination: it the declared type is String we can generate code without an instanceof, otherwise one with an instanceof.

Second question: should this be limited to String or also for StringBuffer, StringBuilder and CharSequence. It makes sense to include those know stringy types as well.

Third question: what about the result of a method annotated with `@ToString.Include`. Are they themselves responsible for adding the quotes, giving developers total freedom to render a proper representation, or should those be quoted as well.

Four. What about Strings and null values in String[] or List<String>. We're definitely not going to reimplement Arrays.toString or List.toString. And Maps that contain String keys or values.

__Given the precedent in the java standard libraries, we think that the value of quotes around String values is not that big.__

Regarding the rendering of null values: if _that_ is the problem, maybe we can fix it.

One possible solution would be to change the rendering `Table(name=null)` to `Table(name is null)`.

I wish we had thought of that when we implemented the first version of `@ToString` 10 years ago. Now I'm not sure that breaking backwards compatibility is worth the benefits. If we would change the rendering, we would probably also need a option in `lombok.config` to revert to the current behavior.
