### ISSUE TITLE
[FEATURE] @ToString json style

### ISSUE THREAD

**Issue by PlexPt** [rzwitserloot/lombok#2248]
Add json style to @ToString

**Comment by rspilker** [comment]
Serialization of objects is not our domain. There are many good libraries that help with that subject.

Serialization turns out to be much harder than: let's just put all the fields in a map by their name, the values are primitive, String or Array/List, or if it is an object, just create a new map.

**Comment by arush0311** [comment]
Can we take in an serializer like GSON/ObjectMapper and delegate the ToString functionality to that?

**Comment by PlexPt** [comment]
or apache commons



---Original---

**Comment by ehsanzarei2** [comment]
since the new tools and technologies workaround with json and using lombok becomes pervasive over time, It is better to do this.
in our case , one of teams that collaborate with our team use a log parser tool that work with json format perfectly and they are surprised why we cant write json log in our project while there are many tools that working on logs and read them as json format data.
