### ISSUE TITLE
[BUG] lombok configuration "equalsandhashcode.callsuper=call" does not work

### ISSUE THREAD

**Issue by Dreijnde** [rzwitserloot/lombok#2258]
When you add the generic setting "lombok.equalsandhashcode.callsuper=call", every equals method will always return false.

The setting is supposed to add @EqualsAndHashCode(callsuper = true) to all classes.
When you add @EqualsAndHashCode(callsuper = true) to classes that do not have a super except for Object, compiler returns the error "Error:(27, 1) java: Generating equals/hashCode with a supercall to java.lang.Object is pointless."

What I suspect is that the generic setting "lombok.equalsandhashcode.callsuper=call" circumvents this, and adds an object reference in the equals, therefore always resolving to false.

**To Reproduce**
```
@Data
public abstract class Data {
  String whatever;
}

@Data
public class SpecificData extends Data {
  String somethingElse;
}
```
in lombok.config:
```
lombok.anyConstructor.addConstructorProperties=true
lombok.equalsAndHashCode.callsuper=call
lombok.toString.callsuper=call
```
to test: 
```
SpecificData one = new SpecificData("bla");
SpecificData two = new SpecificData("bla");
one.equals(two) //expected: true, result: false
```
for version:
```
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.8</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by rspilker** [comment]
I cannot reproduce the bug.

We do have [(green) tests](https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/before/EqualsAndHashCodeConfigKeys2.java) that suggests we don't generate a call to super if:
- the class does not extend anything
- the class extends `java.lang.Object`

I've also tried a your code, after small modifications to make it compile:
```java
import lombok.*;

public class Main {
	public static void main(String... args) {
		Foo one = new Bar("bla", "boo");
		Foo two = new Bar("bla", "boo");
		System.out.println(one);
		System.out.println(two);
		System.out.println(one.equals(two));
	}
}

@Data
abstract class Foo {
  final String whatever;
}

@Data
class Bar extends Foo {
  String somethingElse;
  Bar(String foo, String bar) {
	  super(foo);
	  somethingElse = bar;
  }
}
```

The output:
```
Bar(super=Foo(whatever=bla), somethingElse=boo)
Bar(super=Foo(whatever=bla), somethingElse=boo)
true
```

**Comment by Dreijnde** [comment]
Sorry, my reconstruction was not good.

This reconstruction does show the problem I encountered:

```
class Main {
    public static void main(String... args) {

        SendMessageToOperator not1 = new SendMessageToOperator("messageId", "payload");
        SendMessageToOperator not2 = new SendMessageToOperator("messageId", "payload");
        System.out.println(not1);
        System.out.println(not2);
        System.out.println(not1.equals(not2));

    }
}

@Value
class SendMessageToOperator extends SendMessage {
    String messageId;
    String payload;
}


abstract class SendMessage extends NotificationCommand {
    public abstract String getPayload();

}

abstract class NotificationCommand {
    public abstract String getMessageId();
}
```
Results in: 
```
SendMessageToOperator(super=com.portbase.hinterland.operatorsync.email.SendMessageToOperator@b2cab380, messageId=messageId, payload=payload)
SendMessageToOperator(super=com.portbase.hinterland.operatorsync.email.SendMessageToOperator@9499d4a2, messageId=messageId, payload=payload)
false
```

**Comment by janrieke** [comment]
That's because your abstract classes inherit the `equals` from `Object`, and that only returns `true` for the same instance. And you told Lombok to call the superclass. So this is not a bug.
So either implement `equals` in at least one of the classes, or don't call super.

**Comment by Dreijnde** [comment]
```lombok.equalsAndHashCode.callsuper=call```
This config is supposed to work with abstract classes.
Currently it seems it is not working with any abstract class that extends something else. 
We would love it if it could be fixed, since the setting saves a lot of boilerplate

**Comment by Maaartinus** [comment]
@Dreijnde IIUIC, it's impossible for Lombok as it knows nothing about the superclass (as this information is unavailable when it runs). It can recognize `Object`, but that's it. It does not matter whether the superclass is abstract or not, what does matter is whether it implements (or inherits) `equals`. This is even harder to recognize so the user has to provide the information.

**Comment by renedewaele** [comment]
@Maaartinus 
I'm having the same problem as the author of this issue, and I'm not sure I agree with the conclusion of this issue.

Right now there seemingly is a check if the annotated class directly extends from `Object`. If so, the super methods are not invoked (even when `lombok.equalsAndHashCode.callsuper=call`). However, I think Lombok should instead check whether any of the superclasses (other than `Object`) implement equals/hashcode. If none of the superclasses implement these methods then the super methods should not be invoked. Using reflection this should be a relatively easy (not sure if the same holds for annotation processors).

If this is difficult to do, there is yet another way to implement this at runtime. Simply get the equals method from the superclass (using reflection) before invoking it and if `Object` is the implementing class you don't invoke it.

Right now we would very much like to set `lombok.equalsAndHashCode.callsuper` to `call` but can't really because of this issue. Is it possible to reopen this issue and work on a fix?

**Comment by janrieke** [comment]
Runtime checks via reflection are critical, because a `SecurityManager` can prevent reflection. And what do you do then? Rethrowing the exception is not an option, and falling back to either "call" or "don't call" will always result in a differing behavior compared to no security manager. That's gonna introduce bugs that are much harder to find than unintentional `equals` super calls.

**Comment by randakar** [comment]
Not to mention slow. Equals and hashcode methods get invoked a lot, you do
not want to incur the overhead that reflection introduces. It would not
surprise me if that alone doubles the runtime of these methods.

**Comment by janrieke** [comment]
Yes, but you only have to check that once and statically cache the result, as it won't change during the VM runtime.

**Comment by renedewaele** [comment]
You don’t need to. You’d need to do it once per class at most (and cache the result). 

As I mentioned in my comment: an even better place would be in the annotation processor. I only mentioned this as an alternative if that would prove difficult or impossible. 

Look, the main point is that the feature is a lot less useful right now because of this. I really like Lombok because it helps reduce boilerplate and usually works in ways that make me happy. Let’s try and be constructive and come up with solutions instead of criticisms of suggestions.

**Comment by Maaartinus** [comment]
@renedewaele 
> As I mentioned in my comment: an even better place would be in the annotation processor. I only mentioned this as an alternative if that would prove difficult or impossible.

Lombok knows close to nothing about the superclass, it's all [resolution](https://github.com/rzwitserloot/lombok/wiki/LOMBOK-CONCEPT:-Resolution). For me, the word "resolution" is the magic spell explaining that it can't be done with reasonable cost. Lombok can't see whether there's `equals` in the superclass or maybe in some of its ancestor.

As said, reflection is unreliable. The speed is improbably the problem, but the `SecurityManager` is, at least for someone. Another idea would be to check whether `x.hashCode() == System.identityHashCode()`. When the differ, then there's a custom `hashCode()` and there must be an `equals`, too. When they don't, then you don't know; there's a small probability that it happend by chance (`2**-32`, small but realistic; too bad) or due to a strange implementation. That's even worse than reflection.

> Look, the main point is that the feature is a lot less useful right now because of this.

For you, the config `lombok.equalsAndHashCode.callSuper=call` is unusable as your superclasses has no equals.... So ditch the option forever, watch the warnings and set `callSuper` manually. For 1000 classes, it may take one hour and less characters than this thread.

**Comment by rzwitserloot** [comment]
1. We could have this information at compile time without having to generate runtime reflection code, but getting it difficult to code, slow to do (it'll slow down your IDE), and hard to maintain. We're not going to add such complex stuff for such a core feature.

2. Generating reflection code to do it means the code lombok generates would be considerably worse than code you'd handroll. That is not a step we're going to take.

This issue will be solved if (when?) we make resolution easy and fast. Which is a long way off. No need to re-open this, if ever we do get that, upgrading equals/hashcode super calls is the first thing I'm going to improve.

**Comment by sankita15** [comment]
I am also facing the same problem, because of which I have to explicitly override equals and hashcode. Any fix for this issue got introduced?

**Comment by bilred** [comment]
Hello I am also facing the same problem ! i'd know if you have any fix for this issue? thx.

**Comment by sankita15** [comment]
For my case, I was using @equalsandhashcode twice at parent and grandparent level, which was not required.

the nesting was like this
GrandParent
    Parent
       Child1
       Child2

So Equals and hashcode at grandparent level was not working as the grandparent dto was not required and we removed the grandparent dto

**Comment by rzwitserloot** [comment]
When I explain why we're not adding it, comments in the vein of "I really want it" or "Please reconsider" or __utterly pointless__. You might as well ask if we can break the speed of light soon.

All future comments asking for updates will be summarily deleted, and repeat offenders will get banned.
