### ISSUE TITLE
[FEATURE] JavaDoc generation

### ISSUE THREAD

**Issue by burdoto** [rzwitserloot/lombok#2265]
Opened from #2263

**Describe the feature**
Currently, there is no option to include JavaDoc in generated methods.
This could be ovecome in two ways:

- **Method 1: String literals** Since Java 13's introduction of String literals using `"""`, JavaDocs could be included in an annotation field. Maybe the @JetBrains team is willing to support this change by introducting the `JavaDoc` value in their `Language` annotation to support correct code formatting.
- **Method 2: Annotation a JavaDoc block** Since annotation processors run pre-compilation, it is possible to have a lonely JavaDoc-block in the code, which, annotated with lombok, could be moved to the according method declaration.

**Comment by rzwitserloot** [comment]
Intentional; There is there is no need for this.

If lombok is generating code for a field (so, builder-setter, normal setter, or getter), lombok does copy over javadoc, though the javadoc tool does not run APs, so you have to go via the delombok-then-javadoc route, which is annoying but there isn't much we can do, other than provide maven plugins to make this easier, and these exist. For other stuff like constructors and the like, well, generally the idea is: Hey, if the constructor is boilerplate, there is nothing useful to add. If there's specific info to convey that the name of the class and types/names of the parameters don't already say, then say it in your class javadoc.

Lombok has no further context other than names and we do not believe in pointless repetition in javadoc, and it is difficult to give you a location to add the javadoc (there is putting it in a string literal inside an annotation param, but that's too ugly to consider. String literals are for string literals, not for java code or javadoc). This kind of javadoc:

    /**
     * returns the name.
     * @return String the name.
     */
    public String getName() {return this.name;}

is bad and you shouldn't write it. It serves no purpose and is just a violation of DRY (which is especially problematic, as it is not possible to unit test documentation).

You cannot annotate javadocs. annotation processors do not run 'pre compilation', they run during it, and in fact after the parse phase.

I don't see a feasible way to allow it. At best we can talk about generating a javadoc for, say, a generated constructor, based on combining all javadoc present on fields that are included in it.

**Comment by burdoto** [comment]
I see that there probably isn't a real need for JavaDoc generation on 'primitive', generated getters; you still can document the fields belonging to the getters.
