### ISSUE TITLE
[BUG] Incorrect generation getters/setters on primitive boolean values with names starts with is_...

### ISSUE THREAD

**Issue by mbto** [rzwitserloot/lombok#2299]
**Describe the bug**
Incorrect generation getters/setters on primitive boolean values with names starts with is_...

**To Reproduce**
compile and decompile .class files

**Version info (please complete the following information):**
 - Lombok version 1.18.10
 - Platform java 11.0.2

**Additional context**
![photo_2019-11-28_16-47-26](https://user-images.githubusercontent.com/8545291/69811340-edf76400-11fe-11ea-91e9-281ae8501572.jpg)

**Comment by dgrant** [comment]
@mbto Because you named your member variables should be called `executions` and `dev10_100` then you get would get getters/setters that start with `is`

**Comment by dgrant** [comment]
@mbto oh sorry you're right, that is messed up!

**Comment by dgrant** [comment]
So the code that is doing this is:

```
		if (isBoolean && fName.startsWith("is") && fieldName.length() > 2 && !Character.isLowerCase(fieldName.charAt(2))) {
			// The field is for example named 'isRunning'.
			return booleanPrefix + fName.substring(2);
		}
```

So if the field name is `isRunning` or `is_running` or `is3running` then the getter will be `isRunning`, `is_running` or `is3running`. If the field name is `island`, then the getter will be `isIsland`.

The behaviour is kind of documented: "For boolean fields that start with is immediately followed by a title-case letter, nothing is prefixed to generate the getter name."

But it doesn't mention what happens when the next character is `_`... So that behaviour is kind of undefined, but it just so happens that it works as `_` is "not lowercase" so it works out that is leaves the field name alone and makes the accessor `is_running`. This is not JavaBeans compliant but Lombok already is not (and was it designed to be? I don't think).

**Comment by mbto** [comment]
I using spring boot 2.1.4.RELEASE with lombok 1.18.6 (from spring-boot-dependencies http://search.maven.org/classic/remotecontent?filepath=org/springframework/boot/spring-boot-dependencies/2.1.4.RELEASE/spring-boot-dependencies-2.1.4.RELEASE.pom )

Invoking my endpoint:
http://localhost:8080/test?is_asd=true&is_qwe=true&text=hello

Test endpoint with debug - incorrect behaivor:
![изображение](https://user-images.githubusercontent.com/8545291/69895501-19369c00-1342-11ea-931d-835ac5c9f605.png)

Decompiled data transfer object:
![изображение](https://user-images.githubusercontent.com/8545291/69895527-8fd39980-1342-11ea-8d7b-10e7dba1f9a8.png)

I think its not correct behavior.

**Comment by rzwitserloot** [comment]
This is intended behaviour. Having a boolean field named `isLoaded` result in a getter named `isIsLoaded` is perhaps bean compatible, but obviously undesired. With `is_loaded`, well, mostly you're not following the java conventions, so, who knows what you want. We picked some option. I bet half wanted it to go our way, and the other half wanted it the other way. There is no way to satisfy all parties.

We're not changing this behaviour; it is intentional.

**Comment by mbto** [comment]
Here we are talking about different behavior for the **Boolean-class** and for the **boolean-primitive**.
It is correctly generated for a class, but not correctly for a primitive, so I was very surprised at this when my springboot-framework stopped setting such fields.
I hope you got what I meant.
OK, thanks.
