### ISSUE TITLE
[FEATURE] Apply @NonNull by default via configuration

### ISSUE THREAD

**Issue by vprudnikov** [rzwitserloot/lombok#2310]
Hi!

I have recently noticed that I'm automatically adding `@NonNull` annotations almost everywhere in my code. And I realized that, probably, it would be better to apply `@NonNull` annotation to ALL method parameters (not sure about fields) by default.

How I (and probably others) can benefit from this:
1. Less boilerplate, shorter lines of code.
1. The code becomes more robust without doing anything. 
1. Not thinking about the fact that I have forgotten to add `@NonNull`. I would rather expect that I had to add a sort of `@Nullable` annotation when something can be really nullable.
1. Less time spending on writing tests that check that parameters are not nullable since I have not-null everywhere by default.

Also, I think it reflects somehow what Spring guys do at the moment. They assume that everything is not null unless they mark it as `@Nullable`. One problem is that it can be currently checked by IDE only.

_I would expect that this feature can be achieved by configuration means._

**Comment by rzwitserloot** [comment]
We have considered a lomboky `@NonNullByDefault` and have decided against it.

But, I'll debate this once more with @rspilker before I fully shut this one down.

**Comment by vprudnikov** [comment]
Hi @rzwitserloot , thanks for your reply!

Is it possible for you to review the proposal?

In my opinion, this setting should be applied **globally** via `lombok.config` instead of per-class annotation.

Examples:

- Spring framework assumes non-nullability globally
- Kotlin language has non-nullability by default

So I think it should be a global setting that represents a developer's approach to writing code instead of applying it to particular places only. Then, if a developer decides that something is nullable then the corresponding annotation should be specified (e.g. `@Nullable`, `@Null`, etc.).

Thank you.

**Comment by rzwitserloot** [comment]
We've considered it, and it's a bad idea. We're not going to do this.

It's about what lombok's nonnull does. It does a great many things:

* It serves as documentation carried in the class file. Sort of; the retention policy -IS- `CLASS` so it is in there, but lombok is not designed to be a dependency that sticks around (it needs to be there when you compile and it ends there), and you can't query this info with reflection (intentionally, because of the whole 'lombok should not be a runtime dep' notion). Other libraries' null annotations are more specifically designed for this.
* It has some effect on what `@RequiredArgsConstructor` does, in that non-null marked non-final fields are still considered 'required'. In that sense it also affects `@Data`.
* But the above is all small fry; the major impact of what lombok's `@NonNull` does, is: If put on a parameter, lombok generates an explicit nullcheck as first statement in the method.

And in that last thing there's the rub: What you're suggesting is that _every_ _single_ _last_ method in your __entire codebase__ nullchecks __every__ parameter __every time__, everywhere.

That is a _MASSIVE_ waste of resources and extremely useless, as by putting such a default in `lombok.config`, clearly the odds of null arriving in your methods is low to non-existent.

So, what possible problem are you trying to solve here?

The use of `@lombok.NonNull`, by and large, should be as replacement for writing explicit nullchecks. You should not use it as a more general documentary / 'Hey, IDE? If you could warn me when I pass in (potential) null values, lemme know at compile time so I can address that, okay?' – and that's presumably what you want.

I'm leaving this open for some more feedback, but, without drastic new information, consider it closed.

**Comment by vprudnikov** [comment]
@rzwitserloot , thank you for your reply!

I will try to explain what problem I'm trying to solve.

In our codebase, almost everything is assumed to be non-nullable, like in other programming languages like `Kotlin`. As a result, 99% of code is polluted by `@NonNull` annotations.

So the short story is:

1. **We would like to avoid adding `@NonNull` almost everywhere** but rather adding `@Nullable` where appropriate.
2. **We would like to eliminate the case when we forget adding `@NonNull` annotation** assuming it's working by default

Thanks!

**Comment by remal** [comment]
+1 to @vprudnikov. Many teams consider nullable values as harmful, so it would be very nice to have an opportunity not to mark everything with `@NonNull`.

@rzwitserloot please take a look at https://github.com/rzwitserloot/lombok/issues/2322#issuecomment-572565002. I think it can be a good solution for the problem.

**Comment by rzwitserloot** [comment]
I explained why festooning your entire codebase with `@NonNull` is a really bad idea; if you're doing that now, please stop that.

@vprudnikov if you have a codebase now that has `@NonNull` on every parameter in it, that wasn't a good idea; you should remove most of those, and stick with JSR305 or other annotation based nullity toolkits' package/module-level nnbd (non-null-by-default) mechanism to mark your params as such, and trust in your tools' abilities to discover violations at write time, not at runtime.

There is no point replying to a detailed and specific issue (such as: That would mean you have half a gazillion completely useless nullchecks all over your code base) and reply as if you didnt hear me and just go 'I think it is a good idea'. I need reasons for why my analysis (of: a gazillion null checks in an environment where it is highly inplausible they'd EVER fire, given that you're using tooling to warn at write time of potential null passes) is wrong, or this issue isn't going to be re-opened.

Here is the key argument:

**If your IDE / linting tool is already going to warn/error on potential null passes, why are you so hellbent on every method checking every parameter every time in your entire code base?**

If you have a solid answer to this question, I'll reconsider.

**Comment by vprudnikov** [comment]
@rzwitserloot ,

I would like to ask you 2 questions in order to fully get your point:

1. Could you please provide an example of the proper configuration of IDEA that can prove non-nullability at write time showing the errors? Maybe you know the right articles, plugins, etc. It would be great to see something concrete here.
1. Could you please explain _when_ developers should use `@NonNull`? In my opinion, such info would be very important since many developers might have found `@NonNull` very useful, then started using it more and more _but_ they didn't get the initial idea, so they ended up using this annotation almost everywhere.

I will personally try your advice and write feedback in order to share info with other devs.

Thank you!

**Comment by remal** [comment]
@rzwitserloot Unfortunately you can't completely rely on static analysis tools, you really need runtime checks. Here two examples: 
1. Another developer ignores static analyser warning and passes null. You can say that we have to configure CI properly, but often the reality isn't so perfect.
1. Someone uses our REST API, let's say from Node.js, where we relied on jsr305. Maybe it was a mistake to rely on it, but still we have many not obvious bugs.

So having runtime check we make code much more stable and safer.

**Comment by rzwitserloot** [comment]
@vprudnikov See https://wiki.eclipse.org/JDT_Core/Null_Analysis for an example for eclipse; intellij also has this: https://www.jetbrains.com/help/idea/nullable-and-notnull-annotations.html

@vprudnikov You use lombok's `@NonNull` annotations anywhere where you'd previously put in an explicit nullcheck: You use them when you want your code to runtime-check the annotated parameter.

NB: The javadoc of lombok's nonnull annotation, as well as the feature page, makes no bones about it: It immediately explains this precise concept (that it generates a runtime nullcheck) and says nothing more. It makes no claims whatsoever that you use it to indicate anything; contrast lombok's javadoc on this vs. the various other nonnull annotations from intellij, eclipse, checkerframework, and jsr305.

@remal Catering to bad CI and bad programmers is something we can do, but that only goes so far: Rarely do features that cater to bad programmers cross the bar of 'value vs. cost'. Bad practices and bad coders are really inventive; you can't style-guide and lint-tool your way out of mediocrity, unfortunately. It'll help... a bit. But here's the lombok rule:

**Lombok will not cater to suboptimal solutions.**

In this case, IF you can't trust your coding team to get it right, then it's time to put your foot down and tightly enforce allowed editors and their configurations: __FORCE__ use of the nullity analysers.

Secondly, upgrade your CI system so that it least it will emit warnings when it compiles anything with compile-time-analysable null violations.

If you don't have infra in place for this, then.. time to get to work. The above two solutions are possible and valid approaches if you can't trust your team to get it right, and they are both clearly superior to having lombok generate a gazillion null-checks.

The case where you have 'external' users of your API is more relevant, but the vast majority of methods you write aren't for external use, but it's hard for us to tell, and in addition, I believe that if you have proper nullity annotations on all your stuff and you have an extremely consistent approach to your code ((almost) everything never returns null and chokes on nulls, so don't give us nulls and you need not expect them in return – that is consistent), is enough. Even here adding a billion nullchecks to cater to bad coders who can't read docs is going a bridge too far.

Had this feature been extremely easy to write and maintain I might reconsider, but the problem is a bang for the buck issue: This is HARD to write and HARDER to maintain, so it better have plenty of payoff. It doesn't.

These arguments have moved the needle. Just, not enough.

**Comment by vprudnikov** [comment]
OK, it seems to me that the problem is _the EFFORT needed to implement the feature_. And the effort doesn't match benefits, from @rzwitserloot 's point of view.

As of now, I think we'll still add `@NonNull` annotations to "domain" classes and main APIs since it's safer to stop at their level rather than accidentally saving nulls (received from REST API) to DB by a mistake or sending nulls to another sub-system.

Probably, a good compromise could be applying `@NonNull` to ALL the methods that are non-private if we concerned about performance.

I hope that there will be someone else who needs this feature (or some flavors of it) so it will be considered one more time.

Thank you!

**Comment by remal** [comment]
@rzwitserloot Why are you talking so much about "bad developers"? It's just people and people make mistakes. Everyone make them. Static analysis won't help you if you provide JSON API for example, as the API's users can send requests using different languages or even manually.

We can discuss where to insert runtime checks and where not, but, imho, it's obvious that they make your code safer. And this is one of cool Kotlin features.

**Comment by rzwitserloot** [comment]
@remal Of course, people make mistakes. If these mistakes happen sufficiently often for you to be worried about it, set up a CI system and/or enforce IDE plugins. Using lombok annotations to generate the nullchecks is worse than those two options and is still forcing something.

kotlin doesn't do any of this stuff. Kotlin tells you _AT WRITE TIME_ that you messed up, by moving the nullity status into the type system. If what you want is 'I want what kotlin has', then this feature request isn't what you want.

I think it's clear this isn't going to go anywhere at this point. I keep tabs on traffic on closed issues, so if anybody has convincing arguments for why this is a worthwhile case, or has a low-maintenance option, by all means...

**Comment by vprudnikov** [comment]
@rzwitserloot , kotlin adds also checks at RUNTIME: https://discuss.kotlinlang.org/t/performance-intrinsics-checknotnull-called-for-every-parameter/1971/2

Probably the above will help you to understand what other developers want.

Again, IDE plugin doesn't protect from passing the null to underlying layers from Rest API at runtime.

Sorry, I got your point about the effort needed to implement this, but I disagree with you about importance. I still think that IDE plugin is worse alternative than checking at least non-private methods at runtime.

**Comment by sddavis** [comment]
@rzwitserloot perhaps I have a different use case for this feature (or a similar one). When using the Builder annotation, I would like the build method to fail if any required (i.e. final) fields have not been set. Not having called a certain method of the builder is not something my IDE can warn me about. Currently, unless I add a NonNull annotation to every final field, the builder just sets them to null. Since I am using org.eclipse.jdt.annotation.NonNullByDefault on my packages, ideally, Lombok would treat all final fields in such packages as though they are annotated with NonNull, but providing another way to achieve this, such as a configuration setting or an argument to the Builder annotation, could also work.

**Comment by domdorn** [comment]
hmm.. I see the runtime cost of this, but wonder if we could make it (or another annotation) via config in a way that its generating 
`assert myOb != null; `
that way I can bear the runtime cost during development but switch off the flag when releasing to production? 
in a perfect world, I would have a switch where a `@NonNull`in my web layer would generate real null checks (and thus protect me from evil input data) and in other layers/packages (via lombok.config) would just create those assert statements that get optimized away when running in production?

**Comment by luochen1990** [comment]
I find that lombok doesn't consider [`@ParametersAreNonnullByDefault`](https://www.jetbrains.com/help/idea/parametersarenonnullbydefault-annotation.html) for the auto generated constructors

**Comment by bjmi** [comment]
> kotlin doesn't do any of this stuff. Kotlin tells you _AT WRITE TIME_ that you messed up, by moving the nullity status into the type system. If what you want is 'I want what kotlin has', then this feature request isn't what you want.

Even Kotlin doesn't entirely rely on the type system at compile time.  
There is a null-check provided by the [Intrinsics](https://github.com/JetBrains/kotlin/blob/6e17269d0513eabef2ae7b215c21c32b3d715826/libraries/stdlib/jvm/runtime/kotlin/jvm/internal/Intrinsics.java#L23) class to ensure non-null values at runtime and provide fail-fast behavior.

But #3861 on package-level would relieve a lot of the null-pain already.
