### ISSUE TITLE
[FEATURE] Support NonNull annotations on classes and packages

### ISSUE THREAD

**Issue by remal** [rzwitserloot/lombok#2322]
With JSR 305 annotations you can put NonNull/Nullable annotations on package or class. For example:
* `org.springframework.lang.NonNullApi`
* `org.springframework.lang.NonNullFields`
* `javax.annotation.ParametersAreNonnullByDefault`
* and so on...

It would be really useful, as putting NonNull annotations on every element takes much longer then on the class/package.

**Comment by Frontear** [comment]
This is a curious suggestion. What would you expect lombok to do if I, say used `@NotNull class MyClass`, then did `MyClass inst = null;`. Should lombok fail to compile this piece, or should lombok just silently annotate it with `@NotNull` and continue on?

**Comment by Maaartinus** [comment]
> Should lombok fail to compile this piece

Lombok can't see `@NotNull class MyClass` when it's in a different compilation unit. Having a non-nullable class without a nullable counterpart (like `MyClass?` in Kotlin) makes little sense. So I guess, the OP wanted something else.

The annotation on a class level work as if everything in the class body was annotated with it and let Lombok generate the null checks. Maybe not everything as that could lead to some unexpected NPEs simply due to missed places.

I guess, the equivalents to the three listed annotations performing runtime checks is what the OP wanted. The use for method return values is questionable #907, but for parameters and fields it'd be IMHO very useful.

Disclaimer: I'm not a Lombok team member.

**Comment by rzwitserloot** [comment]
I assume @remal is asking if lombok can just.. stick that annotation on everything the compiler even touches.

That's beyond the scope of what lombok is for.

**Comment by remal** [comment]
@rzwitserloot Let me provide some details. If you still think that it's out-of-the-scope, leave the issues closed.

Let's say I have package `pkg`.

I create `pkg/package-info.java` file of this content:
```java
@NonNullApi
@NonNullFields
package pkg;

import org.springframework.lang.NonNullApi;
import org.springframework.lang.NonNullFields;
```

Also I create a DTO file `pkg/DTO.java` like:
```java
package pkg;

import lombok.Value;

@Value
class DTO {
    String field;
}
```

In this case `DTO.field` field is treated by static analysis tools like non-null field unless it's annotated by some `Nullable` annotation. It would be very useful if Lombok generates null checks in generated methods.

PS: Sorry for the late response, I was on vacation.

**Comment by rzwitserloot** [comment]
That seems so weird to do though; you're already invoking IDE and linting tools to warn/error on potential null passes to these methods, why add a runtime check at this point?

**Comment by remal** [comment]
@rzwitserloot  The reason is very simple: there is no tool that makes runtime nullability checks based on package-level annotations. At least I don't know about them. The first thing I looked at was of course Bean Validation, but it would be a huge challenge to write such extension.

So nothing prevents another developer to ignore static analyzer warning and pass null where we don't expect it. And it leads to  bugs that are really hard to debug. As a result, we place `lombok.NonNull` or `javax.validation.NotNull` on a huge amount of fields and it's not very convenient...

**Comment by Frontear** [comment]
> That seems so weird to do though; you're already invoking IDE and linting tools to warn/error on potential null passes to these methods, why add a runtime check at this point?

Doesn't this also stand for the normal usage of `@NotNull` anyways? IDE's would also flag null parameters, yet this annotation exists.

**Comment by Maaartinus** [comment]
@remal 
> So nothing prevents another developer to ignore static analyzer warning and pass null where we don't expect it.

People ignoring warnings must be taught better. Taught, blackmailed, tortured, fired, whatever. That's the only sane way.

That said, I'm interested in this feature, too.

**Comment by remal** [comment]
@Maaartinus I agree, but we live on not perfect world and work with not perfect people. So runtime checks help.

Moreover there are cases where static analysis doesn't help. For example when we deserialize JSON from some source.

**Comment by Maaartinus** [comment]
> I agree, but we live on not perfect world and work with not perfect people.

Sure, mistakes are unavoidable. But ignoring warning is not.

> Moreover there are cases where static analysis doesn't help. For example when we deserialize JSON from some source.

That's why I'm interested in this feature, too.

The general rule is to get rid of nulls ASAP. Normally, throwing is the right thing, for data coming from the outside, converting nulls (and missing values in JSON) to empties might be the right thing. Ideally, the JSON deserializer should do it, but I'd like to see a Lombok variant of `NonNullFields`, too.
