### ISSUE TITLE
Support @Delegate on multiple fields of same type, such as List

### ISSUE THREAD

**Issue by mefernandez** [rzwitserloot/lombok#2337]
I just want to use `@Delegate` on two `List<String>` fields. 
It would allow to have convenient `add*` methods instead of `getX().add(X)`.

```java
	@lombok.Data
	public static class Data {

		@Delegate(types = { ElementAdders.class })
		private List<String> elements = new ArrayList<String>();

		@Delegate(types = { ItemAdders.class })
		private List<String> items = new ArrayList<String>();

		public interface ElementAdders extends List<String> {
			
		}

		public interface ItemAdders extends List<String> {
		}
	}
```

The code above produces multiple "Duplicate method" compiler errors.

Is there any way to do it with Lombok?

**Comment by rzwitserloot** [comment]
I'm not sure it's that convenient.

Let's say you had the option to do that. That'd mean, here, you'd get:

    clearElements()
    listIteratorElements()
    iteratorElements()


that's great, but then...

    addElements(Element e) // huh, only a single element??
    addAllElements(Coll..) // Weird
    setElements(int, E) // this sets a single element, weird name.

You could use just singular `Element` as suffix, but then the first list is a bit odd. `clearElement` sure sounds like 'delete one element', not 'clear the entire list of elements'. You could go with a prefix:

    elementsAdd
    elementsAddAll
    elementsClear

and that's a sight better to be sure, but it's in the minority for how methods are commonly named. Clear blue sky? I'd expect the method to add an element be named `addElement` and not `elementAdd`.

Conclusion: This is a LOT harder to do right than it looks.

**Comment by mefernandez** [comment]
I agree with all of the above. 

In all, I just wanted two things:
1. Not calling `getElementts()`.
2. Not checking `getElements()` returning null.

Probably not worth it. It just struck me to be able to `@Delegate` one field, but not two.

**Comment by rzwitserloot** [comment]
The fix for having `getElements()` return null is partly just kicking the can down the road, and partly irrelevant because there are better solutions.

## Kicking the can

Lets say elements IS null, what does `container.elementsAdd()` do then? Silently do nothing? That is appealing at first thought, but with some longer thought, that is in all sorts of ways the wrong way to go about it. You end up with: In absence of explicit information about what to do.. throw an NPE. Yeah okay we get to add a nice message but that's not much of a win over `.getElements().add()` which would also throw one, AND java will soon make NPEs like this have a nicer message anyway.

## Wrong place to do it

null does not mean, and never has meant, 'empty'. It means 'no value'. If, for some concept, 'no value' and 'empty' are dangerously close to being interpreted as semantically equivalent, or there really is no sense in having 'no value' there, and any border cases are best solved by having the empty value be the standin, then __DO NOT EVER USE NULL HERE__. The fix is to find the place where this field or variable ends up being null, or where some API call returns null, and fix it, so that it's empty list instead. This doesn't necessarily involve an if. For example, upgrade `map.get(key)` to `map.getOrDefault(key, "")`.

The feature thus awaits a really good use case to warrant further efforts in solving the naming issue. Until then let's just close it.
