### ISSUE TITLE
When using @AllArgsConstructor, how do you want to ignore the injection of a property

### ISSUE THREAD

**Issue by tanhuang2016** [rzwitserloot/lombok#2341]
![image](https://user-images.githubusercontent.com/38677722/72673862-b2647200-3aaa-11ea-8400-5f71c164d457.png)

Action:

Consider defining a bean of type 'java.lang.String' in your configuration.

As you can see, an error is reported if a property of type String is defined.
Is there any good solution,pleas

**Comment by Maaartinus** [comment]
That's not a Lombok problem as you can see when you define the `@AllArgsConstructor` manually.

The problem is with the other thing you're using (Spring?), which tries to find a bean for each argument of the constructor. Obviously, `prefix` needs none. In case you prefix is a constant, make it `static` and you're done as it disappears from the constructor. If it should be set by Spring, you must learn how to do it... I don't use Spring.

If you need to annotate the constructor arguments, then you're out of luck as this AFAIK hasn't been implemented yet.

Anyway, stackoverflow.com would be a much better place to ask as the project owners don't use Spring either.

**Comment by randakar** [comment]
Just annotate that field with
https://www.baeldung.com/spring-value-annotation
