### ISSUE TITLE
[FEATURE] need for @Builder.Default ?

### ISSUE THREAD

**Issue by nimo23** [rzwitserloot/lombok#2342]
**Describe the feature**
I must use `@Builder.Default` when using `@Builder `on class level:
        
```
// must add this annotation to tell lombok
@Builder.Default
// it already has a "new" keyword which can also tell lombok to create its instance
private List<User> users = new ArrayList<>();
```

Maybe lombok can initialize all fields in the builder automatically when it has a `new`-operator on the left hand side of the property. That is also the default behaviour of java: when creating an instance of the class it also creates the instances of its properties if there is a `new`-operator. So maybe lombok can make that automatically by watching for the `new`-operator instead of the need to watch for `@Builder.Default`.

**Comment by Maaartinus** [comment]
@nimo23 
> So maybe lombok can make that automatically by watching for the new-operator instead of the need to watch for `@Builder.Default`.

That's pure magic. You'd react to `new`, but there are things like static factory methods (Guava provides tons of them) which are used in place of a constructor (e.g., `Lists.newArrayList()` or `ImmutableList.of("a", "b")`). There are tons of other ways how to create a new object. So this would be a very strange criterion.

The problem is not with the `new` operator, but with field initialization in general. In a `@Builder`-annotated class, this line
```
private List<User> users = new ArrayList<>();
```
actually defines two fields: one in your class and one in the builder. Yet there's a single initializing expression. The questions are: Should it be used in the builder, in the generated constructor(s), in manually written constructors?

*I could imagine using it in the builder unconditionally.* Lombok is conservative by requiring an annotation. Your approach might do what's wanted most of the time and sometimes, lead to very bad surprises.

**Comment by nimo23** [comment]
>There are tons of other ways how to create a new object. So this would be a very strange criterion.

With `@Builder.Default` it should behave as default where the `new` is the trigger. Creating an object with `new` is done most of the time. For other cases, an annotation like `@Builder.AddProperty` can be used. 

The best would be if lombok uses the initialization part (independend of new or something like `ImmutableList.of("a", "b")`) always automatically in its builder constructor/method when a class is annotated with `@Builder`.

**Comment by nimo23** [comment]
Maybe lombok can have an additional property `@Builder(addDefaultConstructor="true") `to include the default constructor within its builder method at the beginning. With the default constructor one can include its initializiation logic, for example:
```

// no need for @Builder.Default
@Builder(includeNoArgsContructor=true)
@AllArgsConstructor
public class User{

// will be called at the beginning of the lombok generated builder method
public User() {
this.firstName = computeName();
this.lastName = "test";
}

}
```

**Comment by rzwitserloot** [comment]
It's more more complicated than you think, @nimo23. What you want just isn't even remotely possible.
