### ISSUE TITLE
[FEATURE] Configurable default AccessLevel for generated constructors

### ISSUE THREAD

**Issue by CarlSalaets** [rzwitserloot/lombok#2348]
### As is
The annotations to generate constructors by default have `AccessLevel.PUBLIC`

### Desired
Allow to set another default AccessLevel for constructors in `lombok.config`

### Why
I would like to make the generated constructors private by default. That is very handy when using mainly static factory methods.

**Comment by rzwitserloot** [comment]
If you let lombok make these static factory methods (using `@AllArgsConstructor(staticName = "of")` for example), then private is the default.

And if you're in the habit of always writing a custom one, I don't think it's a good idea to squirrel away the notion that the generated constructor is always private in a setting. I think the notion 'every single last class file I ever write, or at least almost all of them, will always have an explicitly written static constructor' is _very_ exotic style, and beyond what we should be supporting.

We need to think of the principle of least surprise. `@AllArgsConstructor` generating a private constructor because of a setting in `lombok.config` is in my opinion beyond what is reasonable to expect casual readers of code to think of.

So, no can do :(
