### ISSUE TITLE
[FEATURE] Configure Lombok to generate @Pure annotations for checkerframework

### ISSUE THREAD

**Issue by Meijuh** [rzwitserloot/lombok#2386]
It would be useful to generate checkerframework's `@Pure` annotation at least for generated getters and setters. See example below:

    // example field with generated getter
    @Getter
    private @Nullable String field;

This assumes we have  configured lombok with `lombok.addNullAnnotations = checkerframework`.
Now, without `@Pure` the following statement makes checkerframework raise the error: `error: [dereference.of.nullable] dereference of possibly-null reference getField()`.

    System.err.println(getField() == null ? "" : getField().toString());

Adding `@Pure` to `getField()` will not raise the error for the second occurence of `getField()` since checkerframework will know calling `getField()` does not change state.

**Comment by rzwitserloot** [comment]
Makes sense, and is an easy addition.

**Comment by Meijuh** [comment]
Note that opposed to my first comment, `@Pure` should obviously not be added to setters, as a setter does change state.

**Comment by rzwitserloot** [comment]
Actually, nevermind. That's not how I understand `@Pure`.

What if the field is non-final, and there is a setter. Is it still deterministic? I don't know what CF's definition is, but it should warn here; maybe another thread, in between your first invocation of `getField()` and the second one, set the field to null. We could generate Pure in a few cases, but not very many. We intentionally elected to generate only `@SideEffectFree` and not `@Pure` because that, at least, is a guarantee we can actually make.

The ones where we can generate `@Pure` aren't particularly interesting; the only nice one is on generated getters for final fields, which is still worth considering.

Second point, on the topic of CF integration: Where's my promised `@ReturnsReceiver`, `@NotCalledMethods`, and `@CalledMethods` at? :)

We designed the CF feature because Michael showed us these annotations, but as far as I can tell, they still haven't showed up in CF v3.2.

I've fixed lombok to no longer generate them until you set checkerframework to '4.0', and they are no longer generated if you set it to 'true' either, as a temporary bandaid, but I was left with the impression team CF would be adding these!

**Comment by rzwitserloot** [comment]
The above does as follows:

* canEqual is now Pure instead of SEF.
* getters are Pure instead of SEF... but only if the field is final.
* The private self() methods in superbuilder are Pure instead of SEF.
* ReturnsReceiver and CalledMethods and NotCalledMethods are now bound to v4.0 and not v3.0 (set `checkerframework = 4.0` to get em; `checkerframework = true` now is equivalent to `checkerframework = 3.2` which no longer generates those.

That sounds right to me, but if I messed that up, let me know by replying (I track closed issues).

**Comment by rzwitserloot** [comment]
Current edge release has the feature: https://projectlombok.org/download-edge

(Not listed in the changelog; not important enough for an entry I think).
