### ISSUE TITLE
[FEATURE] Super Builder should optionally have a public *BuilderImpl

### ISSUE THREAD

**Issue by ddcruver** [rzwitserloot/lombok#2392]
Could the Super Builder have a configurable access to *BuilderImpl so that it can be be used outside the class. Like in Generics.

**Comment by janrieke** [comment]
Could you further elaborate on your use case? Because typically you should not need the Impl, apart from when you want to instantiate the builder (which you'd typically do just by calling `builder()`).

Adding another parameter to `@SuperBuilder` might not sound like a big deal, but it increases the maintenance burden. Furthermore, it may confuse users, because most people simply use this annotation without knowing about the large amount of generics-loaded code with two different classes that is generated by Lombok.

**Comment by ddcruver** [comment]
I will have to get back with an example for you but basically the I have a hierarchy of classes, we will call them transformers, that construct the lombok genereated classes with their builders.  Each transformer of the hierarchy maps to a specific lombok generated classes and passes its builder to parent transformers before filling out the fields that are defined by that class (and not inherited).  
You may need to see an example before you understand my use case fully.

**Comment by ddcruver** [comment]
I think I may actually be able to do what I want.  The generics in my example and implementation are across three types of class (the controller, a trasnsformer and the generics of the lombok classes) where each is defined as a hierarchy.  In my first attempt I may have defined the generics wrong or to tightly, but I believe I have resolved that issue.

[lambok-super-builders-example.zip](https://github.com/rzwitserloot/lombok/files/4313070/lambok-super-builders-example.zip)

Regardless I am forced to use wildcard generics which I find ugly and confusing and try to minimize the usage of them.  I recently contributed a fix to another project that generates inheritable builders as well, https://github.com/joelittlejohn/jsonschema2pojo/pull/1101, and have a later suggestion to improve it some more with https://github.com/joelittlejohn/jsonschema2pojo/issues/1104.  If you look at the later pull request you can see this project has choose to take the approach that the inner method end in Base, as most people will not use this builder and leave the one consumers use as to match the name of the class.  

We made the base/inheritable builder as abstract so no one could use it directly and exposed the "generic resolved" version for ease of use.  In the jsonschema2pojo's version of an inner class builder you don't have the awkward builder as having a generic of itself being exposed to the user.  
The only time they are exposed to the generics is if they need to extend the class or generically use the class in ways I described above.

Regardless I do like your helper builder constructor method.

**Comment by janrieke** [comment]
We cannot use `*BuilderImpl` as return type, because that would cause the methods of subtype builders not to be callable, because they extends the abstract `*Builder`, not the `*BuilderImpl`. I'm almost 100% sure that there is no way to change this, because I spend several weeks to get all this to work in a type-safe manner without any type casts.

Back to the original feature request: an access modifier for the impl. From my point of view, as your use case does not require this feature, the only argument that remains is "it doesn't look good". Considering that a) this is a matter of taste, and b) such a use case seems quite rare, I vote for "no".

But I'm not a lombok team member, I just contributed the `@SuperBuilder` feature. So the decision is not up to me.

**Comment by ddcruver** [comment]
Regardless maybe someone can combine the work from both projects to make a more user friendly version based on both of these implementations.  I personally like the jsonschema2pojo method. One thing is also the method that actual returns the builder should be renamed to end in builder because that is what it returns.

**Comment by janrieke** [comment]
If I understand it correctly, jsonschema2pojo is a regular Java tool that generates code. It can do things an annotation processor like Lombok can't. Especially it can gather information on the class hierarchy and the content of every class in it. That is not possible for Lombok, which can only see the current single compilation unit.
That makes it impossible for Lombok to generate builders like jsonschema2pojo.

**Comment by ddcruver** [comment]
Fair enough. Yes it generates Java code based on json-schema spec (with extension) with the sun code model library. I suppose it might have more information about parent classes.

**Comment by ddcruver** [comment]
I will close this for now.
