### ISSUE TITLE
Allow noIsPrefix for getters on a per-getter basis

### ISSUE THREAD

**Issue by hakanai** [rzwitserloot/lombok#2464]
**Describe the feature**

Depending on the name of the property, sometimes `isUpdated()` makes sense and other times `isWasUpdated()` makes no sense so naming it `getWasUpdated()` is preferred.

We can configure all such methods to be named with `get` in the config file of course, but sometimes I'd still like to be able to have methods named with `is`. :(

So I'd like something along the lines of:

```
    // generates getter called isAccessible()
    @Getter
    private boolean accessible;

    // generates getter called getWasUpdated()
    @Getter(noIsPrefix = true)
    private boolean wasUpdated;
```

**Describe the target audience**

People who are opinionated about the naming of bean methods. ;)

**Additional context**

None?

**Comment by Maaartinus** [comment]
IMHO there are just three usable options:

- You have to be javabeans compatible. Then you're partially out of luck as the crap is incompatible with itself (for fields named like `uShaped`), but in general, it works out of the box.
- You want to be consequent and always use "get" and "set" prefix. Then put `lombok.getter.noIsPrefix = true` in `lombok.config`.
- You want to use the fields name as for the getter and setter (like in a builder). Then use `lombok.accessors.fluent = true`.

Of course, every rule has exceptions. The exceptions should be rare, otherwise the users of the library get lost guessing. Lombok doesn't support exceptional cases, it only cares about boilerplate. So I guess, you need to write some getters manually (possibly with `@Getter(AccessLevel.NONE)`).

Disclaimer: I'm not a project maintainer.

**Comment by trejkaz** [comment]
JavaBeans actually permits both `is` and `get` for boolean properties, so I don't know what you're talking about. It has always been about whether reading the method name as "is something" made sense or not, for whether you named it as `is` or `get`.

**Comment by MichelMunoz** [comment]
> JavaBeans actually permits both is and get for boolean properties, so I don't know what you're talking about. It has always been about whether reading the method name as "is something" made sense or not, for whether you named it as is or get.
Nobody said the contrary. There must be a misunderstanding, @Maaartinus gave you rationales and solutions to your problem
- your objects api should be consistent (coherent, "guessable", easily discoverable...), thus the general configuration solutions provided by @Maaartinus + the defaut behavior of Lombok allow that (`boolean` -> is, `Boolean` -> get)
- but, there are always _rare_ exceptions to the general consistency, in which case, as indicated by @Maaartinus , Lombok already provides you with two solutions (implementing the getter or changing from boolean to Boolean) as illustrated here:
```
@Getter
class SomeClass {   
    private boolean value1;
    
    private boolean value2;
    
    private Boolean value3;
    
    public boolean getValue2() {
        return value2;
    }
}
```
will give you a isValue1(), getValue2(), getValue3().

**Comment by trejkaz** [comment]
Whether the  "exceptions" are rare or not depend on what you're writing. In our case it's heading towards 50/50, and I can easily imagine cases where it might be the majority.

I _know_ that I can just implement the method. I can avoid Lombok entirely, with the same end result. I was just asking for a new feature to be able to configure this on a per-property basis, so that I can remove all trivial getters instead of just half of them.

**Comment by randakar** [comment]
Why that many booleans?

I tend to see 'too many flags' as a warning sign that the programming model
has problems. It may be actually modelling the problem space, but..
usually, it's caused by too much procedural C-like code...

**Comment by trejkaz** [comment]
The codebase is just several gigabytes in size, so even a proportionally small number of boolean getters adds up in numbers overall. But the real answer is probably "because all these dumb JSON serialisation libraries force us to have them". :(

**Comment by randakar** [comment]
That's ridulously large. My sympathies.

What JSON serialization libraries force you to have Boolean fields though?
Pretty sure Jackson doesn't...

**Comment by trejkaz** [comment]
They're not `Boolean`, just `boolean`.

**Comment by randakar** [comment]
Thank you autocorrect ;)

**Comment by rzwitserloot** [comment]
We'd be adding an annoparam that everybody sees and which is completely irrelevant for 90%+ of all properties (all non-booleans), just to cater to a use case where you're replacing a one-liner method with an annotation that contains as many characters as the very code it is supposed to replace.

Not worth the maintenance burden and throwing this in everyone's face, by miles.

**Comment by hakanai** [comment]
It's only a one-line method until you open your eyes and see the rest of the required boilerplate. So you'd actually be replacing 4 or 5 lines with a single parameter, which is definitely worth it for the readability if not the time saved.

**Comment by rzwitserloot** [comment]
> you open your eyes

Crap on ideas all you want. But don't make it personal, please.

> And people who don't want to use it can just ignore it.

IDE autocomplete dialogs will show it. This line of arguing is not going to change the status of this issue.

**Comment by dylanpiergies** [comment]
I am inclined to agree with OP that it would be a useful feature to enable the naming of specific fields' accessors to be coerced using annotations. Trying to figure out how to do that has led me here, after all.

I do find it surprising that Lombok hasn't adopted an approach similar to that used by libraries such as Jackson, whereby pretty much every globally configurable option can be overridden using annotations both at the class and the field level, as appropriate.

**Comment by Alluseri** [comment]
And here we are in 2026, because someone was too afraid to add a parameter to an annotation (the most burdensome of maintenances)
