### ISSUE TITLE
[Help] Need @SuperBuilder support if I can not add the annotation for GrandParent class

### ISSUE THREAD

**Issue by FavorMylikes** [rzwitserloot/lombok#2526]
``` java
// There is a class from outside like importing from maven
// I Can not add @SuperBuilder annotation for this class
class GrandParent {
    // It has a No Arguments constructor method
    public GrandParent(){}
}
@SuperBuilder class Parent {
    private String field_A;
}
@SuperBuilder class Child {
    private String field_B;
}
```
#### What ways do I want to use;
```java
Child.builder().field_A("a").field_B("b").build();
```
How can I do that by changing `Parent` code to cut off the `@SuperBuilder` chain

**Comment by janrieke** [comment]
There is nothing Lombok can do here, because it cannot access `GrandParent` when it processes `Parent`.

However, you can manually implement the necessary builder class for `GrandParent`. See [this StackOverflow topic](https://stackoverflow.com/questions/61708752/using-lomboks-superbuilder-concept-on-a-class-extended-from-a-3rd-party-librar/61763012#61763012) for details.

**Comment by FavorMylikes** [comment]
That's really helpful. 
Thank you.
