### ISSUE TITLE
[FEATURE] Allow @Log4j2 (and probably its cousins) on interfaces

### ISSUE THREAD

**Issue by AndrewLazarus** [rzwitserloot/lombok#2584]
Since Java 8 allows static variables in interfaces, couldn't the `Log4j2` annotation apply there as well as classes?
I think this may be literally a one word change, plus a comma.

**Comment by SimSonic** [comment]
Hovewer both static fields and static inner classes in interfaces cannot be private.

**Comment by rspilker** [comment]
I don't think it is common enough to have a public logger in an interface. Also, accessing the logger when implementing multiple interfaces with log fields would also be interesting.

**Comment by mjustin** [comment]
@rspilker — I just ran across some code in the wild (that otherwise uses the Lombok logging annotations) that creates a static logger on an interface for use within its own default methods.  So this feature could be used within an interface without accessing the logger externally to the interface.

But the point about it being non-private still applies.

**Comment by rzwitserloot** [comment]
Making em public feels really ugly, though. The handicapped nature of default methods (you can't have constants at all unless you make them public, and you can't have private static inner classes either) means I usually just make a package private class in the same package with the meat and potatoes and then farm the work out to this from the default method. That also solves the logging issue.
