### ISSUE TITLE
[FEATURE] spring-boot main annotation (e.g. @SpringBootMain)

### ISSUE THREAD

**Issue by dominik-kovacs** [rzwitserloot/lombok#2606]
Spring boot code

    @SpringBootApplication
    public class HelloWorldApplication {
    
        public static void main(String[] args) {
            SpringApplication.run(HelloWorldApplication.class, args);
        }
    }

Desired solution:

    @SpringBootApplication
    @SpringBootMain
    public class HelloWorldApplication {
    
    }

https://github.com/spring-projects/spring-boot
Since the main method is a generated code, it would be nice to hide it behind an annotation - for example, @SpringBootMain
Also, it could be ignored by coverage tools, right now it is not by default.

**Comment by viveksacademia4git** [comment]
I think that this would be a great feature, especially because of the mentioned coverage issue.

**Comment by juriad** [comment]
It is really useful to replace 3 (or 4 with annotation suppressing coverage tool which you can add there manually even now) lines of code with 1 line once in an application? There are also scenarios which require doing stuff before calling `run` (setting up `MDC` for example), in which cases the annotation will not be useful.

From my experience, the main class of Spring Boot applications often exists only to have the main method, so the presence of the main method does not pollute it. The main method is also not a place where people would make mistakes.

Some project generators already generate the main class with the main method for you, so you actually need to manually replace the method with the annotation. The generators will not switch to using Lombok for just one annotation as there are people who don't want to use Lombok. Setting up Lombok is another place where things can go wrong for newbies who would then blame Spring for being hard/tricky to use.

Lombok is a tool which is very hard to maintain, it is not as easy as adding a template with desired expansion, which by the way you can do in your IDE.

We can go a bit further: why not having an annotation (for example in `package-info.java`) for generating the whole main class? This would actually be much easier as regular annotation processors are designed to produce new class files (instead of modifying existing ones which Lombok does).

Just my two cents. I am not a Lombok maintainer, I am a user and I have contributed once, so I am knowledgeable of its internals.

**Comment by rspilker** [comment]
Reinier and I really do not care about the code coverage problem. I don't even see the problem? Is the main method not executed? Talk to the developer of your code coverage tool on how to configure it to not report this main method.

Also, we're talking about replacing 3 lines of boilerplate by one annotation. In the whole project. That's not enough to warrant the extra maintenance burden.
