### ISSUE TITLE
[FEATURE] SuperArgsConstructor

### ISSUE THREAD

**Issue by ManuInDenWolken** [rzwitserloot/lombok#2646]
**Describe the feature**
An annotation generating a constructor like `@AllArgsConstructor` or `@NoArgsConstructor` matching super in case of a single constructor in super class.

**Comment by randakar** [comment]
This is currently not possible due to known limitations in the way Lombok
works. The Java Annotation Processor API simply doesn't provide the
information required.

For background, see
https://github.com/rzwitserloot/lombok/wiki/LOMBOK-CONCEPT:-Resolution

**Comment by dodtsair** [comment]
Perhaps the issue with resolution can be avoided by pushing the problem to the developer.

I have something like this
```
@Data
class A
  int a;
}
```
Followed by 
```
@Data
class B extends A
   int b; 
}
```

With this setup everyone is looking to construct B like the following `new B(1, 2)` This is not possible it would require resolution

However if a copy constructor annotation is supported (which would require any parent class to have a copy constructor or fail due to compiler error) then we can switch the developers code to the following `new B(new A(1), 2)` it is more ugly, but it would work.  And yes if you had another class called `C` with similar pattern you would end up with `new C(new B(new A(1), 2), 3)` uhg, but it works.  

This would need to be an optional addition on the subclass.  Something like:
```
@Data
@AllArgsConstructor(callCopyCon=true)
class B extends A
   int b; 
}
```

Which would then generate code that looked something like
```
B(A a, b) {
super(a);
this.b = b
}
```

As mentioned before at this point you have a compiler error (as designed), so A would need to be updated to have a CopyConstructor

```
@Data
@CopyConstructor
class A
  int a;
}
```

This would need to generate a constructor like the following
```
A(A copyFrom) {
this.a = copyFrom.A
}
```

You can likewise require the parent class to either be Object, or have its own CopyConstructor (failing to compiler error as designed).  For example adding the @CopyConstructor to the B class would generate the following constructor in B
```
B(B copyFrom) {
super(copyFrom);
this.b = copyFrom.b;
```

Of course you have the readily available alternatives of @Builder @SuperBuilder and @With.

**Comment by rzwitserloot** [comment]
Yeah, but that's just a straight up worse and weird solution compared to the sensible thing, which is to duplicate parent class's constructor's params. Yeah, due to resolution we cannot easily do that, but the solution is to put in the effort to make that work, not to go for an inferior solution.
