### ISSUE TITLE
[FEATURE] boolean inversion generator

### ISSUE THREAD

**Issue by SirNapkin1334** [rzwitserloot/lombok#2663]
**Describe the feature**
A boolean toggle setter, that generates a function that, when called, flips the boolean's state. This can be done either with a field on the `@Setter` (maybe `@Setter(generateInverter = true)`), or with a separate  annotation extending `Setter`. 

### Lomboked Code:
```java
public class Main {

	@lombok.Setter
	@lombok.Getter
	@Lombok.Inverter
	private boolean test;

	public static void main(final String[] args) {

	}
}
```

### Or, alternatively
```java
public class Main {

	@lombok.Setter
	@lombok.Getter(generateInverter = true)
	private boolean test;

	public static void main(final String[] args) {

	}
}
```

### Delomboked Code:
```java
public class Main {

	private boolean test;

	public static void main(final String[] args) {

	}

	public boolean isTest() {
		return test;
	}

	public void setTest(final boolean $test) {
		test = $test;
	}

	public void setTest() {
		test = !test;
	}

}
```

**Describe the target audience**
This would be useful for setting flags. Especially if you are only going to set the flag once, and you know the predefined value, calling the inverter function is a bit cleaner. Obviously it is also useful if you want to flip the value of the boolean, as instead of doing `main.setTest(!main.getTest())` you can just do `main.setTest()`. Perhaps the overloaded `setTest` may not be the best name, I am open to ideas for other names (perhaps `flipTest` or allowing you to customize the name?).

**Additional context**
None.

**Comment by solonovamax** [comment]
Napkin, keep your shitty ideas just in our discord server  .

**Comment by SirNapkin1334** [comment]
bruh

**Comment by xTrM-EN** [comment]
Interesting idea, +1

**Comment by proudmuslim-dev** [comment]
> Napkin, keep your bad ideas in our discord server .

Please keep your de-constructive opinions in your head

**Comment by solonovamax** [comment]
> > Napkin, keep your bad ideas in our discord server .
> 
> Please keep your de-constructive opinions in your head

It's napkin we're talking about here, we all do this in the sk1er discord.

**Comment by SirNapkin1334** [comment]
can you all not please

**Comment by proudmuslim-dev** [comment]
> It's napkin we're talking about here, we all do this in the sk1er discord.
The fact remains that you're ruining his thread, so cut it out. Let the repo maintainers decide

**Comment by rspilker** [comment]
As a maintainer, first, the original request was valid an well-formatted, according to our template instructions. It described the idea and contained examples in "lombok" style and plain java, and it tried to explain the target audience.

Regarding the feature itself, I have some comments:
- Since it would only apply to `boolean` fields, making it a property of `@Setter` is a bit strange. Especially since this is not a very common thing to do.
- I think that the suggested naming pattern `setXxxx()` (without parameters) is misleading. I would prefer `toggleXxx()` or, as suggested in the proposal `flipXxx()`. `@lombok.Toggle` or `@lombok.Flip` would then be a better annotation.
- In my personal experience, I haven't encountered the need for such a feature enough to call it "boilerplate". I don't ythink it is worth the added maintenance load to the lombok code base.

I'm rejecting the request because the expected added benefits do not outweigh the added maintenance load.

**Comment by SirNapkin1334** [comment]
Alright. Thank you for the feedback.

**Comment by rzwitserloot** [comment]
@SirNapkin1334 yup. Feel free to lord over your friends on that discord server that whilst your idea went down in flames, they were glorious. I'm going through a bunch of feature requests and this one is stated more plainly and clearly than any of em, so, I'll gladly read through more ideas like this :)
