### ISSUE TITLE
[BUG] @Builder at class level can reuse a constructor with the same signature but different param order

### ISSUE THREAD

**Issue by vbuciuc** [rzwitserloot/lombok#2672]
**Describe the bug**

If a class has an existing constructor with the same signature that @Builder would generate when set on class, but with parameters in a different order than the order in which the class fields are declared then the lombok generated builder will build instances with switched values for fields.

```
    @Builder
    @Getter
    public static class OrderedFieldsWrongOrderConstructor
    {
        private String name;
        private String kind;


        public OrderedFieldsWrongOrderConstructor(final String kind, final String name) {
            this.kind = kind;
            this.name = name;
        }
    }

```

**To Reproduce**

Run ```mvn test``` on repo: https://github.com/vbuciuc/lombok-builder-issue

**Expected behavior**

Throw a compile warning or error when am existing constructor might be reused.

**Version info (please complete the following information):**
 - lombok 1.18.16
 
```
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_272, vendor: Debian, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.9.0-2-amd64", arch: "amd64", family: "unix"
```

**Additional context**

Apologies if this was reported before, I did a quick search but didn't come up with anything.

**Comment by janrieke** [comment]
Using a custom all-args constructor for `@Builder` is a valid use case and is often intended. So always reporting a warning (or worse, an error) is not a good choice.
Theoretically, Lombok could emit a warning when an existing constructor has a matching signature, but differing parameter names. But maybe the coder wanted the parameter names to be different for a reason. I'm not sure if there is a good way out of here...

**Comment by rzwitserloot** [comment]
@vbuciuc there is nothing lombok can possibly do here. Except, perhaps, look at the _names_, using those to detect that things may not be in order. But you're free to pick whatever names you like, so, that's just not appropriate - languages (and lombok, which sticks pretty close to good language design) shouldn't rely on things that are explicitly specced not to matter (and names do not matter - there are no 'magic names' that the compiler will interpret. A name is whatever you want it to be, and carries no particular meaning. A parameter named 'foo' and a field named 'foo' are unrelated.

But, your use case is trivially solvable. Annotate your constructor with `@Builder`. Not the entire class.

**Comment by vbuciuc** [comment]
@rzwitserloot I agree that it's trivially solvable. 


It's just that it's very easy for somebody to switch the field order or parameter order or add a constructor without realizing what the consequences are. Maybe just a visible and explicit warning in the docs might be enough.

**Comment by almson** [comment]
@rzwitserloot Constructor parameter names can be anything if `@Builder` is placed on the constructor (which is probably what the user **is looking to do**). But if `@Builder` is placed on the class and the user is actually creating a method that conflicts with what what `@Builder` itself is trying to create, then it's appropriate to enforce that parameter names match. This isn't language design, this is enforcing the correct use of an extension mechanism.

**Comment by rzwitserloot** [comment]
> But if @Builder is placed on the class and the user is actually creating a method that conflicts with what what @Builder itself is trying to create, then it's appropriate to enforce that parameter names match. 

It's tricky here; if you put Builder on a method, then the names do matter: It's the only thing lombok gets in order to name the 'setter' methods of the builder; as `@Builder` on a class is just syntax sugar for putting it on the default AllArgsConstructor, which is normally derived from fieldnames, all is well. Toss in a handwritten constructor instead, and lombok will silently use the fields in order to figure out what to do, but then use the constructor you wrote to actually instantiate the object.

This change would be backwards incompatible. But, reconsidering the fact that builder elevates param names by its very nature, and that a mismatch between your fields and an explicitly written constructor effectively dooms you anyway... maybe?

It gets real complicated though. Imagine you have this:

```
@Builder
class Example {
    String a, b;

    Example(Object a, String b) { ... }
}
```

This currently works fine with builder - builder-on-a-class passes each and every field, in that order, and typed the same way the field is, to the constructor, without checking if it even exists. It does in this snippet, even though the types don't match.

Should lombok warn about the above? If we go with a warning, what's the solution to get rid of the warning? I guess the only way out is to go ahead and rename your parameter, because I rather doubt `@Builder(allowWonkyNames = true)` is a good idea, and we can't add 'keys' to `@SuppressWarnings` easily or even piggy-back on existing ones.

What about:

```
    @Builder class Example {
        String a, b;
        Example(String... a) {}
    }
```

should we warn there?

**Comment by janrieke** [comment]
What about a config file option like `nonMatchingParamNames = [ignore, warning, error]` with `warning` as default?
You could get rid of the warning quite easily without cluttering the annotations with (for 99% of the users) unnecessary parameters. And, more importantly, we could also cover `@With`, which has the same problem.
