### ISSUE TITLE
[FEATURE] Jacksonized use Builder.Default to set JsonProperty.defaultValue

### ISSUE THREAD

**Issue by almson** [rzwitserloot/lombok#2673]
**Describe the feature**
Jackson uses `@JsonProperty(defaultValue="...")` to document the default value. `@Builder` uses `@Builder.Default` and a field initializer to implement a default value. It would be nice if the Jackson metadata was generated from the corresponding Builder functionality.

**Describe the target audience**
This feature benefits those who produce documentation and schemas of their Jackson classes. For example, I use https://github.com/mbknor/mbknor-jackson-jsonSchema It is really awesome because it works with https://github.com/json-editor/json-editor to automatically generate web forms.

**Example**
Here is the proposed syntax:

    @Jacksonized @SuperBuilder
    static class Config
    {
        @Builder.Default
        final Foo value = Foo.of (45);
    }

Here is valid Java code that I currently write:

    @Jacksonized @SuperBuilder
    static class Config
    {
        static final Foo DEFAULT_VALUE = Foo.of (45);
        static final String DEFAULT_VALUE_STRING = "45";

        @JsonProperty(defaultValue = DEFAULT_VALUE_STRING) 
        @Builder.Default
        final Foo value = DEFAULT_VALUE;
    }

Note that the annoying thing with writing code without the proposed feature is the Java requirement that annotation parameters be constant expressions. What lombok should do is call the `@JsonValue` method of Foo (often, toString) and use it to set `defaultValue`. Java doesn't allow doing that, so the default value has to be duplicated as a string literal.

**Comment by rzwitserloot** [comment]
> Note that the annoying thing with the current code is the Java requirement that annotation parameters be constant expressions. I'm not sure if it's possible to work around that in lombok.

Lombok cannot really work around this. If it sniffs of something that could end up being a CTC (such as `@Whatever(something = AClassNameThatDoesNotExistAtAll.FOOBAR)`, then lombok can probably get its hands on it, but this has proven to be very fragile (read: hard to get right, tends to require wildly different strategies in different tooling environments, and tends to break even on fairly minor new JDK releases) so I really don't want to go there.

I'm also highly skeptical of silently just equating the `.toString()` output of your default value as being a valid standin for the value itself. That's not usually the case.

For example:

```
List<String> x = List.of("Hello, ", "World");
sysout(x.toString());
> [Hello, , World]
```

note how that toString output is indistinguishable from `List.of("Hello", "", "World")`,or for that matters, `List.of(someObjWhoseToStringReturnsHello, "", "World")` and therefore, cannot be used to reconstruct.

**Comment by rzwitserloot** [comment]
> If it sniffs of something that could end up being a CTC (such as `@Whatever(something = AClassNameThatDoesNotExistAtAll.FOOBAR)`)

Rereading, that is not particularly clear.

Javac will just give up and hard error (never running annotation processors, thus, lombok hasn't even been started yet) if within the confines of the annotation processor (AP) spec a compiler error is inevitable.

According to spec, APs can only generate new stuff and not modify existing stuff. That's not actually true (hence, why lombok works), but it does restrict the syntax lombok can allow. The reason `DoesNotExistAtAll.FOO` works is because it doesn't exist now, but some processor may add it later, thus javac has to keep going. But, `DoesExist.NON_EXISTING_THING` will fail and there's nothing lombok can do about it, because javac will give up on the spot.

**Comment by almson** [comment]
Thank you for considering this. I've reworded the OP a bit.

Some points:
  - I think you misunderstood the constant expression issue. The desired syntax does not violate Java rules. I shouldn't have mentioned it.
  - `toString` wasn't an arbitrary choice--it's annotated with @JsonValue. I realize that looking for the annotated method might make the feature even more difficult.
  - It doesn't matter if the value can't roundtrip because it's metadata to display to the user or in documentation, although obviously the developer should try to ensure that it does.

**Comment by almson** [comment]
I don't want to spam you with issues, but is it technically possible to convert javadoc comments into `@JsonPropertyDescription`?

**Comment by rzwitserloot** [comment]
> is it technically possible to convert javadoc comments into `@JsonPropertyDescription`?
That is probably technically possible, but I worry that there are context where javadoc disappears on us. Given that javadoc's already gone, the fact that we therefore cannot copy that javadoc around to the stuff we generate feels irrelevant, but when it changes the actual code we generate, I'm a little more skeptical. Some extra tests and a few caveats in the docs about such a feature would be warranted.


I think the crucial problem that needs solving before this can turn into a feasible feature request is this dilemma:

We want to generate: `@JsonProperty(defaultValue="45")` off of `@Builder.Default Foo value = Foo.of(45);`

And do so automatically, with no hints whatsoever other than the fact that the `@Builder` annotation making this happen has a sibling `@Jacksonized` annotation to go along with.

This then leads to:

* How do we turn `Foo.of(45)` into `"45"`? There is no runtime available. Lombok cannot compile just `Foo.of(45)` and deign to run toString on this; Lombok also cannot open up `Foo.java` or `Foo.class` and dig around. All lombok gets is an AST of: `MethodInvoke(receiver = Ident("Foo"), msg = "of", params = [IntLiteral[45]])` and __that is all the context we get__, and need to get to 45 from there. How do we do that? It's easy enough if it's `@Builder.Default int x = 5;` or `@Builder.Default List<String> foo = List.of("Hello", "World");`, in that lombok can ship with built-in knowledge about what `int` is or what `List.of` does, but we can't ship with built in knowledge of what `Foo.of` is, as Foo isn't in the java core package or in a major library. Also, what if it's `@Builder.Default long start = System.currentTimeMillis()` - forget lombok for a moment, how would you write your `@JsonProperty` annotation? Would you write just `@JsonProperty`, leaving the default value unspoken, or would you shove a string description in there (`@JsonProperty(defaultValue="now")`? If it's `now`, lombok stands no chance of ever generating that without resorting to complicated mechanisms and/or resolution, I think.

* If we go with the route of 'eh, if not possible, then do not bother', how do we give the programmer control of whether or not we generate those `defaultValue` annoparams? What if you don't want us to do it? What if you want defaultValue annoparams for everything and you want warnings or errors if lombok is deciding not to add them because it doesn't feel confident it knows how to turn the initializing expression, into a string literal describing it? I can see someone wanting a defaultValue param everywhere, and therefore wanting a warning or error out of lombok if lombok can't figure it out, so that the author of the code can then handroll the `@JsonProperty` annotation where needed, and rely on lombok to do it for those fields whose defaults are context-free understandable, such as `5` or `"Hello"` or `null`.

A description of how we'd tackle those problems is probably the next step to get this proposal moving forward.

**Comment by almson** [comment]
You're right, it's hopeless to do this properly in the general case.

But, again, this is just metadata for documentation. As they say, bad documentation is a lot better than nothing. So I think it'd be a net positive to do this for literals. Even non-literals could be handled just by displaying the bit of java code. (So, it would handle even `System.currentTimeMillis()`.)

This could be controlled by a config key with values: off, literals only, all, and "only literals but warn when the default value is not a literal and a custom value isn't given".

I would add a `display` attribute to `Builder.Default` for this so that `@JsonProperty` doesn't need to be used, to make the config logic simpler, and to have control in case something in Jackson changes or another framework is supported.

**Comment by rzwitserloot** [comment]
So, just so I understand you correctly, the string value of the `defaultValue` annoparam of `@JsonProperty` contains human english - it's documentation, not something an automated tool is ever going to parse as an expression, right?

**Comment by janrieke** [comment]
Maybe at the moment, but the [Jackson docs](https://fasterxml.github.io/jackson-annotations/javadoc/2.10/com/fasterxml/jackson/annotation/JsonProperty.html#defaultValue--) explicitly mentions that this may change:
> It is possible that in future this annotation could be used for value defaulting, and especially for default values of Creator properties, since they support required() in 2.6 and above.

Thus, I don't think that it's a good idea to automatically generate this (at least for non-trivial cases like objects).

**Comment by rzwitserloot** [comment]
@janrieke it sounds primarily that my use case of: "I wish for all `@Builder.Default` annotated elements to either get a lombok-generated `defaultValue` annoparam, or, a warning/error generated by lombok that lombok doesn't know how" is important, because the alternative would appear to be that you just kinda guess what lombok can and cannot do, and that doesn't sound like a good plan at all.

**Comment by janrieke** [comment]
I thought a bit on this proposal, and I think there are further fundamental problems:
1. Putting the annotation only inside the builder will have no effect for documentation purposes. It must be placed on the property of the class itself. But if Lombok would do that, why should only a `@Builder.Default` trigger this behavior, and not a regular init expression? A regular init expression will have the same effect when you have a `@Data` class, where you have a no-args constructor and setters. But it has no effect when Jackson uses an `@AllArgsConstructor`. Generating the correct documentation is not trivial, and it may change with new Jackson versions.
2. Generating `@JsonProperty` can unexpectedly change Jackson's behavior. For instance, if you have a `@JsonIgnore` on a setter, Jackson will ignore the corresponding property completely. If Lombok would put a `@JsonProperty` on the field, the property will suddenly be visible, only the setter would be ignored.

I don't think this feature request is a good idea.

**Comment by almson** [comment]
> Maybe at the moment, but the [Jackson docs](https://fasterxml.github.io/jackson-annotations/javadoc/2.10/com/fasterxml/jackson/annotation/JsonProperty.html#defaultValue--) explicitly mentions that this may change:
> 
> > It is possible that in future this annotation could be used for value defaulting, and especially for default values of Creator properties, since they support required() in 2.6 and above.
> 
> Thus, I don't think that it's a good idea to automatically generate this (at least for non-trivial cases like objects).

I can't imagine that happening. Nothing in the current contract of `defaultValue` says it has to be valid for deserialization. It would be a very breaking change. Besides, while it may be useful for `@JsonCreator` constructors/methods because Java doesn't have default parameters, it would be pointless and doubly breaking for setters. This is going to stay as documentation.

> why should only a @Builder.Default trigger this behavior, and not a regular init expression (when not using a builder)?

I don't know, are there plans to support `@Jacksonized` for something other than `@Builder`? I like the Jackson+Builder combo. I like that it's set up analogous to and hopefully compatible with soon-to-be-released [Record types](https://openjdk.java.net/jeps/384). I don't like no-arg constructors and non-final fields and I don't like `@Data`.

> Generating @JsonProperty can unexpectedly change Jackson's behavior. For instance, if you have only a @JsonIgnore on a setter (but no @JsonProperty on the field), Jackson will ignore the corresponding property completely. If Lombok would put a @JsonProperty on the field, the property will suddenly be visible, only the setter would be ignored.

Again, in the context of Jacksonized Builder I don't see the issue. When `@JsonIgnore` is put on the field it's ignored correctly.

**Comment by janrieke** [comment]
> Again, in the context of Jacksonized Builder I don't see the issue. When `@JsonIgnore` is put on the field it's ignored correctly.

I did some testing and I think you are right. I thought (not for the first time) that the "virtual property" concept (i.e., that getter, setter, and field form a unit, and annotating just one of them covers all) does extend to builders (i.e., also the builder's setter would be ignored). It is _not_. That's also the reason we copy `@JsonIgnore` onto the builder's setter (I remember now).

That means putting a `@Jacksonized` on a class already affects the annotation's effect. I don't like that, but apparently that's the way the Jackson designers want it.

However, coming back to point 1, this means we really have to restrict this feature to `@(Super)Builder`.

**Comment by rzwitserloot** [comment]
> I don't know, are there plans to support @Jacksonized for something other than @Builder?

Not concrete ones, but as @janrieke mentioned, tightly binding:

_lombok will generate, on this very field, a `@JsonProperty` annotation in order to provide the `defaultValue` annoparam_

and

_`@Builder.Default`_


together is a mistake, because these two things aren't inherently related. Even if that would seem to result in what you wanted and have no immediately problems... Tightly binding unrelated concepts together, in my experience, leads to both a library that is hard to understand, and severely hampered ability to evolve a library in a backwards compatible fashion in the future.

I concur with @janrieke and this FR has reached a phase where it is clear it'll never cross the value/money bar within a reasonable timeframe, unfortunately. Let's drop it.

**Comment by almson** [comment]
The proposal does not tightly bind Builder.Default to JsonProperty. It proposes that 1) Builder generates a `Builder.Default.doc` (or `.display` or whatever) attribute (and/or a javadoc comment) which may have multiple uses. 2) Jacksonized uses this doc when creating JsonProperty. I'm not proposing validation, deserializability, warnings, or Jackson compatibility for `Builder.Default.doc`. I don't think any of those things are necessary or desirable.
