### ISSUE TITLE
[BUG] NullPointerException during Javadoc copy

### ISSUE THREAD

**Issue by Rawi01** [rzwitserloot/lombok#2682]
**Describe the bug**
Lombok does not check if the source javadoc is `null`. This leads to a bunch of NPE as soon as lombok tries to create a regex matcher. The exception gets catched in one of the calling methods and does not lead to a compilation error.

**To Reproduce**
- Add a breakpoint for thrown NullPointerExceptions
- Run tests

**Expected behavior**
Obviously there should be no exception. I also noticed that there are javadoc copy methods in `HandlerUtil` that only add new javadoc lines (e.g. `addReturnsThisIfNeeded`). Right now these methods get never called if the input is empty because of the exception. Is this intended? If not, lombok could also create the javadoc, I added an example how the result could look like. 

**Input**
```java
@lombok.experimental.Accessors(chain = true, fluent = true)
@lombok.Setter
class Example {
	private int fieldName;
}
```

**Current output**
```java
class Example {
	private int fieldName;

	@java.lang.SuppressWarnings("all")
	public Example fieldName(final int fieldName) {
		this.fieldName = fieldName;
		return this;
	}
}
```

**Possible output**
```java
class Example {
	private int fieldName;

	/**
	 * @return {@code this}.
	 */
	@java.lang.SuppressWarnings("all")
	public Example fieldName(final int fieldName) {
		this.fieldName = fieldName;
		return this;
	}
}
```

**Version info (please complete the following information):**
 - Lombok version: **latest**
 - Platform: **all**

**Additional context**
I can provide a PR if you let me know how lombok should handle these cases.

**Comment by rzwitserloot** [comment]
> Right now these methods get never called if the input is empty because of the exception. Is this intended?

It's not. Bad exception handling is one of my pet peeves but I think this is my code. Whoopsie!

Sounds like lombok should do a quick null check in general (avoid the exception chain, even if that leads to the same end result of nothing happening). and in the case of lombok making up javadoc because it has something to add (such as `@return {@code this}`), I think we might as well add that, right? (so, change the behaviour from the current: "Does not generate `@return {@code this}` unless there was already javadoc to copy" to a proposed: "Will generate javadoc with just `@return {@code this}` in that case".

**Comment by Rawi01** [comment]
Thats what I thought too but as that needs adjustments in a bunch of test cases I don't want to waste time changing everything without asking.
