### ISSUE TITLE
[BUG] Different checker framework annotations for SuperBuilder

### ISSUE THREAD

**Issue by Rawi01** [rzwitserloot/lombok#2692]
**Describe the bug**
While checking the diff for #2690 I noticed that the generated checker framework annotations are different in ecj and javac. 

**To Reproduce**
https://github.com/rzwitserloot/lombok/blob/6f218d5ba896820bfc11143fefacccca8f8042d6/test/transform/resource/after-ecj/NullAnnotatedCheckerFrameworkSuperBuilder.java#L159-L161
https://github.com/rzwitserloot/lombok/blob/6f218d5ba896820bfc11143fefacccca8f8042d6/test/transform/resource/after-delombok/NullAnnotatedCheckerFrameworkSuperBuilder.java#L231-L234

**Expected behavior**
I don't know which one is right but using different annotations seems to be wrong.

**Version info (please complete the following information):**
 - Lombok version: **latest**
 - Platform: **all**

**Additional context**
Seems to be okay for the normal builder and is also wrong in the `CheckerFrameworkSuperBuilder` test.

**Comment by rzwitserloot** [comment]
I think they should both be on there.
* `@NonNull` is appropriate because this method cannot possibly return `null`. One disconnect between lombok's 'mindset' about these things vs. checkerframework is that checkerframework does not really make a demarcation between spec and implementation: In this case, the annotation is not needed because the checkerframework is perfectly capable of figuring this out on its own based on the code, but, [A] explicitly annotating helps any AP ordering conflict issues / issues with checkerframework failing to find/process the generated code, and [B] lombok DOES think there is a difference: If a method is explicitly annotated as `@NonNull`, that's a promise, and changing it later would be a backwards break, whereas if CF analyses it, that does not comprise a future promise.
* Unique is also appropriate: The value returned from this method is a unique reference: No field or stack anywhere in the running VM could possibly refer to the object returned by this. The only 'pointer' to it is what this call returns.

Thus, they should have both.
