### ISSUE TITLE
[BUG] Different behavior of @Delegate in Eclipse and IntelliJ

### ISSUE THREAD

**Issue by Wdestroier** [rzwitserloot/lombok#2766]
**Describe the bug**
In eclipse you can annotate a field with @Delegate and, if the method doesn't already exists in the current class file, it will be generated. If you open the same code in IntelliJ it will give a duplicated method error. A fix to this problem can be adding an exclusion @Delegate(excludes = ...)

**To Reproduce**
Create a new project in eclipse and another in IntelliJ. Create a new class called MyInputStream. Paste this code in it: https://pastebin.com/JtmuLRku . Try to compile.

**Expected behavior**
The same code must compile or not compile in eclipse and IntelliJ.

**Version info:**
- Lombok version: 1.18.16
- Java version: "11.0.7" 2020-04-14 LTS
- Eclipse version: 2020-12
- IntelliJ version: 20.3.2 x64

**Comment by Rawi01** [comment]
Please do not report any problems or feature requests for the intellij plugin here; file these with the [intellij lombok plugin github repo](https://github.com/mplushnikov/lombok-intellij-plugin/issues).

Since version 1.18.16 lombok skips already implemented methods. It seems like this was not added in the IntelliJ plugin.
