### ISSUE TITLE
@EqualsAndHashCode generating Unecessary casts

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#345]
_Migrated from Google Code (issue 272)_

**Comment by rzwitserloot** [comment]
@simioni.eduardo let's say lombok added that setting. Take it to its logical conclusion. `@EqualsAndHashCode` would have, literally, 90 different parameters. Obviously a crazy plan.

Reconsidering it, and given how this is never ever going to bubble to the top of the pile, along with various other issues (such as how this is not gonna play well with valhalla), I'm just gonna call time of death on this issue.

Besides, since this issue was opened we've adopted a policy that any linter tool that gets annoyed by lombok code is to be fixed by instructing the linter to stop linting generated code. If the linter doesn't let you do that, file a bug report with the linter. It's perhaps a bit 'kicking the can down the road', but, honestly, linting generated code of any stripe is a silly notion.

Note that lombok can (and does) generate annotations that indicate the method is generated. Various linter tools CAN be configured (and you can tell lombok to add annotations, too).
