### ISSUE TITLE
@Builder clobbers initial field values

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#703]
_Migrated from Google Code (issue 668)_

**Comment by edudar** [comment]
+1
`@Builder` should carry values from original fields to respective ones in builder class

**Comment by Maaartinus** [comment]
> I ran into this same issue. I was under the assumption that the builder would initialize the object with a noArgs constructor and then call the setters for the specific fields that had been assigned while building.

A builder is typically used for immutable objects, so the `@AllArgsConstructor` is the way to go.

---

> `@Builder` should carry values from original fields to respective ones in builder class

This may not be always possible, e.g., for something like

    int x = aProtectedMethodOfASuperclass();

I guess, such funny things are pretty rare.

---

As `@Builder(toBuilder = true)` has been implemented, my above workaround should work:

    new MyComponent().toBuilder().someString("fish").build();

To make fool-proof, define

    public Builder builder() {
        return new MyComponent().toBuilder();
    }

in the containing class instead of letting Lombok generate it.
