### ISSUE TITLE
Add support constructing via setters for classes annotated with @Builder

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#783]
_Migrated from Google Code (issue 748)_

**Comment by jrglee** [comment]
This feature would be great. It also eliminate another limitation of the builder which is losing all the default values, i.e.: collections are usually initialized in the declaration or in the default constructor; by having an all args constructor supporting the builder you have the chance of initializing an object with an null collection inside.

The setter-based builder would only set the available values, you could also protect your setter and ignore null values on collections. It is a win-win.

**Comment by rzwitserloot** [comment]
@jrglee solving the 'default value issue' is a separate problem; we certainly wouldn't want to encourage lombok users to give their classes setters (even private ones) JUST to enable defaults. In fact, potential abuse means I'm less inclined to make this feature request happen.

Accepted, but because of the issue raised by @jrglee, blocked until we solve the need for defaults in builder.

We can probably just do the right thing by default if you have either an explicit no-args constructor OR you have no constructors, AND `@NoArgsConstructor` and no other `@XArgsConstructor` on the class. In that case we'll just build-by-setter instead.

**Comment by rzwitserloot** [comment]
NB: To work around this, you can make a static method that constructs a new instance and then calls .set() for everything; then put `@Builder` on that. Alternatively, make an all-args constructor and do the same thing. Then put `@Builder` on that.

**Comment by jrglee** [comment]
@rzwitserloot Few months after I wrote my last comment I learned how to use the `toBuilder` method. Something like

```
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class Foo {

    @Getter
    private String greeting = "hello";

    public static FooBuilder builder() {
        return new Foo().toBuilder();
    }
}
```

In this way I can call builder without having to provide a value to `greeting`. It solves the default value issue and even preserves immutability in my example. I learned this trick while reading about another issue. It would be nice to have this example in the main documentation too.

**Comment by ioan-miklosik-sv** [comment]
Hi, I am also facing a situation when this feature would be useful, the one in the title I mean. I am using both @Data and @Builder on my data object and am creating a custom setter for one of the fields, setter which does a slight transformation on the value before assigning it to the field. When using the JavaBeans pattern it is fine, my value is transformed when the setter is called. But this does not happen when using the builder. The setter is bypassed in this case. Do you have a suggestion for this case, is there an "elegant" solution for this or just workarounds? Please suggest the best workaround (except duplicating code in the builder method) in this last case. Thank you.

**Comment by rzwitserloot** [comment]
between `@Builder.Default` and `toBuilder=true`, the use cases are adequately addressed. We won't add this feature.

**Comment by baldram** [comment]
> The elegant solution is to never use setters if at all possible. ;-) Write a constructor, put a Builder annotation on it, replace the Data annotation with a Value annotation, never look back.

@randakar I like your idea with "no setters at all". There is an issue when writing the constructor manually. The `@Builder.Default` seems to not work then. What do you advise?

**Comment by Maaartinus** [comment]
@baldram I'm not sure, IIUYC, but I guess, with a manual constructor, you can just leave out both `@Builder.Default` and the initializer expression and initialize the field in the constructor.

The trick from the above https://github.com/rzwitserloot/lombok/issues/783#issuecomment-281441785 may also help. In case, you dislike `new Foo()`, then you can use a private static final Foo instance.

**Comment by baldram** [comment]
That's it! You're right @Maaartinus. The `Builder.Default` is simply redundant in this case. I have a classic initialization and it's even more clear.
Now let's take @rzwitserloot [suggestion](https://github.com/rzwitserloot/lombok/issues/783#issuecomment-430002803). Finally, it looks good. Using `@Builder` annotation on constructor in combination with `toBuilder=true` I'm able to do what I need. What was my problem to solve? Updating Hibernate references in case of bidirectional mapping. All done respecting immutability! :-)

**Comment by randakar** [comment]
If anyone knows a way to define hibernate models without having to resort to setters and a no-args constructor, I'm all ears. Immutable classes and hibernate seems to be fully mutually incompatible.

**Comment by MayCXC** [comment]
this feature would fix builders for subclasses with private fields, which don't work well now. @SuperBuilder doesn't always work for that either.

**Comment by rzwitserloot** [comment]
@MayCXC I have no idea what you mean. Can you post an example of first a class hierarchy that 'applies' (doesnt work now, whether you try to use `@Builder` or `@SuperBuilder`), but where invoking setters would somehow fix this.

**Comment by MayCXC** [comment]
sure, it's a specific case but say you extend a code generated class Entity with your own class ExtendsEntity to add some behaviors to it. If you want to generate an ExtendsEntity.Builder subclass that sets private fields in Entity, right now your only option is to copy and paste a constructor from Entity to ExtendsEntity and annotate it with @Builder. If @Builder looked for public setters, it could see setters that ExtendsEntity inherited from Entity and make a full Builder without copy pasting a constructor. This could also be useful for annotations like @AllArgsConstructor that generate an empty constructor in child classes that cannot see their parent's fields.

**Comment by janrieke** [comment]
I'm quite sure your use case works with a `@SuperBuilder` with minor customizations. Feel free to create a StackOverflow question if you need help with that.

**Comment by rzwitserloot** [comment]
@MayCXC Ah, I see. No, we can't do that. If we could do that, `@SuperBuilder` would have been barely necessary.

The problem is, what you want requires [resolution](https://github-wiki-see.page/m/projectlombok/lombok/wiki/LOMBOK-CONCEPT:-Resolution) which is tricky (see the link).

**Comment by MayCXC** [comment]
@rzwitserloot ok, thanks for your response. we have since moved on to implementing generated interfaces instead of extending generated classes, which has the advantage that our lombok and jpa annotations work nicely with one another, and it seems like a much better pattern for this use case. So if anyone finds this issue trying to fix the same problem, maybe try composition instead of inheritance.

**Comment by jennierose** [comment]
I came across a [stackoverflow question](https://stackoverflow.com/q/42379899) with a really clear use case for this:

```
@Data
@Builder
public class User {
    private static final PasswordEncoder ENCODER = new BCryptPasswordEncoder();

    private String password = null;

    // In some cases it can be really problematic to bypass the accessor methods!!
    public void setPassword(@NonNull final String password) {
        this.password = ENCODER.encode(password);
    }
}
```

Would it be possible to add a simple configuration option to tell lombok to use accessor methods to get and set variables? I know it's possible to override an `@AllArgsConstructor` or a specific method in a `@Builder` class, but delomboking part of a class just to change `this.field = field` to `this.setField(field)` makes me wonder if there should be a more elegant solution here.

**Comment by MayCXC** [comment]
@jennierose something I was also going to try was `lombok.accessors.chain = true` with https://projectlombok.org/features/GetterSetter, which should work with inheritance, and provide about the same `new Instance().setX(x).setY(y).setZ(z)`... syntax as a builder. But if you need the actual builder class this won't work.

**Comment by rzwitserloot** [comment]
@jennierose I don't think that's a good example. I find that code deplorable - it's going to cause confusion, and given that security issues usually cannot be easily tested, confusion is _deadly_. You have a field named `password`, and it is lying to you. It doesn't contain the password at all. It contains a passhash.

That class should be written as follows:

```java
@Data
public class User {
    private static final PasswordEncoder ENCODER = new BCryptPasswordEncoder();

    // Depending on what you want, you may want to tag this with:
    // @Setter(AccessLevel.NONE)
    private String passHash;

    public void setPassword(@NonNull String password) {
        passHash = ENCODER.encode(password);
    }
}
```

After all, in your example, your User class would operate as `.setPassword("hello")` works fine, and then `.getPassword()` returns something completely different. See how that is confusing?

Once we have the above established is the proper way to write the class, we then get to the gnarly question of what the builder should look like. In this case we really don't want a `setPassHash` style method in that builder... or do we? Maybe you have a passHash instead. Should it be possible to make new user objects based on a passHash? If you're creating User objects based on JPA or any other database solution, then you surely do - the passHash is all you have. In fact, in practice, when would you ever create a user object using an actual password, via a builder? Perhaps when the user signs up, and you're about to `save()` this user object to the database? In which case it might just be smarter to leave the pass hashing separate from the builder step. Perhaps you should simply be writing:

```java
  User.builder()
    .passHash(User.hashPassword(passEnteredOnNewUserForm))
   .build();
```

Where `hashPassword` is a method you write in an appropriate context - could be a `static` method in `User` itself, or if you have some sort of `UserFactory` because the pass hash algorithm is configurable, then in that factory.

The question more generally boils down to: What if I want an alternate way to set a property and also want to eliminate the normal way to set that property. You can trivially do the alternate-set thing (write the actual builder class and include the method), but telling builder to not generate the usual setter is not currently possible. Given that I don't see an easy syntactical way to do so, I doubt we'll ever add such a thing.

I in fact adopt your case as proof that we should _not_ do this. Feels like delivering this feature is the proverbial handing the foot-bazooka to journeyman developer and watching the fireworks.
