### ISSUE TITLE
Inconsistent hashcode when using indirection in @EqualsAndHashCode(exclude={})

### ISSUE THREAD

**Issue by fabmars** [rzwitserloot/lombok#888]
Using Lombok 1.16.4 on Linux + JDK8_51 x64
Consider the following code:

``` java
@Data @Builder @EqualsAndHashCode(exclude = { Mail.UID })
public class Mail {
    public final static String UID = "uid";

    private String uid;
    private String to;
    private String subject;
    private String content;

    public static void main(String[] args) {
    Mail plop1 = Mail.builder().subject("Hello").to("mark@fb.com").build();
    System.out.println(plop1.hashCode());
    Mail plop2 = Mail.builder().uid("012345").subject("Hello").to("mark@fb.com").build();
    System.out.println(plop2.hashCode());
    }
}
```

Output: 1484447000 and 373267937 !!!
Also note that Eclipse issues a warning on the exclude : "This field doesn't exist or would have been excluded anyway".

Now, use @EqualsAndHashCode(exclude = {"uid"})
Output: 1472535018 and 1472535018 => All right.

**Comment by rspilker** [comment]
Yeah, referring to constants in annotations doesn't work so well. Especially if they are in another file. In this case, possibly we could also generate a similar warning in javac, or even recognize the pattern and give a better warning/error.

**Comment by fabmars** [comment]
Sounds like you're telling me it's not easy to fit.

**Comment by Maaartinus** [comment]
Slightly OT: IIRC there was already a proposal to switch to annotations (`@EqualsAndHashCode.Exclude` or maybe `@Exclude.EqualsAndHashCode`) or allow both annotations and string arguments (but not both at the same time) for compatibility. Any news on it?

**Comment by kobbikobb** [comment]
This seems to be a limitation with java.
https://stackoverflow.com/questions/2065937/how-to-supply-value-to-an-annotation-from-a-constant-java

The problem seems to be that exclude is an array.

This might be possible with a String annotation.
In theory this could be solved with a single string value property, either supporting one value or a comma separated values.

I think this would make the abstraction worse.
I would vote to close this with won't fix.

What do you think?

**Comment by rspilker** [comment]
We now do have the `@EqualsAndHashCode.Exclude`, making this feature obsolete.
