### ISSUE TITLE
Getting error while compiling on OSX (all java versions)

### ISSUE THREAD

**Issue by martintreurnicht** [rzwitserloot/lombok#930]
We've been using lombok for more than a year now, but since our update to 1.16.6 i'm getting this error while compiling on mac osx:

 ``` warning: lombok.javac.apt.Processor could not be initialized. Lombok will not run during this compilation: java.lang.RuntimeException: java.lang.ClassNotFoundException: lombok.javac.handlers.HandleHelper ```

Switching back to 1.16.4 seems to resolve the issue

**Comment by askoning** [comment]
This seems similar to #826 - but for some reporters in that thread 1.16.4 was actually the culprit

**Comment by martintreurnicht** [comment]
@askoning I would agree with you, but the root cause of the issue i'm getting seems to be a missing class `lombok.javac.handlers.HandleHelper` which then causes initialization to fail

**Comment by rzwitserloot** [comment]
@martintreurnicht Can you send us the complete stack trace? I did a quick peek at the place that generates this error, and it should have given you a complete stack trace. We like line numbers.

**Comment by rspilker** [comment]
I've just created an [edge release](https://projectlombok.org/download-edge.html). After download, you probably need to rename the file from `lombok-edge.jar` to `lombok.jar`.

If you use that version, during compilation a warning should occur containing a reference to a report file that's created in your temp directory. You can also just look in your temp directory for files called 
`lombok-processor-report-*.txt`.

This file probable tells you where the problem comes from. If you cannot figure it out, can you copy the contents of the file to this issue so we can have a look as well?

**Comment by martintreurnicht** [comment]
I'm not sure what caused the issue originally but it seems that it started working again, might be some kind of weird classpath issue but it's no longer an issue.
