### ISSUE TITLE
Delimiter attribute for the ToString annotation

### ISSUE THREAD

**Issue by astrapi69** [rzwitserloot/lombok#934]
Hi there,

the ToString annotation does not provide a delimiter when delimiting the fields. The default delimiter now is a comma like:

public String toString() {
    return "ToStringExample(" + this.getName() + ", " + this.shape+ ")";
   }

but better would be to set the annotation i.e. 

@ToString(delimiter=":")

and results to

String delimiter = ":";
public String toString() {
    return "ToStringExample(" + this.getName() +delimiter + this.shape+ ")";
   }

**Comment by rspilker** [comment]
Although this might be nice for some cases, we haven't seen this enough. Since the (generated) toString is meant for debugging purposes, the current implementation should be good enough. If you have made the toString format part of your API, a handwritten method might even be better since you need to place the documentation on it anyway.

**Comment by astrapi69** [comment]
I do not think that this is a big feature but it can be comfortable to have it.

**Comment by OksiBlack** [comment]
Totally agree with astrapi69. Even more, custom delimiter can help in debugging. For example, new line will make more explicit and standout output.
