### ISSUE TITLE
Consider adding Java 7 option for Delombok

### ISSUE THREAD

**Issue by awhitford** [rzwitserloot/lombok#975]
I don't think that Delombok considers the Java version when generating code.  Ideally, it should be able to take advantage of new language features when possible.

An example would be leveraging the [Objects.hash](http://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#hash(java.lang.Object...)) function -- but that may only be done when Java 7 or later is the target JDK.  The [Objects.equals](http://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#equals(java.lang.Object,%20java.lang.Object)) function may also be used, generating cleaner looking code.

**Comment by rzwitserloot** [comment]
While 'cleaner', Objects.hash(x, y, z) doesn't generate the same hashes as what lombok would do when you have a class with fields x, y, and z, no matter what these fields are. We're not going to accept delombok generating code that isn't functionally equivalent even if it rarely matters, and we're not going to rewrite the impl of lombok's hashcode generators to fit that, because ours have better hash performance.

Objects.equals() WOULD help though. Still not something we'll generate (hey, we're generating code, why not generate the 'long form' which is more likely to be compatible with stuff?). I worry about the complication of what we call this. delombok serves 2 separate functions:

* Show you _EXACTLY_ what lombok is doing
* Turn your lombok-containing code into code that is as pretty as we can make it, without the lombok

here these two are in conflict. But how do we communicate that in the settings? We can, but at this point I'm not sure this is worth doing.

**Comment by rzwitserloot** [comment]
I checked the current state of delombok and there just isn't a 'prefer cleaner code over code that is as close as reasonable to the stuff lombok does' option. There's `-f:pretty` which is short for a bunch of options to make it look nicer but that isn't the same. We COULD do this but it'd be a lot of work. Doesn't sound worth it.
