### ISSUE TITLE
@ToString includes transient fields while @EqualsAndHashCode does not

### ISSUE THREAD

**Issue by adamsiemion** [rzwitserloot/lombok#996]
There is an inconsistency in handling of transient fields: `@EqualsAndHashCode` does not include transient fields, while `@ToString` does include them.

My usage scenario: I have an application using JPA with bidirectional associations:

```
class User { Department department; }
class Department { Set<User> users; }
```

I would like to use lombok to generate `hashCode()`, `equals()` and `toString()`. I add `@EqualsAndHashCode` and `@ToString` to the `User` and  `Department` class. This of course does not work as the generated methods call themselves infinitely. 

If I mark the users set in Department as `transient` it solves the infinite recursion problem for the `hashCode()` and `equals()` methods as `@EqualsAndHashCode` does not include transient fields, but does not solve the problem for the `toString()` method as  `@ToString` does include transient fields.

**Comment by ElectronicFur** [comment]
With our JPA model we just use _exclude_ in these cases.

For example:

```
@EqualsAndHashCode(exclude={"users", "someOtherMemberToExclude"})
@ToString(exclude={"users", "someOtherMemberToExclude"})
```

**Comment by rzwitserloot** [comment]
This behaviour is intentional. The definition of what 'transient' really means is really just: "java's built in serialization mechanism ignores it."

That's it. We're left to our devices to try to interpret what that means for other interactions. We've decided that it means to skip them for equals/hashCode purposes, but not for toString purposes. As @mennojansz wrote, the 'out' is to exclude them with `exclude=`.

**Comment by ewirch** [comment]
Your decision leads to irritating output in this case:
```
Asserts.assertEqual(obj, differentObj);
```
The message print by JUnit will contain more differences then JUnit actually detected. toString/hashCode/equals should really go hand in hand.
